### ISSUE TITLE
没有删除按钮

### ISSUE THREAD

**Issue by zzjinjin** [fex-team/kityminder-editor#100]
没有删除按钮，对于想把空间整得干干净净的强迫症患者来说真是一场灾难

**Comment by zhangbobell** [comment]
不知道你说的是哪个界面上的删除按钮？
1. 脑图的文件管理界面上有删除文件的选项，在文件右侧末尾的三个小点中；
2. 脑图编辑界面里的工具栏中有删除节点的按钮的，或者直接用 backspace 或 delete 就想能删除节点。
