### ISSUE TITLE
- -；插入链接对话框有Bug，不支持粘贴~

### ISSUE THREAD

**Issue by goldenlove** [fex-team/kityminder-editor#103]
环境： OSX Chrome 45.0.2454

是否已知bug？
另外，能优化下交互不用弹窗么？
就两个输入框，直接在当前选中节点下显示小浮层就好了？

**Comment by zhangbobell** [comment]
这个问题在对话框（除了导入导出节点对话框）弹出的时候会出现问题，我们已经知晓，会尽快修复。合并到 #101，交互方面的事情我们后期会优化。
