### ISSUE TITLE
错误信息

### ISSUE THREAD

**Issue by liangsmood** [fex-team/kityminder-editor#104]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>A Database Error Occurred</h1>\n\t\t<p>Error Number: 2006</p><p>MySQL server has gone away</p><p>INSERT INTO `kityminder_log`\n                (`file_guid`, `user_id`, `operation`, `operate_time`, `ip_address`)\n                VALUES\n                ('09420c81158452a66247840fbcc5599d', '2569406705', 'opened', '2015-09-23 16:42:54', '10.50.149.12')</p><p>Filename: /home/bae/app/models/mbos.php</p><p>Line Number: 1162</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"09420c81158452a66247840fbcc5599d"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by zhangbobell** [comment]
在用户访问量大的时候会出现这个问题，我们已经知晓，会尽快修复。

**Comment by iamocean** [comment]
@zhangbobell 我也遇上这个 BUG，写着写着就弹个框出来，根本就无法用了。

**Comment by zhangbobell** [comment]
目前不会影响用户的数据。

**Comment by zhangbobell** [comment]
这个问题已经修复并上线，见 http://naotu.baidu.com/user/changelog
