### ISSUE TITLE
添加链接时，复制粘贴竟然粘贴至其他地方，这种低级错误，请问做回归了吗。。。如图

### ISSUE THREAD

**Issue by dlutls** [fex-team/kityminder-editor#105]
![1](https://cloud.githubusercontent.com/assets/8817369/10063753/c64d9a96-62a3-11e5-9123-3d5d98530f17.png)

**Comment by zhangbobell** [comment]
这个问题在对话框（除了导入导出节点对话框）弹出的时候会出现问题，我们已经知晓，会尽快修复。合并到 #101
