### ISSUE TITLE
在百度脑图，支点主题备注中，建议强调可以加入颜色

### ISSUE THREAD

**Issue by Higenk** [fex-team/kityminder-editor#106]
我发现在备注的时候，如果同时使用GFM语言：*_这是斜体和加粗_*的时候，在观看时，字体颜色会变成红色。既然如此，为何不加入其他颜色供选择呢？

**Comment by zhangbobell** [comment]
备注输入框是一个 markdown 编辑器，并不是一个富文本编辑器，设计的初衷是为了头脑风暴或工作规划时简单的记录，而不是着重于样式。
