### ISSUE TITLE
几乎每十多秒就会弹出一次

### ISSUE THREAD

**Issue by YarKb** [fex-team/kityminder-editor#111]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>A Database Error Occurred</h1>\n\t\t<p>Error Number: 2006</p><p>MySQL server has gone away</p><p>SELECT `user_name`\n                FROM `kityminder_user`\n                WHERE `user_id` = '2701718212'\n                LIMIT 1</p><p>Filename: /home/bae/app/models/mbos.php</p><p>Line Number: 999</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"b397204db4a7\",\"created\":1443766194,\"text\":\"团队协作与效率提升\"},\"children\":[{\"data\":{\"id\":\"ayvwennsasws\",\"created\":1443766208161,\"text\":\"有哪些协作情景\"},\"children\":[{\"data\":{\"id\":\"ayvweqyw18w8\",\"created\":1443766215362,\"text\":\"甲方/客户\"},\"children\":[{\"data\":{\"id\":\"ayvwf09k6cc0\",\"created\":1443766235599,\"text\":\"查看提交的文档与设计稿\"},\"children\":[{\"data\":{\"id\":\"ayvwfnshks4c\",\"created\":1443766286809,\"text\":\"批注\"},\"children\":[{\"data\":{\"id\":\"ayvwl2bponk8\",\"created\":1443766710267,\"text\":\"提出修改\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwfotwxbks\",\"created\":1443766289072,\"text\":\"Check\"},\"children\":[{\"data\":{\"id\":\"ayvwl618a74k\",\"created\":1443766718342,\"text\":\"这个版本OK了\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvx3ahaoo44\",\"created\":1443768138574,\"text\":\"获知更新\"},\"children\":[{\"data\":{\"id\":\"ayvx3cgpgoow\",\"created\":1443768142892,\"text\":\"乙方更新了版本\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"ayvwey9la4ck\",\"created\":1443766231247,\"text\":\"观察者\"},\"children\":[{\"data\":{\"id\":\"ayvwnmkz5i8k\",\"created\":1443766911091,\"text\":\"全局视角\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvweullcmos\",\"created\":1443766223265,\"text\":\"项目管理者\"},\"children\":[{\"data\":{\"id\":\"ayvwfv2fxr4k\",\"created\":1443766302648,\"text\":\"项目进度把控\"},\"children\":[{\"data\":{\"id\":\"ayvwh413y08o\",\"created\":1443766400523,\"text\":\"日历功能\"},\"children\":[]},{\"data\":{\"id\":\"ayvwh64xde88\",\"created\":1443766405107,\"text\":\"提醒功能\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwfz6iv3sw\",\"created\":1443766311602,\"text\":\"成员管理\"},\"children\":[{\"data\":{\"id\":\"ayvwqehrrj4k\",\"created\":1443767128576,\"text\":\"编辑组内成员名单\"},\"children\":[]},{\"data\":{\"id\":\"ayvwqgu3z8s8\",\"created\":1443767133676,\"text\":\"查看组内成员工作状态\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwgpz17rc4\",\"created\":1443766369923,\"text\":\"任务管理\"},\"children\":[{\"data\":{\"id\":\"ayvwgs1t168s\",\"created\":1443766374444,\"text\":\"分配任务\"},\"children\":[{\"data\":{\"id\":\"ayvwmfqlv0cg\",\"created\":1443766817830,\"text\":\"最好支持图文\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwgtuo4c4c\",\"created\":1443766378366,\"text\":\"查看任务处理情况\"},\"children\":[]}]}]},{\"data\":{\"id\":\"ayvwevz2ebk0\",\"created\":1443766226257,\"text\":\"项目成员\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"ayvwhlq6c084\",\"created\":1443766439044,\"text\":\"处理任务\"},\"children\":[{\"data\":{\"id\":\"ayvwkb9ovv48\",\"created\":1443766651372,\"text\":\"任务到期提醒\"},\"children\":[]},{\"data\":{\"id\":\"ayvwq86qew44\",\"created\":1443767114848,\"text\":\"自建新任务\"},\"children\":[{\"data\":{\"id\":\"ayvwqb7dem0w\",\"created\":1443767121417,\"text\":\"子任务\"},\"children\":[]}]}]},{\"data\":{\"id\":\"ayvwhvb4uqwo\",\"created\":1443766459902,\"text\":\"团队协作\"},\"children\":[{\"data\":{\"id\":\"ayvwkicr4gwk\",\"created\":1443766666795,\"text\":\"文档、表单协作编辑\"},\"children\":[{\"data\":{\"id\":\"ayvwm2qj2uww\",\"created\":1443766789527,\"text\":\"同时编辑\"},\"children\":[]},{\"data\":{\"id\":\"ayvwm6wz168s\",\"created\":1443766798624,\"text\":\"PDF标注\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwkmcumzcc\",\"created\":1443766675508,\"text\":\"文件共享\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwi152k2gc\",\"created\":1443766472596,\"text\":\"版本管理\"},\"children\":[{\"data\":{\"id\":\"ayvwkr9cwcw8\",\"created\":1443766686180,\"text\":\"同一文件多版本管理\"},\"children\":[]},{\"data\":{\"id\":\"ayvwt3wna4w8\",\"created\":1443767340623,\"text\":\"工作产出上传与沟通\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwmlqg1qo8\",\"created\":1443766830881,\"text\":\"工作总结\"},\"children\":[{\"data\":{\"id\":\"ayvwmn10c6ww\",\"created\":1443766833697,\"text\":\"每日工作总结的提交\"},\"children\":[{\"data\":{\"id\":\"ayvwmqjhzkg8\",\"created\":1443766841345,\"text\":\"任务一览\"},\"children\":[]},{\"data\":{\"id\":\"ayvwn049o4gg\",\"created\":1443766862192,\"text\":\"工作量统计\"},\"children\":[]},{\"data\":{\"id\":\"ayvwmw8yucgg\",\"created\":1443766853769,\"text\":\"一句话总结\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"ayvwr97re6g4\",\"created\":1443767195451,\"text\":\"涉及到的沟通平台\"},\"children\":[{\"data\":{\"id\":\"ayvwrfx3e4w8\",\"created\":1443767210043,\"text\":\"综合协作平台\"},\"children\":[{\"data\":{\"id\":\"ayvwzehw7fcc\",\"created\":1443767833861,\"text\":\"https://glip.com/\"},\"children\":[]},{\"data\":{\"id\":\"ayvwzfuj1kc8\",\"created\":1443767836802,\"text\":\"https://www.teambition.com/tour\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwriay94sk\",\"created\":1443767215235,\"text\":\"设计图沟通\"},\"children\":[{\"data\":{\"id\":\"ayvwzyvfjfkk\",\"created\":1443767878215,\"text\":\"http://designboard.cc/\"},\"children\":[]},{\"data\":{\"id\":\"ayvx002p30ko\",\"created\":1443767880831,\"text\":\"https://bearyboard.com\"},\"children\":[]},{\"data\":{\"id\":\"ayvx2f0ywq0o\",\"created\":1443768070107,\"text\":\"http://www.invisionapp.com/\"},\"children\":[]}]},{\"data\":{\"id\":\"ayvwrmvrr84w\",\"created\":1443767225201,\"text\":\" 团队实时沟通\"},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.21\"}","fileGuid":"95bf573a3b5266828b0f00cd973bc5d9"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

**Comment by zhangbobell** [comment]
我们已经知晓，并在解决，将在最近的更新中修复，不会影响用户的数据，见 #104
