### ISSUE TITLE
复制到备注里就会产生一个下级，而不是出现在备注里

### ISSUE THREAD

**Issue by xiaoshuaiyang** [fex-team/kityminder-editor#116]
复制到备注里就会产生一个下级，而不是出现在备注里

**Comment by zhangbobell** [comment]
这个问题我们已经解决，将在下个更新修复，详见 issue #102，暂时你可以通过粘贴到地址栏，然后全选后拖拽到备注框内，或者让当前节点处于编辑状态，直接粘贴即可。

**Comment by xiaoshuaiyang** [comment]
问一下什么时间更新。脑图是常用工具，现在使用非常不方便

**Comment by zhangbobell** [comment]
最快本周吧。
