### ISSUE TITLE
变更节点级次的时候，子节点被逆序了

### ISSUE THREAD

**Issue by HunterGX** [fex-team/kityminder-editor#118]
示例：
a-a1
  -a2-a3-a31
             -a32
             -a33
当将a3改为a的子节点时，a3的子节点顺序被逆序了，如下：
a-a1
  -a2
  -a3-a33
       -a32
       -a31

**Comment by zhangbobell** [comment]
你好，你所提供的信息无法判断父子节点关系，能否提供截图，或者是采用导出节点粘贴到这里，让我们能进一步判断？issue #119 同样缺乏这方面信息。

**Comment by HunterGX** [comment]
原图：
1、#119 
      同时选中a31,a32，a33复制,在a1上粘贴
    预期效果
    
    
    实际效果
    
2、#118
    将a3变更为a的节点
       没有重现了，，，，





miss_cn@163.com
 
发件人： Bo Zhang
发送时间： 2015-10-14 17:11
收件人： fex-team/kityminder-editor
抄送： HunterGX
主题： Re: [kityminder-editor] 变更节点级次的时候，子节点被逆序了 (#118)
你好，你所提供的信息无法判断父子节点关系，能否提供截图，或者是采用导出节点粘贴到这里，让我们能进一步判断？issue #119 同样缺乏这方面信息。

**Comment by zhangbobell** [comment]
看不到截图啊。
