### ISSUE TITLE
复制同层级多个节点时的bug

### ISSUE THREAD

**Issue by HunterGX** [fex-team/kityminder-editor#119]
示例：
0-a
  -b-b1
     -b2
欲将b1,b2复制为a的子节点，预期效果：
0-a-b1
     -b2
    -b
实际效果：
0-a-b2
   -b

**Comment by HunterGX** [comment]
示例，一共三级，复制同一个二级下的两个并列的三级子节点，粘贴到其他任意接点上时，只有一个子节点被粘贴了，另外一个丢失了

**Comment by zhangbobell** [comment]
问题已经修复，详情见 https://github.com/fex-team/kityminder-core/commit/bc2fc1b5a45789dafacacd2862eaf66c00cc949a
