### ISSUE TITLE
反馈：关于复制粘贴文字的问题

### ISSUE THREAD

**Issue by TryLoveCatch** [fex-team/kityminder-editor#123]
从其他地方复制文字，想粘贴到备注里面，每次都是新建了一个节点，这个不合理啊，没法复制了，只能手动输入

**Comment by zhangbobell** [comment]
感谢你的反馈，这个问题我们已经知晓并解决，将在下个更新修复，暂时你可以复制到浏览器地址栏，然后全选拖拽到链接输入框。或者让节点进入编辑状态，即可正常粘贴。详见 #102
