### ISSUE TITLE
粘贴却产生下级主题（Google Chrome）

### ISSUE THREAD

**Issue by ohmydengzi** [fex-team/kityminder-editor#124]
前提：
Google Chrome（版本 43.0.2357.134 m）
重现：
1、复制一些文字，选中主题，Ctrl+v
2、选中主题-备注-插入备注，在备注中Ctrl+v
实际输出：
上面两种情况都会产生下级主题，只要是选中状态下，Ctrl+v都会这样

备注：之前一直在找适合的思维导图编辑器，当发现百度脑图的时候，眼前一亮。功能和我想的差不多，而且界面也不错。加油改bug！

**Comment by zhangbobell** [comment]
感谢你的反馈，这个问题我们已经知晓并解决，将在下个更新修复，暂时你可以复制到浏览器地址栏，然后全选拖拽到链接输入框。或者让节点进入编辑状态，即可正常粘贴。详见 #102
