### ISSUE TITLE
使用发现的问题和建议

### ISSUE THREAD

**Issue by tall49er** [fex-team/kityminder-editor#126]
今天刚开始使用，然后有一些问题
1.输入一个主题按回车，刚输入的内容会有重复的两份。输入 abc  变成   abcabc
2.会乱跳，会跳到其他地方，刚才输入的地方也没有了。

建议
1.图片大小修改，插入的图片特别小，看不清。
2.添加表格。
3.支持插入本地图片

**Comment by zhangbobell** [comment]
你说的第一个问题已经被 @Naixor 修复了，见 [commit d1d2b004](https://github.com/fex-team/kityminder-editor/commit/d1d2b004f42279ffe5fcb8f183f8246f7ec253fe)

**Comment by zhangbobell** [comment]
第二个问题能不能提供更一个稳定的复现步骤？

**Comment by zhangbobell** [comment]
你的建议我们在未来的开发中会考虑的，插入本地图片的功能一定会加上，还有对图片的大小的调节功能。

**Comment by NerdyCybory** [comment]
但是今天用firefox还是有这种现象，难道是我的浏览器版本太老，你们说chrome体验最好，所以是不是喝浏览器也有关系。

发送自 Outlook




On Sun, Oct 18, 2015 at 2:56 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
你说的第一个问题已经被 @Naixor 修复了，见 [commit d1d2b004](https://github.com/fex-team/kityminder-editor/commit/d1d2b004f42279ffe5fcb8f183f8246f7ec253fe)

---

**Comment by NerdyCybory** [comment]
好的好的，谢谢这么认真的回复

发送自 Outlook




On Sun, Oct 18, 2015 at 2:57 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
你的建议我们在未来的开发中会考虑的，插入本地图片的功能一定会加上，还有对图片的大小的调节功能。

---

**Comment by NerdyCybory** [comment]
这不好说，按tab第一次编辑一般没问题，在节点切换之后再按f2编辑，速度快的时候会出现。

发送自 Outlook




On Sun, Oct 18, 2015 at 2:59 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
第二个问题能不能提供更一个稳定的复现步骤？

---

**Comment by NerdyCybory** [comment]
猜测是不是在同步的时候容易出现一些

发送自 Outlook




On Sun, Oct 18, 2015 at 2:59 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
第二个问题能不能提供更一个稳定的复现步骤？

---

**Comment by NerdyCybory** [comment]
发送自 Outlook




On Sun, Oct 18, 2015 at 3:02 AM -0700, "rui tang" <talltangrui@outlook.com> wrote:
猜测是不是在同步的时候容易出现一些

发送自 Outlook




On Sun, Oct 18, 2015 at 2:59 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
第二个问题能不能提供更一个稳定的复现步骤？

---

**Comment by zhangbobell** [comment]
第一个问题已经解决，但是要能用上的话，需要等待下次更新。

**Comment by NerdyCybory** [comment]
好的好的，周末加班辛苦了

发送自 Outlook




On Sun, Oct 18, 2015 at 7:36 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
第一个问题已经解决，但是要能用上的话，需要等待下次更新。

---
