### ISSUE TITLE
备注不能粘贴链接呀！

### ISSUE THREAD

**Issue by yisuoyanyu111** [fex-team/kityminder-editor#131]
__备注粘贴链接默认怎家子节点了！__

**Comment by zhangbobell** [comment]
感谢你的反馈，这个问题我们已经知晓并解决，将在下个更新修复，暂时你可以复制到浏览器地址栏，然后全选拖拽到链接输入框。或者让节点进入编辑状态，即可正常粘贴。详见 #102
