### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by tall49er** [fex-team/kityminder-editor#133]
为什么节点每行开头不能有空格，记代码没有缩进很难看啊。

**Comment by techird** [comment]
有意思，故意去试了一下，带空格的行会变成新节点。需要看一下，应该是和导入文本功能冲突了。

**Comment by tall49er** [comment]
我能参与到这个项目的开发吗，我看是开源的。

发送自 Outlook




On Tue, Oct 20, 2015 at 12:44 AM -0700, "Together we can fly!" <notifications@github.com> wrote:
有意思，故意去试了一下，带空格的行会变成新节点。需要看一下，应该是和导入文本功能冲突了。

---

**Comment by Naixor** [comment]
一个空格会新建节点这个，逻辑上只有在IE系列下包含edge才会啊，IE下输入的TAB会被转义成空格处理，不得已而为之，其他浏览器是一个tab或者四个空格就会算一个tab按照导入节点处理

**Comment by tall49er** [comment]
你确定，我用firefox

发送自 Outlook




On Tue, Oct 20, 2015 at 12:54 AM -0700, "Stormspirit" <notifications@github.com> wrote:
一个空格会新建节点这个，逻辑上只有在IE系列下包含edge才会啊，IE下输入的TAB会被转义成空格处理，不得已而为之，其他浏览器是一个tab或者四个空格就会算一个tab按照导入节点处理

---

**Comment by Naixor** [comment]
必须确定啊，除非你输入了四个空格 - -，不是四个空格不会按照TAB去处理导入的，难道有其他逻辑BUG？

**Comment by Naixor** [comment]
我刚试了下，我这里的Win和Mac的FF都是一行前面输入1个空格（总之别是四个）没出现这个BUG - -

**Comment by tall49er** [comment]
是这样的，我按tab没反应，所以按了4个空格

发送自 Outlook




On Tue, Oct 20, 2015 at 12:58 AM -0700, "Stormspirit" <notifications@github.com> wrote:
必须确定啊，除非你输入了四个空格 - -，不是四个空格不会按照TAB去处理导入的，难道有其他逻辑BUG？

---

**Comment by tall49er** [comment]
FF是什么😅

发送自 Outlook




On Tue, Oct 20, 2015 at 1:00 AM -0700, "Stormspirit" <notifications@github.com> wrote:
我刚试了下，我这里的Win和Mac的FF都是一行前面输入1个空格（总之别是四个）没出现这个BUG - -

---

**Comment by techird** [comment]
@tall49er FireFox

**Comment by Naixor** [comment]
这里其实是有个使用上的冲突的，因为当你进入编辑模式下，从外部直接粘贴带有TAB或者四个空格的文本，我们会对他转换节点处理，这意味着你进入编辑模式下自行输入的内容，我没事无法得知它到底是外部粘贴进来的，还是你输入的 - -，因此全部都得做节点转换处理，发现无法转换，则当做文本输入进去。因此你的这个BUG，相当于可以归纳成为支持在编辑模式下输入TAB就行了吧 - -

**Comment by Naixor** [comment]
@techird 好久不见~

**Comment by tall49er** [comment]
为什么会有腾讯的工程师

发送自 Outlook




On Tue, Oct 20, 2015 at 1:06 AM -0700, "Stormspirit" <notifications@github.com> wrote:
@techird 好久不见~

---

**Comment by tall49er** [comment]
啊，是吧

发送自 Outlook




On Tue, Oct 20, 2015 at 1:07 AM -0700, "Stormspirit" <notifications@github.com> wrote:
这里其实是有个使用上的冲突的，因为当你进入编辑模式下，从外部直接粘贴带有TAB或者四个空格的文本，我们会对他转换节点处理，这意味着你进入编辑模式下自行输入的内容，我没事无法得知它到底是外部粘贴进来的，还是你输入的 - -，因此全部都得做节点转换处理，发现无法转换，则当做文本输入进去。因此你的这个BUG，相当于可以归纳成为支持在编辑模式下输入TAB就行了吧 - -

---

**Comment by Naixor** [comment]
@tall49er ...脑图最开始就是@techird 在百度时编写的好不好 - -

**Comment by tall49er** [comment]
什么，怎么了

发送自 Outlook




On Tue, Oct 20, 2015 at 1:08 AM -0700, "Together we can fly!" <notifications@github.com> wrote:
@tall49er FireFox

---

**Comment by techird** [comment]
@tall49er 开源项目无国界，大家都可以维护的

**Comment by tall49er** [comment]
这样啊

发送自 Outlook




On Tue, Oct 20, 2015 at 1:09 AM -0700, "Stormspirit" <notifications@github.com> wrote:
@tall49er ...脑图最开始就是@techird 在百度时编写的好不好 - -

---

**Comment by tall49er** [comment]
我能加入开发吗，从哪里做起啊，还是你们给我一个小功能写一些

发送自 Outlook




On Tue, Oct 20, 2015 at 1:09 AM -0700, "Stormspirit" <notifications@github.com> wrote:
@tall49er ...脑图最开始就是@techird 在百度时编写的好不好 - -

---

**Comment by zhangbobell** [comment]
@tall49er 可以的啊，你可以向我们直接提 pull request，之前已经有人提过，之前的版本的「天盘图」模板就是 pull request 过来的。

**Comment by tall49er** [comment]
看了一下readme ， 我这个刚大二的好多都不知道～～

发送自 Outlook




On Tue, Oct 20, 2015 at 1:12 AM -0700, "Together we can fly!" <notifications@github.com> wrote:
@tall49er 开源项目无国界，大家都可以维护的

---

**Comment by zhangbobell** [comment]
没事，慢慢学，都是从不懂开始的。

**Comment by tall49er** [comment]
从哪里上手哪，我连javascript都没看过，～～刚学完谭浩强老师的cpp，在自学java，python 之类的

发送自 Outlook




On Tue, Oct 20, 2015 at 1:18 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
没事，慢慢学，都是从不懂开始的。

---

**Comment by Naixor** [comment]
@tall49er 比如你刚提的这个问题解决了吧 - -，在contenteditable div里面支持输入TAB - -

**Comment by tall49er** [comment]
天盘图 是什么 ，在网图里没见过，百度也搜不到～～

发送自 Outlook




On Tue, Oct 20, 2015 at 1:21 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
@tall49er 可以的啊，你可以向我们直接提 pull request，之前已经有人提过，之前的版本的「天盘图」模板就是 pull request 过来的。

---

**Comment by tall49er** [comment]
真的tab没反应

发送自 Outlook




On Tue, Oct 20, 2015 at 1:25 AM -0700, "Stormspirit" <notifications@github.com> wrote:
@tall49er 比如你刚提的这个问题解决了吧 - -，在contenteditable div里面支持输入TAB - -

---

**Comment by zhangbobell** [comment]
天盘图在新版的脑图还没有整合上去，下个更新就会加上，旧版的有。如果对 js 感兴趣可以找本经典的书籍，慢慢开始读，然后边看边做。

**Comment by tall49er** [comment]
好的好的，

发送自 Outlook




On Tue, Oct 20, 2015 at 1:33 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
天盘图在新版的脑图还没有整合上去，下个更新就会加上，旧版的有。如果对 js 感兴趣可以找本经典的书籍，慢慢开始读，然后边看边做。

---

**Comment by tall49er** [comment]
现在it 互联网真的不景气吗，居然停招了

发送自 Outlook




On Tue, Oct 20, 2015 at 1:37 AM -0700, "rui tang" <talltangrui@outlook.com> wrote:
好的好的，

发送自 Outlook




On Tue, Oct 20, 2015 at 1:33 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
天盘图在新版的脑图还没有整合上去，下个更新就会加上，旧版的有。如果对 js 感兴趣可以找本经典的书籍，慢慢开始读，然后边看边做。

---

**Comment by zhangbobell** [comment]
百度的社招暂时停了，但是今年的校招没有停啊。
