### ISSUE TITLE
配置环境有一点问题

### ISSUE THREAD

**Issue by tall49er** [fex-team/kityminder-editor#135]
![Uploading 2015-10-21 17:36:28屏幕截图.png…]()

npm run init 的时候为什么会有这么多err ， 是环境没有配置成功吗，我用的是Ubuntu，帮我看一下好了，谢谢。

**Comment by tall49er** [comment]
![2015-10-21 17 36 28](https://cloud.githubusercontent.com/assets/14860802/10636131/023ebe94-7830-11e5-83f2-20ed7dae664b.png)

**Comment by zhangbobell** [comment]
使用超级用户权限 sudo 执行命令。

**Comment by tall49er** [comment]
奥，好的好的

发送自 Outlook




On Thu, Oct 22, 2015 at 8:54 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
使用超级用户权限 sudo 执行命令。

---

**Comment by tall49er** [comment]
切换到root账号也可以吧

发送自 Outlook




On Thu, Oct 22, 2015 at 8:54 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
使用超级用户权限 sudo 执行命令。

---

**Comment by tall49er** [comment]
能请教一个问题吗，你觉得本科应该专注于学习基础像  数据结构算法，操作系统编译原理 。还是多关注一些前沿的东西。

发送自 Outlook




On Thu, Oct 22, 2015 at 8:54 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
使用超级用户权限 sudo 执行命令。

---

**Comment by zhangbobell** [comment]
更多的关注底层原理吧，热门的东西总有一天会过时，留在书本上的是经过时间洗礼留下来的。

**Comment by tall49er** [comment]
好的好的，谢谢

发送自 Outlook




On Sat, Oct 24, 2015 at 9:08 AM -0700, "Bo Zhang" <notifications@github.com> wrote:
更多的关注底层原理吧，热门的东西总有一天会过时，留在书本上的是经过时间洗礼留下来的。

---
