### ISSUE TITLE
异常反馈,谢谢

### ISSUE THREAD

**Issue by kitho1** [fex-team/kityminder-editor#136]
错误
 http://naotu.baidu.com/public/dist/kityminder.online.min.js?_=d4421268a452ef9f
行号：41
错误信息：Uncaught TypeError: d.moreService is not a function
列号：491
错误对象：TypeError: d.moreService is not a function

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by zhangbobell** [comment]
请问能否提供下这个问题的复现步骤？以便我们进一步定位问题。

**Comment by kitho1** [comment]
通过Google Chrome (Version 46.0.2490.80 m)浏览器 从naotu.baidu.com/home点击了文件名跳转到http://naotu.baidu.com/file/***时出现的,只出现过一次.
------------------------------------------------------------------------------
[反馈]打开思路图时,图的初始位置很多时候在左上角,有时会在中间

**Comment by zhangbobell** [comment]
可能复现不太稳定，我们这边没有出现。你的另一个反馈的问题也已经解决，将在下个更新修复。
