### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by stonewl897** [fex-team/kityminder-editor#137]
当输入的内容比较长，保存再打开后。内容下面的横线太短，导致文字看不清楚。

**Comment by Naixor** [comment]
感谢反馈，我刚试了下，没太明白是什么意思，可否截个图呢?
这是我试的，也算超过屏幕宽度的长度了：
![86791734-ca87-47e9-88cf-27cd928014f1](https://cloud.githubusercontent.com/assets/5070106/10655184/d7961690-78a4-11e5-9798-036291d4a86f.png)
ps:其实你可以用软换行啊，shift + enter，会好看不少的
