### ISSUE TITLE
关于展开只能展开到6级节点

### ISSUE THREAD

**Issue by zm03322161** [fex-team/kityminder-editor#140]
现在只能展开到六级节点，我的脑图超过这个数量，展开挺不方便的。希望官方给出更多级或者可以全展开。
或者手动输入节点数。

**Comment by Naixor** [comment]
希望能描述一下不方便的地方，类似体验问题，只有了解到哪里会导致不方便，才好改进

**Comment by zm03322161** [comment]
如图。。非常感谢你们的回复。
![undefined](https://cloud.githubusercontent.com/assets/3784198/10725879/4ada82d6-7c0a-11e5-93c7-423c0b94a747.png)
![1](https://cloud.githubusercontent.com/assets/3784198/10725880/4afeec34-7c0a-11e5-8a39-4179c20656f8.png)

**Comment by zm03322161** [comment]
那个，这个放着我来试试完善。

**Comment by techird** [comment]
@zm03322161 其实思维导图不建议有太深的层级，如果你做的导图太深，可以考虑下合并、归纳、抽象了。

**Comment by zhangbobell** [comment]
这个问题也已经解决了，下个版本按下「展开」按钮就可以展开全部节点了。

**Comment by zm03322161** [comment]
@techird 不建议只是一种个人使用习惯，其实我已经压缩很多了，都扔到备注里了。我觉得功能上还是应该可以全展开的。如果抽象归纳的太多，一些node就会模糊不清，不够精确。

@zhangbobell 作者你效率要不要这么快，我还想着试试能不能做点贡献呢。。哈哈

非常赞的应用。加油~~

**Comment by techird** [comment]
@zm03322161 这个只是脑图书写的一些建议，特殊情况有特殊用法。软件还是有能力支持的。

**Comment by zhangbobell** [comment]
@MarsZone 哈哈，因为正如 @techird 所说，这个改起来很简单。

**Comment by MarsZone** [comment]
@zhangbobell 等下，我觉得那个123456级节点展开的功能其实还是有必要保留的。在此之上加入一个全部展开~

**Comment by zhangbobell** [comment]
@MarsZone 是的，我就是这么改的啊。
