### ISSUE TITLE
百度脑图打开失败

### ISSUE THREAD

**Issue by guorui22** [fex-team/kityminder-editor#142]
错误
 503: 读取文件失败

浏览器信息：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by zhangbobell** [comment]
你好，有没有用户名和文件 id，我们看一下。

**Comment by guorui22** [comment]
我通过恢复历史版本，现在可以打开了。谢谢。
