### ISSUE TITLE
分享脑图报错

### ISSUE THREAD

**Issue by liminjun** [fex-team/kityminder-editor#143]
![image](https://cloud.githubusercontent.com/assets/966009/10750457/c37e843e-7cb0-11e5-88eb-7cf55d402a5a.png)

**Comment by zhangbobell** [comment]
有没有出错信息？有没有文件的 id ?

**Comment by zhangbobell** [comment]
检查一下你的网址后面是不是带着其他的字符，比如汉字什么的。

**Comment by zhangbobell** [comment]
这个问题已经在 11 月 3 日发布的版本中修复，见 http://naotu.baidu.com/user/changelog。
