### ISSUE TITLE
如果向节点中粘贴从网页中复制来的带有格式的文字，则显示为空

### ISSUE THREAD

**Issue by freechen** [fex-team/kityminder-editor#144]
我从一个网页中复制了加粗的字，向节点中粘贴时显示为空，如果把这字先放到txt文件中，再复制粘贴过来就会显示。

![image](https://cloud.githubusercontent.com/assets/5688949/10780213/0a0c537a-7d76-11e5-97e5-8f6f5c47cc37.jpg)

![image](https://cloud.githubusercontent.com/assets/5688949/10776847/5db82588-7d50-11e5-87d1-c1bdcd5dbf25.png)

**Comment by Naixor** [comment]
这个问题已修复，新版本将会处理这些带有格式的文字的~

**Comment by zhangbobell** [comment]
@freechen 这个问题已有 @Naixor 从 commit d1d2b004f42279ffe5fcb8f183f8246f7ec253fe 修复，点击可以查看详情。
