### ISSUE TITLE
Ubuntu 15.04 + Freemind 0.9.0 打不开导出的 mm 文件

### ISSUE THREAD

**Issue by yangyanqing** [fex-team/kityminder-editor#149]
baidu脑图导出的 mm 文件第一行为 <map version="1.0.1">
打开后报错，修改为 <map version="0.9.0"> 后可正常打开

**Comment by zhangbobell** [comment]
「第一行为」是什么意思？能否提供更进一步的信息？

**Comment by yangyanqing** [comment]
文本打开的导出的 MM 文件，第一行“map version="1.0.1"”，
原始记录应该是带尖括号给转义没了，这次把尖括号去掉了

**Comment by yangyanqing** [comment]
修改为 0.9 后正常打开，可能是我的客户端版本太低了吧
