### ISSUE TITLE
ctrl+z  撤销的问题蛮大

### ISSUE THREAD

**Issue by luobeng** [fex-team/kityminder-editor#150]
经常ctrl+z   不会是撤销，反而会打乱前面已经存在的成果

这个bug  蛮影响使用

**Comment by zhangbobell** [comment]
有没有进一步的反馈信息？举个例子也行啊。

**Comment by luobeng** [comment]
大概有下列聊天中出现的这种现象
---

我这里经常ctrl+z有问题，现在还不太能准确复现
罗兴峰(xf.luo)  23:14:59
偶尔也是 ctrl+z以后 出来几个粘贴板中的内容
少了一味药  23:15:45
对，这个我也发现了。而且还发现一个BUG，有的时候来回切换页面（Alt+Tab）粘贴，本来改好的节点文本时常出现历史粘贴板的内容
[image: 内嵌图片 1]

2015-11-01 17:31 GMT+08:00 Bo Zhang <notifications@github.com>:

> 有没有进一步的反馈信息？举个例子也行啊。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fex-team/kityminder-editor/issues/150#issuecomment-152811666>
> .
>



-- 

罗兴峰  运维总监
-----------------------------------------------

地址：上海市徐汇区天钥桥路1000号徐汇苑商务楼5楼  ( 200030 )
网址：www.shuyun.com
手机：133 2180 0965
邮箱：xf.luo@shuyun.com

**Comment by luobeng** [comment]
issue 102 已修复
可关闭
