### ISSUE TITLE
工具栏显示不全

### ISSUE THREAD

**Issue by simcyber** [fex-team/kityminder-editor#153]
![image](https://cloud.githubusercontent.com/assets/5127586/10931413/23d14496-8302-11e5-9c28-3a8a73091cb3.png)

您好，工具栏如何调整高度，默认的好像显示不全，下面挡住点了

**Comment by zhangbobell** [comment]
你的浏览器是否处于放大状态， `ctrl + 0` 恢复即可。

**Comment by simcyber** [comment]
果然是这个问题，谢谢！
