### ISSUE TITLE
[Google Chrome] ctrl+s保存，主题被清空

### ISSUE THREAD

**Issue by ohmydengzi** [fex-team/kityminder-editor#160]
谷歌浏览器。
选中主题节点，ctrl+s保存，点开鼠标，主题名字就会被清空。

**Comment by zhangbobell** [comment]
你需要先抬起 S 再抬起 ctrl，这个问题我们将在下个版本修复。

**Comment by zhangbobell** [comment]
出现这种情况，暂时可以使用 esc 键退出编辑解决。

**Comment by zhangbobell** [comment]
这个问题已经在 [v1.4.26](http://naotu.baidu.com/user/changelog) 上得到解决。
