### ISSUE TITLE
Save 操作引起 status -1 的错误

### ISSUE THREAD

**Issue by tangfei67** [fex-team/kityminder-editor#162]
错误
 {"data":null,"status":-1,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"1b2d7c29a618\",\"created\":1448163286,\"text\":\"企业级服务公司\"},\"children\":[{\"data\":{\"id\":\"b0372g5wsdmo\",\"created\":1448163361818,\"text\":\"数据分析\",\"expandState\":\"expand\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b037vv1sv7k0\",\"created\":1448165666782,\"text\":\"Mixpanel\\n监测用户行为\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039sj6uz5kw\",\"created\":1448171048094,\"text\":\"Interana\\n企业客户数据管理\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039tq10gow0\",\"created\":1448171141342,\"text\":\"HasMetrics\\n云端用户体验管理\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039v1cvetxc\",\"created\":1448171244368,\"text\":\"Tidemark\\n基于云的数据分析平台\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039wk49yi9s\",\"created\":1448171363571,\"text\":\"Qualtrics\\n网上调查\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b03a2zhdderk\",\"created\":1448171867200,\"text\":\"DataGravity\\n数据情报收集\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b0372iaipk3k\",\"created\":1448163366450,\"text\":\"企业办公\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b037zn10tczk\",\"created\":1448165962777,\"text\":\"Slack\\n企业级通讯工具\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b0380pc59l34\",\"created\":1448166046168,\"text\":\"Zenefits\\n保险和人力资源软件领域\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039qq10etxc\",\"created\":1448170906249,\"text\":\"Huddle\\n企业协同和内容管理\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039vzxxkxs0\",\"created\":1448171319652,\"text\":\"Anaplan\\n企业销售、运营及财务建模与规划\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b03a0t0do2dc\",\"created\":1448171696383,\"text\":\"SkyHigh Networks\\n监控云服务公司\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b0372jnwbb40\",\"created\":1448163369436,\"text\":\"企业安全\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b039unppn5kw\",\"created\":1448171214669,\"text\":\"Illumio\\n云安全服务商\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b03a29kvrif4\",\"created\":1448171810816,\"text\":\"OpenDNS\\nDNS 安全 已被思科收购\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b037q2qvoohs\",\"created\":1448165213351,\"text\":\"物联网\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b037qctr8ef4\",\"created\":1448165235293,\"text\":\"Jasper\\n为物联网科技提供云服务\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b037rivbu0hs\",\"created\":1448165326813,\"text\":\"在线教育\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b037rtmcnnr4\",\"created\":1448165350214,\"text\":\"Lynda.com\\n已被LinkedIn收购\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b037td7to3r4\",\"created\":1448165471236,\"text\":\"移动开发\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b037tqwvoidc\",\"created\":1448165501049,\"text\":\"Xamarin\\n跨平台的应用开发\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b038140bke0w\",\"created\":1448166078104,\"text\":\"云服务\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b0383nwul9fk\",\"created\":1448166278158,\"text\":\"Couchbase\\nNoSQL 数据存储\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039pf4mtou8\",\"created\":1448170804160,\"text\":\"Nutanix\\n数据中心(服务器、存储和网络融合)\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039xifytkw0\",\"created\":1448171438289,\"text\":\"Pluribus\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039zkpd0npc\",\"created\":1448171599939,\"text\":\"Interana\\n网站性能和安全\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b03a1mzi181s\",\"created\":1448171761634,\"text\":\"Centrify\\n身份管理\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"b039o09tpq80\",\"created\":1448170693458,\"text\":\"应用构建部署\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"b039obkdo6ps\",\"created\":1448170718040,\"text\":\"Docker\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039ohtk0qo0\",\"created\":1448170731656,\"text\":\"CoreOS\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039yo7sak8w\",\"created\":1448171529219,\"text\":\"Puppet Labs\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"b039z3mqp5hc\",\"created\":1448171562775,\"text\":\"Chef\",\"layout\":null},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue-compat\",\"version\":\"1.4.24\"}","fileGuid":"2a8ba92b45bbc9cc17712f6e444c9a23"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":""}

浏览器信息：Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by zhangbobell** [comment]
这个问题我们已经知晓并正在解决，谢谢。

**Comment by tangfei67** [comment]
加油！

**Comment by Naixor** [comment]
-1问题是断网导致 - -，你可以放心这不会对你的脑图产生很大影响~
