### ISSUE TITLE
脑图出错: 500

### ISSUE THREAD

**Issue by maolion** [fex-team/kityminder-editor#166]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>A Database Error Occurred</h1>\n\t\t<p>Unable to connect to your database server using the provided settings.</p><p>Filename: core/Loader.php</p><p>Line Number: 346</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"a52a3c287455\",\"created\":1449195951,\"text\":\"白板程序 \"},\"children\":[{\"data\":{\"id\":\"b0dd4ix0du04\",\"created\":1449196050765,\"text\":\"客户端\\n----------\\n一个基于 WEB 浏览器结构的跨平台\\n应用程序框架\"},\"children\":[{\"data\":{\"id\":\"b0dd5963au0c\",\"created\":1449196107910,\"text\":\"请示单元\\n----------\\n客户端发送网络请求向服务器调用资源库和解析单元\"},\"children\":[]},{\"data\":{\"id\":\"b0dd5c67nf48\",\"created\":1449196114448,\"text\":\"显示单元\"},\"children\":[]},{\"data\":{\"id\":\"b0ddhy16x08c\",\"created\":1449197102403,\"text\":\"音频录制单元\"},\"children\":[]},{\"data\":{\"id\":\"b0ddi8mslckw\",\"created\":1449197125477,\"text\":\"画板单元\"},\"children\":[]},{\"data\":{\"id\":\"b0ddm9jdpgoo\",\"created\":1449197440904,\"text\":\"音视频播放单元\"},\"children\":[]},{\"data\":{\"id\":\"b0ddij5b2i0o\",\"created\":1449197148365,\"text\":\"数据发出/接收通断单元\"},\"children\":[]},{\"data\":{\"id\":\"b0ddj5q5wcg0\",\"created\":1449197197515,\"text\":\"录像播放单元\"},\"children\":[]}]},{\"data\":{\"id\":\"b0dd4u9k1gc0\",\"created\":1449196075468,\"text\":\"服务器端\"},\"children\":[{\"data\":{\"id\":\"b0dd5xanaw0g\",\"created\":1449196160428,\"text\":\"资源库\"},\"children\":[]},{\"data\":{\"id\":\"b0dd64e7kaw4\",\"created\":1449196175881,\"text\":\"解析单元\"},\"children\":[]},{\"data\":{\"id\":\"b0dd6a4bok08\",\"created\":1449196188344,\"text\":\"调用单元\"},\"children\":[]},{\"data\":{\"id\":\"b0dd6ggst28k\",\"created\":1449196202159,\"text\":\"发送单元\"},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.24\"}","fileGuid":"9d0b5c4d9d964e90113b56a1e50bf544"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

**Comment by yinheli** [comment]
常有这个错误, 数据库层面的问题....  看来这个项目还没有受到足够重视, 配备资源还不足啊.

**Comment by zhangbobell** [comment]
这个问题是由于后端压力过大造成的，现已修复，对文件没有任何影响，感谢反馈！
