### ISSUE TITLE
错误提示，用的360极速浏览器，打开”分享给我的文件“时出错

### ISSUE THREAD

**Issue by czhwu** [fex-team/kityminder-editor#167]
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/ls_share_me","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于后端压力过大造成的，现已修复，对文件没有任何影响，感谢反馈！
