### ISSUE TITLE
有没有计划添加对Latex数学公式的支持？

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [fex-team/kityminder-editor#169]
很早以前我就希望脑图类应用里面能显示数学公式。
最好就是直接把Latex转显示为公式，千万不要像word那样鼠标点公式。
我不了解JS，似乎有一些工具可以做到显示Latex，比如Math Jax之类。

**Comment by zhangbobell** [comment]
之前我们已经开发过相关的库 [kityformula](http://gongshi.baidu.com)，而且也有用户提议过这个问题，详见 #17，这个建议我们会在未来的开发中认真考虑，感谢。

**Comment by zhangchen-qinyinghua** [comment]
@zhangbobell 
我注意到贡献者很少。
你们是否接受项目开发者以外的PR？

**Comment by zhangbobell** [comment]
我们非常欢迎提供 PR，原先的项目是 [kityminder](https://github.com/fex-team/kityminder)，项目经历了一次代码重构，因此之前的 PR 都没有在新的仓库里面。

**Comment by zhangchen-qinyinghua** [comment]
谢谢回应。

I'll close the issues.
