### ISSUE TITLE
分支焦点问题

### ISSUE THREAD

**Issue by miaogong** [fex-team/kityminder-editor#174]
焦点在某一个节点，这时，移动画面到其他的分支，点击展开按钮或关闭节点按钮（就是加减号），焦点会回到原先的节点上，而不是点击关闭或者展开按钮所在的节点。

如果画布比较大，就会出现反复回到原节点的问题。感觉不是很符合逻辑。

除非把焦点移动到需要展开的节点上，再展开。

**Comment by zhangbobell** [comment]
你说的是不是点击 +/- 的时候，焦点应该跳到 +/- 所在的节点？

**Comment by miaogong** [comment]
应该是这样的吧？以前版本我记得应该是这样处理的。

个人觉得也比较符合编辑的逻辑。

**Comment by zhangbobell** [comment]
感谢反馈，这个建议不错。

**Comment by zhangbobell** [comment]
问题已经由 fex-team/kityminder-core 的 commit e37a414b6045663613983f2f222202128535a00d 修复。
