### ISSUE TITLE
保存脑图失败, 请重试

### ISSUE THREAD

**Issue by yuu2lee4** [fex-team/kityminder-editor#179]
错误
 208: 保存脑图失败, 请重试

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.87 Safari/537.36 QQBrowser/9.2.5748.400

**Comment by zhangbobell** [comment]
这个问题我们已经知晓并正在解决，目前对文件不会有任何影响，感谢反馈。

**Comment by zhangbobell** [comment]
merged with #176
