### ISSUE TITLE
210: 创建脑图新版本失败, 请重试

### ISSUE THREAD

**Issue by yuu2lee4** [fex-team/kityminder-editor#182]
错误
 210: 创建脑图新版本失败, 请重试

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.87 Safari/537.36 QQBrowser/9.2.5748.400

**Comment by Naixor** [comment]
这还上脑图后端服务问题，感谢反馈，总的来说，就是数据库操作未成功，因此需要你重新操作一遍，我们后续会继续提高后端的处理能力，尽量减少这种错误的发生。感谢反馈~
