### ISSUE TITLE
提供从编辑页到列表页的直接返回按钮

### ISSUE THREAD

**Issue by shuibingxin** [fex-team/kityminder-editor#186]
从“我的文件”-》列表进去之后-》如何返回呢？重新进入登录页面？个人觉得“我的文件”这样一个类似主页的页面，应该有一个全局菜单可以进入才对。

**Comment by zhangbobell** [comment]
这个功能我们会在下个版本中具备。

**Comment by zhangbobell** [comment]
merged with #175
