### ISSUE TITLE
【all】节点导出导入（alt+v alt+c）的BUG

### ISSUE THREAD

**Issue by Naixor** [fex-team/kityminder-editor#194]
使用alt+c进行节点导出时有个问题，节点内部的\n到页面上的textarea上会被直接解析成为<br>，节点内容上需要一套单独对\n的转换，下面简述我的几个想法：
想法一：
+ 节点内的软换行会被解析成'\n'字符，长度为2
+ 若用户需求输入\n，则可使用'\\n'来代替
```JavaScript
/*
 * 对应|123|--|abc  |
 *                  |haha|
 */
123
    abc\nhaha

/*
 * 对应|123|--|abc\nhaha|
 */
123
    abc\\nhaha
```

第二个想法：
+ 导出的内容中，每个节点会被一个`[]`包含起来
```JavaScript
[123]
    [abc
    haha]
```
@zhangbobell 
希望其他用户可以一起贡献自己喜欢的体验方式

**Comment by miaogong** [comment]
强烈建议恢复到老版脑图的简单复制和粘贴功能！
现在的简单的分支之间的调整实在是太繁琐！

**Comment by Naixor** [comment]
复制粘贴一直就没变过，还请使用确定下。这只是针对非chrome无法跨脑图粘贴复制做的替代方案

**Comment by zhangbobell** [comment]
@miaogong @Naixor 我也不是很清楚 @miaogong  说的简单复制和粘贴时什么意思？简单的分支之间调整繁琐在什么地方，能否举例说明？感谢。
