### ISSUE TITLE
强烈呼吁恢复原先的多个脑图之间分支复制粘贴功能

### ISSUE THREAD

**Issue by miaogong** [fex-team/kityminder-editor#196]
现在的分支复制粘贴比以前多了一个步骤，alt+c，没有原版的方便快捷！

多个脑图之间也不能进行ctrl+c 和ctrl+v了，强烈呼吁恢复原先的分支复制粘贴功能！

**Comment by zhangbobell** [comment]
现在的版本是在 chrome 浏览器是支持 ctrl+c/v 进行跨 tab 页粘贴复制的，alt + c/v 是其余浏览器的降级方案。
原先的版本只能通过导入/导出实现这一功能，ctrl + c/v 只能在当前脑图使用。
所以这么看，现在应该是比原先的版本方便的。你可以提供一下你的浏览器版本，我们看一下是什么情况。

**Comment by miaogong** [comment]
呵呵，感谢开发者在周末时间还在回复！

一直是使用遨游浏览器访问的，所以在我这里，原先的版本是可以在多个脑图之间复制粘贴的！
也就是说，原先版本应该是支持chromium内核版本浏览器的跨tab页复制粘贴的。

使用chromium内核浏览器的在国内应该算是主流，如360，搜狗等等，所以还是希望官方考虑在这些浏览器中实现这个比较常用的功能。

**Comment by zhangbobell** [comment]
跨 tab 页复制粘贴是我们新加入的功能，原先的版本没有这个功能，由于 chrome 是支持的，所以猜测 chromium 内核的浏览器应该也是支持的，你可以看一下你的内核版本，如果太低就升级一下，应该就没有什么大问题了。

**Comment by weidays** [comment]
目前复制粘贴有个问题。就是脑图生成的自然id，会重复。这对用此作业务id的问题很大。希望能处理这个问题。

**Comment by zhangbobell** [comment]
@weidays 你说的 id 是脑图文件数据的 id 还是 svg 节点的 id ？前者是自动递增编号的，后者是随机生成的，不会重复，能否举例说明？

**Comment by weidays** [comment]
我说的 是节点id，确实是随机生成的。但是我复制的父节点，他顺便带过来的子节点的 id就是和被复制对象的id是一样的。我确实遇到这个问题了。你试试。

**Comment by weidays** [comment]
@zhangbobell    
![image](https://cloud.githubusercontent.com/assets/3984392/12577811/d96b350a-c457-11e5-8218-66cb9b341db4.png)
![image](https://cloud.githubusercontent.com/assets/3984392/12577824/e60be5c0-c457-11e5-8761-60bd16619946.png)
![image](https://cloud.githubusercontent.com/assets/3984392/12577826/ea00678c-c457-11e5-8cfc-5520f4d42172.png)

生成的km json如下，你看看
{"root":{"data":{"id":"dd406517601f","created":1450702799,"text":"思维导图"},"children":[{"data":{"id":"b1mq26ze8q0o","created":1453802740538,"text":"aaaa"},"children":[]},{"data":{"id":"b1mq284iz6ok","created":1453802743025,"text":"bbb"},"children":[]},{"data":{"id":"b1mq290wgmos","created":1453802744983,"text":"cccc"},"children":[]},{"data":{"id":"b1mq29przqww","created":1453802746488,"text":"ddd"},"children":[]},{"data":{"id":"b1mq2a9dq2gw","created":1453802747672,"text":"eee"},"children":[{"data":{"id":"b1mq2cwnam80","created":1453802753433,"text":"aaa"},"children":[]},{"data":{"id":"b1mq2e3m5mo0","created":1453802756031,"text":"ccc"},"children":[]},{"data":{"id":"b1mq2fqmyqwo","created":1453802759600,"text":"ccc"},"children":[]}]},{"data":{"id":"b1mq2ay8fvkg","created":1453802749175,"text":"分支主题"},"children":[{"data":{"id":"b1mq2a9dq2gw","created":1453802747672,"text":"eee"},"children":[{"data":{"id":"b1mq2cwnam80","created":1453802753433,"text":"aaa"},"children":[]},{"data":{"id":"b1mq2e3m5mo0","created":1453802756031,"text":"ccc"},"children":[]},{"data":{"id":"b1mq2fqmyqwo","created":1453802759600,"text":"ccc"},"children":[]}]}]}]},"template":"default","theme":"fresh-blue","version":"1.4.31"}

**Comment by Naixor** [comment]
其实他指的是全部的粘贴复制，跨不跨tab都会用一个id - -，因为是直接用的`node.data = util.clone()`做的 - -

**Comment by zhangbobell** [comment]
了解了，这一块后续考虑一下。
