### ISSUE TITLE
脑图比较大的时候，拖动分支到屏幕顶端，脑图不能跟随移动！

### ISSUE THREAD

**Issue by miaogong** [fex-team/kityminder-editor#197]
如果脑图文件比较大，显示的内容超出了屏幕范围，那么在拖动最下方的分支到上方的屏幕边缘时，脑图不会跟随移动！

ps，我是脑图的老用户，这个功能在原先版本是正常的！

**Comment by zhangbobell** [comment]
刚试了一下旧版本的脑图，没有出现你说的这个功能。不过这个需求很好，我们将在开发中加入。

**Comment by miaogong** [comment]
呵呵，印象中，原先版本是可以实现这个功能的，所以才会体现出很不方便！


可能是我记错了？（使用遨游浏览器）

**Comment by zhangbobell** [comment]
原先的版本没有这个功能的，未来将在开发中加入。
