### ISSUE TITLE
比较大的脑图在打开/关闭分支节点的时候，焦点会回到中心节点

### ISSUE THREAD

**Issue by miaogong** [fex-team/kityminder-editor#198]
还是比较大的脑图的问题，还是关于节点的焦点问题，建议官方开发自己多使用一下自己的产品！就知道这个地方是很反常规的。

如果一个节点在一个较大脑图的上方，这时候，打开/关闭节点，会使焦点回到中心节点。

相当于你在操作这个分支节点的时候，突然又回到屏幕中间了。然后你又要拖动屏幕到你刚才操作的地方，才能继续工作。思路一下子就被打断了！

这个问题以前提过，可能官方人员没有当做严重问题吧！

如果对于像我这样，把很大一部分工作从xmind转移到百度脑图的人来说，这个动作每天都会发生很多次。

希望能早日解决！

**Comment by zhangbobell** [comment]
想起了你说的这个问题，曾经在 QQ 群提过，我们记录下来了，但是刚才我尝试复现这个问题，可能的原因是不是展开折叠的时候，由于双击到空白画布上去了，导致回到中心节点？还是怎么个原因？能否图示？

**Comment by miaogong** [comment]
这么晚还在看公司的软件反馈？真是敬业啊！

刚才在遨游和chrome中都试验了一下，存在同样的问题！

就是比较大的脑图，在移动到最上方的分支节点的时候（此时中心节点已经在屏幕下方，看不到了），单击分支节点的+/-按钮，焦点会回到中心节点，也就是整个脑图又以中心节点为中心居中了。所以要回到刚才编辑的节点，又要重新拖动脑图！

打完以上文字后，又试验了了一下你说的双击空白处，确实会像上面一样回到中心节点，而且神奇的是，在此之后，再打开、关闭节点焦点就不会回到中心节点了！对我来说，也算是个临时解决方案吧！

**Comment by Naixor** [comment]
这个是我们的一个规则问题。。。不知道我这么描述是否明白，之所以会向下窜位，是你当前选中的节点在屏幕外侧，你展开节点和关闭节点的时候会触发渲染事件，触发这个事件的时候的一个规则：用户当前选择节点不在可视区，我们会帮用户把这个节点居中在可视区。这个貌似是很久很久以前有人提过的一个需求...
验证的话：你可以选中某个会出现在你要展开或关闭节点的可视区内的节点，不会出现这个问题。

@zhangbobell @miaogong 可以综合想一下这个用什么策略接地气一些哈~

**Comment by zhangbobell** [comment]
问题已经由 fex-team/kityminder-core 的 commit e37a414b6045663613983f2f222202128535a00d 修复。
