### ISSUE TITLE
百度云客户端端上不能访问脑图文件么？

### ISSUE THREAD

**Issue by leo07046219** [fex-team/kityminder-editor#208]
FAQ 10.1不再使用百度云作为储存，保证数据的稳定性和可操作性；
==》
这个更新是否意味着百度云客户端端上不能访问脑图文件么？如果能访问，还是在/我的网盘/我的应用数据/kityminder/mindmap目录么？

**Comment by zhangbobell** [comment]
目前百度脑图使用 [BOS](https://bce.baidu.com/product/bos.html) 作为储存，apps/kityminder 目录是 v1.4.18 之前的版本创建的文件，之后所有的文件都升级迁移至 BOS 上，百度云目录不再写入新的数据，旧的数据在 `/我的网盘/我的应用数据/kityminder` 目录里面。
