### ISSUE TITLE
保存时 500 报错

### ISSUE THREAD

**Issue by jimfeer** [fex-team/kityminder-editor#213]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>500 - Internal Server Error</title>\n </head>\n <body>\n  <h1>500 - Internal Server Error</h1>\n </body>\n</html>\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"d47877cffa83\",\"created\":1455347146,\"text\":\"LINUX\"},\"children\":[{\"data\":{\"id\":\"b21xicdqxvk0\",\"created\":1455347153236,\"text\":\"网络管理\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b21xiiev50gg\",\"created\":1455347166364,\"text\":\"IP配置\"},\"children\":[{\"data\":{\"id\":\"b21xikh3ec4w\",\"created\":1455347170852,\"text\":\"IFCOINFIG\"},\"children\":[{\"data\":{\"id\":\"b21xk94x80wk\",\"created\":1455347302900,\"text\":\"临时修改命令\"},\"children\":[]}]},{\"data\":{\"id\":\"b21xin1tfc0k\",\"created\":1455347176459,\"text\":\"SETUP[RED HAD专有]\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b21xkerlxg08\",\"created\":1455347315156,\"text\":\"永久修改\"},\"children\":[]},{\"data\":{\"id\":\"b21xltrg4gwk\",\"created\":1455347426162,\"text\":\"service network restart\"},\"children\":[]}]},{\"data\":{\"id\":\"b21xiopvw4gk\",\"created\":1455347180091,\"text\":\"配置文件\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b21xmoumnskc\",\"created\":1455347493835,\"text\":\"etc/sysconfig/network-scripts/ifcfg-etho\"},\"children\":[]},{\"data\":{\"id\":\"b21xrzxtvgg0\",\"created\":1455347909794,\"text\":\"etc/sysconfig/network\"},\"children\":[]},{\"data\":{\"id\":\"b21xt5dbaooc\",\"created\":1455347999978,\"text\":\"hostname test\"},\"children\":[{\"data\":{\"id\":\"b21xtg80t7kk\",\"created\":1455348023603,\"text\":\"查看与临时修改\"},\"children\":[]}]},{\"data\":{\"id\":\"b21xtpb7kc0s\",\"created\":1455348043386,\"text\":\"etc/resolv.conf\"},\"children\":[]},{\"data\":{\"id\":\"b21xwhgxfeo0\",\"created\":1455348261410,\"text\":\"修改UUID\"},\"children\":[{\"data\":{\"id\":\"b21xwmpga8kw\",\"created\":1455348272810,\"text\":\"vi /etc/sysconfig/network-scripts/ifcfg-eth0  #删除MAC地址行\"},\"children\":[]},{\"data\":{\"id\":\"b21xx771k44w\",\"created\":1455348317409,\"text\":\"rm -rf /etc/udev/rules.d/70-persistent-net.rules\n#删除网卡和MAC地址绑定文件\"},\"children\":[]},{\"data\":{\"id\":\"b21xxwfuze8s\",\"created\":1455348372362,\"text\":\"重启系统\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"b21y6c4e0e80\",\"created\":1455349033410,\"text\":\"网络查看\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b21y6pfvrqww\",\"created\":1455349062403,\"text\":\"ifup/ifdown\"},\"children\":[]},{\"data\":{\"id\":\"b21y6wtsqkcg\",\"created\":1455349078482,\"text\":\"netstat\"},\"children\":[]},{\"data\":{\"id\":\"b21yd16yuk8w\",\"created\":1455349558170,\"text\":\"nslookup\"},\"children\":[]},{\"data\":{\"id\":\"b21ygo0mcc4c\",\"created\":1455349842945,\"text\":\"telnet [端口号]\"},\"children\":[]},{\"data\":{\"id\":\"b21ygv2ibago\",\"created\":1455349858297,\"text\":\"traceroute  www.immoc.com\"},\"children\":[]},{\"data\":{\"id\":\"b21yidhftccs\",\"created\":1455349976746,\"text\":\"wget http://xxx.sdfa/sa.gz\"},\"children\":[]},{\"data\":{\"id\":\"b21yitw28bkg\",\"created\":1455350012458,\"text\":\"tcpdump\"},\"children\":[{\"data\":{\"id\":\"b21yk5l9mq04\",\"created\":1455350116291,\"text\":\"网络抓包\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b21yqq2b2r4s\",\"created\":1455350631042,\"text\":\"远程管理\"},\"children\":[{\"data\":{\"id\":\"b21yqsiaa680\",\"created\":1455350636362,\"text\":\"ssh\"},\"children\":[{\"data\":{\"id\":\"b21ysrktdggk\",\"created\":1455350791066,\"text\":\".ssh/host_name\"},\"children\":[]}]},{\"data\":{\"id\":\"b21yspcwnkg8\",\"created\":1455350786235,\"text\":\"scp\"},\"children\":[]},{\"data\":{\"id\":\"b21yxnvhy0gs\",\"created\":1455351174826,\"text\":\"xshell/winscp\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b21zj0aadzc4\",\"created\":1455352847489,\"text\":\"软件安装\",\"layout_mind_offset\":{\"x\":422,\"y\":95}},\"children\":[{\"data\":{\"id\":\"b21zvvdksjs4\",\"created\":1455353855538,\"text\":\"rpm\"},\"children\":[{\"data\":{\"id\":\"b220c5djbrk8\",\"created\":1455355131130,\"text\":\"-ivh -Uvh\"},\"children\":[]},{\"data\":{\"id\":\"b220c9je6jcc\",\"created\":1455355140192,\"text\":\"-ql qp\"},\"children\":[]},{\"data\":{\"id\":\"b220da4e4k08\",\"created\":1455355219825,\"text\":\"-V\"},\"children\":[]},{\"data\":{\"id\":\"b220fran8408\",\"created\":1455355413937,\"text\":\"rpm2cpio pack | cpi -idv\"},\"children\":[]}]},{\"data\":{\"id\":\"b21zvwwh0w00\",\"created\":1455353858858,\"text\":\"yum\"},\"children\":[{\"data\":{\"id\":\"b220p1uegzcw\",\"created\":1455356142177,\"text\":\"/etc/yum.repos.d/CentOS-Base.repo\"},\"children\":[]}]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.31\"}","fileGuid":"825355e755f2d36963f48d7bda72476a"},"headers":{"Accept":"application/json, text/plain, _/_","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by zhangbobell** [comment]
能否提供这个问题的复现步骤，我们正在排查这一问题。

**Comment by jimfeer** [comment]
报错过程，就是我在看视频，停止了脑图的操作，然后过一段时间后，网页就弹出这些提示错误了，要求我拷给开发人员。
我用的是360极速浏览器，内核使用极速模式。我在想，是不是我使用了一些特殊字符，例如 | 之类的？

**Comment by zhangbobell** [comment]
有少量用户反馈过相同的错误，可能的原因是你的网络环境访问脑图服务器失败导致的，具体原因我们仍在排查，目前不会对文件造成任何影响。
