### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by sundyloveme** [fex-team/kityminder-editor#214]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>A Database Error Occurred</h1>\n\t\t<p>Unable to connect to your database server using the provided settings.</p><p>Filename: core/Loader.php</p><p>Line Number: 346</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/get_latest_versions","data":{"fileGuid":"ec6616b13762de07d253e3bf71b86e3d"},"headers":{"Accept":"application/json, text/plain, _/_","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by zhangbobell** [comment]
这一问题是否持续出现？我们正在排查。

**Comment by sundyloveme** [comment]
不是！就那么一次。
  建议增加署名的功能啊，右下角署名这样的功能啊！

**Comment by zhangbobell** [comment]
署名？类似于水印？
