### ISSUE TITLE
【功能】点击脑图时，打开新页，不要在当前页打开

### ISSUE THREAD

**Issue by jimfeer** [fex-team/kityminder-editor#215]
如果脑图多了，想在各个脑图中切换，就要打开多张脑图，但习惯了点击，又得重新打开脑图。如果点击是打开新页面，那就方便多了，保留文档管理的页面。

**Comment by zhangbobell** [comment]
你可以右键选择在新窗口打开，这一功能目前已经具备。

**Comment by jimfeer** [comment]
你所说的只是IE自带的，我也可以接拖拉打开新页，如果能实现点击就是新的页面更好了。请再考虑一下，点击打开新页面这个功能。就像看新闻那样，我们都习惯打开一个新的页面看，看完后习惯性的关闭它，如果是同一页面跳转，那就连目录都关了。又得重新打开，很不符合人的习惯性思维。

**Comment by zhangbobell** [comment]
这个可能是个习惯问题，有部分「洁癖强迫症:smile:」用户不喜欢开太多的窗口，所以目前如果统一换成另一种打开方式可能不是一个很好的解决方法，就像百度搜索结果点击打开的方式一样。

**Comment by jimfeer** [comment]
产品应该面向大部分用户的习惯，何况你要在脑图间拷贝时，必需要打开多个窗口，跟你说的「洁癖强迫症」完全是逻辑冲突，何况好的习惯就是用完一个窗口，就应该关闭。软件就是为了更快，更懒的人工作的，如果还要多想一步，多操作一下，那跟软件开发的初衷有出入了。

**Comment by jimfeer** [comment]
新建脑图，这个不能在新窗口打开，有点让人痛苦。我还得点多几下，移动多几次鼠标才能回到我的工作区。
