### ISSUE TITLE
批量变更节点级次（高->低）时，节点顺序被改变

### ISSUE THREAD

**Issue by HunterGX** [fex-team/kityminder-editor#220]
在变更级次（高->低）时，节点顺序被改变，低->高  不存在这种情况。
变更前：
![image](https://cloud.githubusercontent.com/assets/9412439/13415172/b35b74c2-df93-11e5-97b4-b854678ddf88.png)
变更过程：
![image](https://cloud.githubusercontent.com/assets/9412439/13415185/c95ec81e-df93-11e5-9e6a-232e2ddac9f6.png)
变更后：
![image](https://cloud.githubusercontent.com/assets/9412439/13415191/dde00b5e-df93-11e5-8104-f60d11694adb.png)

**Comment by HunterGX** [comment]
刚试了一下，跨父节点移动，也会产生逆序效果
变更前：
![image](https://cloud.githubusercontent.com/assets/9412439/13415362/18ad4afc-df95-11e5-9c6b-c40b00988ecf.png)

变更后：
![image](https://cloud.githubusercontent.com/assets/9412439/13415373/28856acc-df95-11e5-9539-c4933c42f3cb.png)

**Comment by zhangbobell** [comment]
已确认，这的确是个 bug，我们会在下个版本修复。

**Comment by zhangbobell** [comment]
问题已经修复，详情见 https://github.com/fex-team/kityminder-core/commit/bc2fc1b5a45789dafacacd2862eaf66c00cc949a
