### ISSUE TITLE
脑图 多节点后自动偏移问题

### ISSUE THREAD

**Issue by yangweijie** [fex-team/kityminder-editor#223]
左右 2个节点，右节点后添加几层自己点后 再添加 节点反转显示，这时候用户为了看清楚，拖动右第一个节点，右拖动后，显示完整（不翻转）后放开，结果 右边图像部分无限往右偏移。

**Comment by zhangbobell** [comment]
这个我们已经知晓并修复，具体可参见 1975186ea77c348ed3c9353c1b73a60cd809cb7f，将在下个更新解决。
