### ISSUE TITLE
打开脑图项目后报错

### ISSUE THREAD

**Issue by hahnzhu** [fex-team/kityminder-editor#225]
如下图所示，涉及项目比较多，望尽快处理。如需提供具体信息可联系我。

![image](https://cloud.githubusercontent.com/assets/2987435/13665051/7ca74268-e6e5-11e5-8bb4-47803c4e4757.png)

**Comment by hahnzhu** [comment]
服务器问题，现在可以正常访问了

**Comment by zhangbobell** [comment]
百度脑图所使用的 BOS 服务于 17:05 分左右出现故障，目前百度云那边的同事正在排查，您的文件可能会出现暂时不能打开的情况，等那边修复好了就 OK 了，脑图数据不会受到影响，给你带来了不便敬请谅解。
