### ISSUE TITLE
文件名自动被重命名的bug

### ISSUE THREAD

**Issue by jixing-ji** [fex-team/kityminder-editor#230]
# 文件名BUG
1. 我新建一个脑图文件叫做aaa
2. 打开abc这个文件添加一个主题，命名为bbb
3. 关闭这个文件，文件名就被自动重命名为bbb！

即使再次修改文件名，进去之后仍然会被重命名！

**Comment by zhangbobell** [comment]
这个 bug 我们已经知晓并复现，将在下个版本修复。

**Comment by zhangbobell** [comment]
已由 commit 65752c24a5ec0a6b8f0725543c5b40ea67a667cd 修复，待上线。

**Comment by zhangbobell** [comment]
问题已修复。

**Comment by jixing-ji** [comment]
我又试了一下，还是不行哎

**Comment by zhangbobell** [comment]
脑图现在的重命名机制是：根节点文字和标题是单向绑定的关系，即更改根节点文字会引起标题的变化，而在编辑页面或文件列表修改标题不会引起根节点文字的变动。
