### ISSUE TITLE
移动子节点bug

### ISSUE THREAD

**Issue by cuining** [fex-team/kityminder-editor#237]
![bug](https://raw.githubusercontent.com/cuining/X/master/issue114.png)

如图，我用鼠标拖动一个子节点的时候，子节点并没有按照我想要的方向运动，而是跑到边界外面了

上下移动（碰到容器边界时）好像也有问题

浏览器版本 chrom 51.0.2687.0 dev-m

**Comment by zhangbobell** [comment]
这个问题我们已经上线解决。
