### ISSUE TITLE
画布拖动问题

### ISSUE THREAD

**Issue by LancelotLewis** [fex-team/kityminder-editor#245]
在实际使用中，目前是需要按住alt和鼠标左键就能够拖动画布。如果用户先释放alt，再释放鼠标，一切正常；如果用户先释放鼠标左键，再释放alt键，这时画布还处于可拖动状态，望解决！

**Comment by Naixor** [comment]
报下操作系统以及浏览器版本型号？刚才mac上的几个浏览器上试了下，正常走逻辑这部分没有问题，...另外，复现过程真的就只是先放开左键再放开alt嘛？

**Comment by LancelotLewis** [comment]
@Naixor win10 360极速浏览器最新版，我用脑图很久了，一直都是这样。
我用win10的edge浏览器同样操作没有问题，但是发现页面的样子比较诡异。
![image](https://cloud.githubusercontent.com/assets/8749615/14522242/362515fe-0260-11e6-8be1-a0bda125dbd0.png)

**Comment by Naixor** [comment]
360...还请不要使用了，从来没对他的兼容性做过适配，不过edge浏览器，由于要解决其本身浏览渲染的另一个BUG，我们会不停地重绘节点，有比较诡异的时候，win10的话建议你使用chrome，或者ff，百度浏览器等我们支持的浏览器。

**Comment by zhangbobell** [comment]
这个问题我们已经上线解决。
