### ISSUE TITLE
紧凑蓝，三行文本时与上一个 Item 字体重叠

### ISSUE THREAD

**Issue by yangyanqing** [fex-team/kityminder-editor#255]
![default](https://cloud.githubusercontent.com/assets/7357939/15073999/1923923e-13cf-11e6-8c67-4d5f85268896.JPG)

**Comment by yangyanqing** [comment]
Firefox 45.0.2
当增加一个与“3、数据管理”同级的 Item 时，重叠部分会自动调整展开

**Comment by zhangbobell** [comment]
点击「整理布局」按钮能否解决问题？

**Comment by yangyanqing** [comment]
@zhangbobell 可以解决问题，不过这个按钮也找了半天
