### ISSUE TITLE
请问一下kityminder-protocol现在已经没有了吗？

### ISSUE THREAD

**Issue by kgdxpr** [fex-team/kityminder-editor#259]
我想用KityMinder来做在线显示脑图，但我想在线显示的是XMind的文件，
说明上写需要用kityminder-protocol 来扩展第三方格式支持
但我一点链接就404了，我该怎么能找到，或是有别的替代方法吗，谢谢

**Comment by zhangbobell** [comment]
kityminder-protocol 其实并没有着手开始做，这一块我们会逐步补上。如果你想做 xmind 文件的导入导出，建议参考 https://github.com/fex-team/kityminder/tree/dev/src/protocol 下的 xmind.js 和 xmind.md 完成。
