### ISSUE TITLE
能否将百度脑图的导出功能开源出来啊

### ISSUE THREAD

**Issue by jmolboy** [fex-team/kityminder-editor#265]
能否将文件导出功能一并开源呢？这样直接在本地host一个就可以使用了

**Comment by zhangbobell** [comment]
文件导入导出功能不属于一个编辑器应该负责的，我们打算做一个 kityminder-protocol 定义一套数据输入输出的协议，但是现在还没有时间做。但是如果你想做文件的导入导出，建议参考 https://github.com/fex-team/kityminder/tree/dev/src/protocol 完成。
