### ISSUE TITLE
npm上的版本怎么还是1.0.21，是不打算在npm上发布新版本了吗？

### ISSUE THREAD

**Issue by jmolboy** [fex-team/kityminder-editor#266]
想基于kityminder-editor开发，但是不想用bower，但是npm上的版本好久没更新了；
是不会继续在npm上发布后续版本了么

**Comment by jmolboy** [comment]
不用bower的原因是，我要基于electron开发本地应用；但是bower_componments无法打包和压缩，显得太庞大了；这个不知有什么好的方案？百度脑图最终是怎么压缩合并bower_componments的呢？

**Comment by zhangbobell** [comment]
刚发现确实是如此。由于我还没加入到 npm 包管理权限群组里，所以这块就一直没有更新。已经联系了 admin @zswang ，将于这两天更新到最新版。

**Comment by zswang** [comment]
done

**Comment by zhangbobell** [comment]
npm  已经更新到最新版了 1.0.55 @jmolboy

**Comment by jmolboy** [comment]
3q

**Comment by jmolboy** [comment]
3q
