### ISSUE TITLE
文档呢?

### ISSUE THREAD

**Issue by bluewaitor** [fex-team/kityminder-editor#269]
文档找不到, 找到的都是死链接.
我想看导出图片的option参数是什么意思,都找不到.
顺便问一下,导出的图片能控制大小吗?

**Comment by zhangbobell** [comment]
你是基于 kityminder-editor 做二次开发？option 参数目前对于导出 png 还没有用，图片大小不能控制尺寸，具体可以参见 https://github.com/fex-team/kityminder-core/blob/dev/src/protocol/png.js，如果可以，你可以在这个文件的基础上补充 option 功能，让其支持传入尺寸、图片质量等参数，欢迎向我们提 PR，文档这一块目前还不全，我们会逐步完善。

**Comment by bluewaitor** [comment]
已经提了PR了

**Comment by zhangbobell** [comment]
已经合并，感谢提供:smile:
