### ISSUE TITLE
拖动的时候吧(估计是)，就报500错误

### ISSUE THREAD

**Issue by Lee-Feng** [fex-team/kityminder-editor#274]
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"dfd181e771af\",\"created\":1468287397,\"text\":\"指令后置语句方案\",\"note\":\"这里只讨论后置语言的相关问题，因为MoveL,MoveC等前半句就相当于函数的调用也已。\"},\"children\":[{\"data\":{\"id\":\"b5lce0ga6mo8\",\"created\":1468287244957,\"text\":\"模仿Lua方案(C++端保存异步的脚本函数)\"},\"children\":[{\"data\":{\"id\":\"b5lceph3iog8\",\"created\":1468287299425,\"text\":\"脚本线程执行\"},\"children\":[{\"data\":{\"id\":\"b5lcg01sh14w\",\"created\":1468287400809,\"text\":\"对于条件检测Until\"},\"children\":[]},{\"data\":{\"id\":\"b5lcgksrdbsw\",\"created\":1468287445975,\"text\":\"对于操作执行With\"},\"children\":[]},{\"data\":{\"id\":\"b5lch1kco4ws\",\"created\":1468287482472,\"text\":\"以后可能还有其他操作\"},\"children\":[]}]},{\"data\":{\"id\":\"b5lcf81i78gg\",\"created\":1468287339841,\"text\":\"新线程执行\"},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.33\"}","fileGuid":"cb29109dec0267355f5ee0d559a3fba9","csrf_token":"4de8f39484035df08588b1fa272979f4"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 SE 2.X MetaSr 1.0

**Comment by zhangbobell** [comment]
看了一下，这是后端错误多是由于后端稳定性造成的，跟前端的操作（拖动、缩放）没有太大关系，一般刷新一下页面就正常了，如果这个问题频繁出现，请联系我们。

**Comment by zhangbobell** [comment]
先 close 了。
