### ISSUE TITLE
能不能将脑图导出图片，这样便于保存。

### ISSUE THREAD

**Issue by CymChad** [fex-team/kityminder-editor#278]
RT

**Comment by zhangbobell** [comment]
这个功能现在已经具备了，点击左上角「百度脑图」->「另存为」即可。

**Comment by CymChad** [comment]
恩 好的，多谢。致敬开源者

**Comment by CymChad** [comment]
我是一名android开发，也做过自己开源项目，希望以后有app项目，我开源加入献出一份自己的力量。

**Comment by loonmoon** [comment]
我用的是X-mind，可以导出各种的图片，还可以配合印象笔记使用，一键同步图片和文档。

**Comment by CymChad** [comment]
百度脑图可以配合印象笔记使用吗？
