### ISSUE TITLE
辛辛苦苦编辑的脑图不见了~~

### ISSUE THREAD

**Issue by Beatles123** [fex-team/kityminder-editor#279]
之前几天做了个脑图，之后的每天都有用，每天也都有保存，今天早上想再加点东西进去，竟然变成空白文档了······我重复刷新了好几次······还是这样······崩溃了~~

**Comment by zhangbobell** [comment]
你可以尝试使用「历史版本」功能恢复，如果仍有问题，可以通过 QQ 群找到我。

**Comment by Beatles123** [comment]
哈哈，感谢！！！已经恢复了~~
