### ISSUE TITLE
本地可以直接运行 kityminder-editor demo 吗

### ISSUE THREAD

**Issue by livem** [fex-team/kityminder-editor#285]
我直接在本地，使用 chrome 打开 kityminder-editor-master\dist\index.html

直接运行不了的。

看了一下 index.html ，里面依赖了很多第三方的 js 和 css ，但找不到 bower_components 这个文件夹呢。。。。

想问问，本地可以直接运行 demo 么？
新手求教，谢谢！

**Comment by zhangbobell** [comment]
请参考 https://github.com/fex-team/kityminder-editor#使用

**Comment by livem** [comment]
生产环境也得引用很多第三方库么？

我看了一下 naotu.baidu.com 的编辑页面，貌似只引用了 kityminder 的相关东东～～～没发现其他的。。。

**Comment by zhangbobell** [comment]
生产环境下可以将引用的第三方库通过 uglify-js 等 npm 包合并压缩。

**Comment by livem** [comment]
原来是这样子，学习了 ^_^

**Comment by livem** [comment]
kityminder-core-dev/example.html

倒是简单很多，直接就可以打开浏览器渲染出来了。

**Comment by jiangtao** [comment]
@linanyways 可以参考 我搞的一个简单版本 https://github.com/hexyun/vue-minder
功能目前没那么多。

**Comment by automan-lmx** [comment]
好的，谢谢你呀。五一快乐哟




------------------ 原始邮件 ------------------
发件人: "jiangtao"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 下午4:35
收件人: "fex-team/kityminder-editor"<kityminder-editor@noreply.github.com>; 
抄送: "林曼贤"<807904746@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [fex-team/kityminder-editor] 本地可以直接运行 kityminder-editor demo 吗 (#285)




@linanyways 可以参考 我搞的一个简单版本 https://github.com/hexyun/vue-minder，功能目前没那么多。
