### ISSUE TITLE
百度脑图登陆提示

### ISSUE THREAD

**Issue by rainwa** [fex-team/kityminder-editor#287]
隔天登陆重新输入密码后会提示用户名或密码错误。我快抓狂啦，密码是对的，是对的，是对的！！！

**Comment by zhangbobell** [comment]
你可以在 http://passport.baidu.com （需要先退出百度账户，或者你打开浏览器的隐身模式）这里登录看看，如果登录有问题，你可能需要申诉了。如果没有问题，请提供一下你的百度用户名，我帮你看一下。
