### ISSUE TITLE
“整理布局”使更改后布局变为初始的布局了

### ISSUE THREAD

**Issue by ohmydengzi** [fex-team/kityminder-editor#296]
一个逻辑结构图，同一层有多个节点，改变节点的上下关系，然后“整理布局”。“整理布局”之后，布局就变为没改变前的了。这个能不能优化一下？

我想手动改变节点的上下关系，又想使用“整理布局”使得美观一点。

**Comment by zhangbobell** [comment]
调整节点的时候，你需要注意到有个占位符的概念，拖动节点时，在画布上节点可能的位置会有一个深色的占位符，拖到占位符后，整理布局时就不会重新调整了。

**Comment by ohmydengzi** [comment]
噢，好的，谢谢！
