### ISSUE TITLE
Demo页不能编辑?

### ISSUE THREAD

**Issue by lealife** [fex-team/kityminder-editor#3]
![image](https://cloud.githubusercontent.com/assets/1699428/6746604/4ab4093c-cf06-11e4-891c-b5a50c01d4e1.png)
找不到工具栏可以编辑.

**Comment by czfshine** [comment]
这个kityminder-editor 仓库是实现基础功能的，工具栏什么的在kityminder 那个仓库

**Comment by techird** [comment]
@lealife @czfshine 目前 kityminder-editor 正在基于 angular 迁移之前的 UI 功能，可以关注 dev 分支。

**Comment by zhangbobell** [comment]
这个问题已经得到了改善，kityminder-editor 现在是一个完整的脑图编辑器。
