### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by JiayingZeng** [fex-team/kityminder-editor#302]
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/file_info","data":{"fileGuid":"3a861989abd2fe45f7acf6cfe24eb34a","csrf_token":"90261e8707959a6c1a2ea6bc97d2e705"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于服务器不稳定造成的，我们正在排查，不会对数据有影响。
