### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by escblack** [fex-team/kityminder-editor#304]
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"8243aa685392c07fa11263335dd31ffe","csrf_token":"85aff5d2bd2c5aab2c590adeccc81e38"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于服务器不稳定造成的，我们正在排查，不会对数据有影响，重试就好。
