### ISSUE TITLE
错误：百度脑图 回收站 批量操作彻底删除报错

### ISSUE THREAD

**Issue by Wangyilie** [fex-team/kityminder-editor#305]
在回收站页面，批量操作->全选->彻底删除，首次删除时报错，再次删除时正常。

 报错信息如下：
> 错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/clear","data":{"selectedFileGuids":["79c0166efdd24c0c6f292af5d7835476","911e7d81bd4c36deeeff9567011fdc1c","438ff7c2504080413deed8026b08b188","1dedda2154dd40201133dcf9dff75e90","65d12fa614319ee48f774f0db138b832","0a14f566c7f0129b7ba7235e8f96672b"],"csrf_token":"f36a4cbee94b15702235b02b0261ee6b"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于服务器网络不稳定造成的，我们正在排查，重试即可，不会影响数据，如果该问题重试仍然无法解决并稳定重现，请联系我们。
