### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GitHubdomain** [fex-team/kityminder-editor#306]
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/get_root_dir","data":{"csrf_token":"2838df7aa45e4353a635ea868fc84f57"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于服务器网络不稳定造成的，我们正在排查，重试即可，不会影响数据，如果该问题重试仍然无法解决并稳定重现，请联系我们
