### ISSUE TITLE
百度脑图问题反馈

### ISSUE THREAD

**Issue by lokoR** [fex-team/kityminder-editor#309]
错误
 {"data":null,"status":-1,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"232551d96b8e26649770520a30b4fa08","csrf_token":"49ef6f85c5d86901772c06e4f9608a32"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":""}

浏览器信息：Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by zhangbobell** [comment]
这个错误一般是由于你所在的网络不畅导致的，请尝试切换更好的网络条件。
