### ISSUE TITLE
百度脑图：数据丢失

### ISSUE THREAD

**Issue by shiyi2000** [fex-team/kityminder-editor#313]
这是第三次丢失数据了，前两次整张脑图都不见了，这一次点开只有中心主题。
我是一个程序语言初学者，我把所有消化后的笔记都放到你们的产品里了，而现在我需要重新review我的教材，这让我感觉很生气。
我使用的浏览器是Chrome，每次关闭前都已经确保更改已保存。
我昨天清空了一次历史记录，是这个原因造成的吗？但只有几张脑图的数据丢失，其余皆保存完好，请问这是怎么一回事？丢失的数据可以找回吗？

希望你们能尽快给予解答，感谢。

**Comment by zhangbobell** [comment]
你可以通过历史版本功能找回你的文件。

**Comment by shiyi2000** [comment]
历史版本没有完整的数据，只有一开始空白的脑图而已

**Comment by zhangbobell** [comment]
提供一下你的脑图地址。

**Comment by shiyi2000** [comment]
http://naotu.baidu.com/file/9759dc6b8fc5abd739a09edd2f596867

**Comment by shiyi2000** [comment]
How is it now
Please be faster, thank you

**Comment by zhangbobell** [comment]
问题已通过邮件单独回复。
