### ISSUE TITLE
怎么自定义节点内容

### ISSUE THREAD

**Issue by jmolboy** [fex-team/kityminder-editor#314]
怎么自定义脑图节点里的排版和样式呢？

**Comment by zhangbobell** [comment]
你可以参考 [kityminder-core](https://github.com/fex-team/kityminder-core) 里面 [template](https://github.com/fex-team/kityminder-core/tree/dev/src/template) 和 [theme](https://github.com/fex-team/kityminder-core/tree/dev/src/theme) 自定义。

**Comment by jmolboy** [comment]
我想自定义节点里的内容，在节点里创建复合的dom结构，比如在节点力创建自定义的图文混合内容？
template和theme只是改了外观吧；

**Comment by zhangbobell** [comment]
oo，你是想在节点里插入其他的内容？下图中有：文本、链接、优先级、进度、备注和图片
![image](https://cloud.githubusercontent.com/assets/6234613/19925009/2c8e64a6-a129-11e6-8ac6-75242284413f.png)

如果要插入其他内容，需要创建这个类型（负责内容）并创建渲染器（render, 负责在节点合适的位置渲染），可以参考[进度图标](https://github.com/fex-team/kityminder-core/blob/dev/src/module/progress.js)

**Comment by jmolboy** [comment]
ok；内容只能是kity里定义的基本内容的混合形式吗？

**Comment by zhangbobell** [comment]
不限于吧，只不过如果是用 kity 里定义的用起来会方便很多。

**Comment by jmolboy** [comment]
好的，多谢

**Comment by jmolboy** [comment]
![Uploading 111.png…]()
实现这样的节点，全部用svg实现好复杂，svg node里能嵌入html吗？或者其他方法

**Comment by zhangbobell** [comment]
svg 里面不支持嵌入 html，我建议你深入研究一下 kityminder-core 的渲染机制，不同的组件是怎么样在节点中定位和渲染的，这样写好了之后，能大大提高效率。

**Comment by jmolboy** [comment]
好的，感谢指导
