### ISSUE TITLE
error of 百度脑图

### ISSUE THREAD

**Issue by zy19348** [fex-team/kityminder-editor#320]
错误
 {"data":"Internal Server Error","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"8f381ebf690f\",\"created\":1478749972,\"text\":\"CRM\",\"priority\":null},\"children\":[{\"data\":{\"id\":\"b8gd58e3re0o\",\"created\":1478750053608,\"text\":\"responsive supply chain managemnt\"},\"children\":[{\"data\":{\"id\":\"b8gd7cnn4fks\",\"created\":1478750219621,\"text\":\"quantity supplied and reduce the inventories\"},\"children\":[]}]},{\"data\":{\"id\":\"b8gd6lrdjz4g\",\"created\":1478750161073,\"text\":\"increasing the customers retention \"},\"children\":[]},{\"data\":{\"id\":\"b8gd6n81ro8c\",\"created\":1478750164258,\"text\":\"reach new customers\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.33\"}","fileGuid":"db1a4abf5ec35f556a9182dc69df27f3","csrf_token":"042d1669a37af0fe64bc3211d9d905af"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.22 Safari/537.36 SE 2.X MetaSr 1.0

**Comment by zhangbobell** [comment]
这个问题是由于服务器网络不稳定造成的，我们正在排查，重试即可，不会影响数据，如果该问题重试仍然无法解决并稳定重现，请联系我们
