### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by xingfinal** [fex-team/kityminder-editor#322]
今天在进入脑图时, 提示错误.
1.4.33版本
错误
 {"data":"","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"c9583fb7b1d68ac0bbec5a10dbe75082","csrf_token":"caf1e70856cdd987da5161e88550fe53"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于服务器不稳定造成的，我们将于近期进行升级解决这个问题，你重试即可，不会影响数据。

**Comment by xingfinal** [comment]
多谢您及时的回复. 希望脑图越来越好~~
