### ISSUE TITLE
MBP SF 另存导出的 PNG 和 SVG 显示不出图来。

### ISSUE THREAD

**Issue by JeffenCheung** [fex-team/kityminder-editor#325]
**环境：**
* mac book pro safari，英文

**现象：**
* 导出 png 和 svg 都不显示内容或乱码

**原因：**
* 是中文字库体缺失造成的？

**Comment by zhangbobell** [comment]
提供一下脑图的分享链接地址和你的浏览器的详细版本信息，如果在这里不方便，可以通过 QQ 群方式单独发给我。

**Comment by JeffenCheung** [comment]
browser：Safari Version 10.0.1 (12602.2.14.0.7)
os：MBP 2012 mac book pro

脑图分享：http://naotu.baidu.com/file/1aee78475481ff440463879598439671?token=37d5c76f053b0af9
导出PNG提示：
脑图的节点中包含跨域图片，导出的 png 中节点图片不显示，你可以替换掉这些跨域的图片并重试。

点击 close ，无视它，关闭窗体后，导出了一张空白 PNG。

但在 windows 下 google chrome 可以顺利导出这个 PNG。

**Comment by zhangbobell** [comment]
Safari 需要停止跨源限制，`开发`->`停用跨源限制`
