### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by jiuyuezai** [fex-team/kityminder-editor#339]
错误
 {"data":"<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","status":400,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"b9iqvczzl9cg\",\"created\":1482648053889,\"text\":\"图论\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9kgt0lc97cc\",\"created\":1482822778968,\"text\":\"图的基本概念\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9is4eujg80k\",\"created\":1482651584301,\"text\":\"图\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b9is4gzm8ewc\",\"created\":1482651588961,\"text\":\"无序积A&B\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9is58izghcs\",\"created\":1482651648905,\"text\":\"无序对{a,b}记为(a,b)，(a,b)=(b,a)，A&B=B&A\",\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"b9is4nljcf4g\",\"created\":1482651603347,\"text\":\"无向图G=<V,E>（有序二元组）\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9is708pazcc\",\"created\":1482651787598,\"text\":\"顶点集：V是一个非空有穷集，其元素称作顶点或结点\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9is7wvzduwo\",\"created\":1482651858663,\"text\":\"边集：E是无序积V&V的有穷多重子集，其元素称作无向边，简称边\",\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"b9is9va2xb4g\",\"created\":1482652011890,\"text\":\"有向图D=<V,E>（有序二元组）\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9isi45fsgoc\",\"created\":1482652658113,\"text\":\"顶点集：V是一个非空有穷集，其元素称作顶点或结点\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isi63g68g8\",\"created\":1482652662347,\"text\":\"边集：E是笛卡儿积VxV的有穷多重子集，其元素称作有向边，简称边\",\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"b9islfp0or48\",\"created\":1482652918334,\"text\":\"n阶图：n个顶点的图\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9ism0wu3ns4\",\"created\":1482652964520,\"text\":\"零图：一条边也没有的图。n阶零图记作Nn\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9ismi8fy9kw\",\"created\":1482653002227,\"text\":\"平凡图：1阶零图只有一个顶点，没有边\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isnkqzdu04\",\"created\":1482653086065,\"text\":\"空图：顶点集为空集\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isoa36st4c\",\"created\":1482653141223,\"text\":\"标定图：给每一个顶点和每一条边指定一个符号\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isoyshwkgg\",\"created\":1482653194996,\"text\":\"基图：将有向图的各条有向边改成无向边后得到的图称作这个有向图的基图\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isqd4zxcoc\",\"created\":1482653304591,\"text\":\"端点、始点、终点、孤立点、关联、环、关联次数、相邻\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9isrqf9vz4k\",\"created\":1482653411875,\"text\":\"领域、闭领域、关联集、后续元集、先驱元集\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9iss892o4gk\",\"created\":1482653450682,\"text\":\"平行边、重数、多重图、简单图\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9it34betq0w\",\"created\":1482654304122,\"text\":\"度数、出度、入度、最大度、最小度、悬挂顶点、悬挂边、偶度（奇度）顶点\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9it6eddieww\",\"created\":1482654561101,\"text\":\"定理\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9it7p9fdk8o\",\"created\":1482654663171,\"text\":\"在任何无向图中，所有顶点的度数之和等于边数的2倍\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j0zby58qgw\",\"created\":1482676576157,\"text\":\"在任何有向图中，所有顶点的度数之和等于边数的2倍\\n所有顶点的入度之和等于所有顶点的出度之和，都等于边数\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j1024jseg4\",\"created\":1482676633140,\"text\":\"任何图中，奇度顶点的个数是偶数\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j10rn56eos\",\"created\":1482676688684,\"text\":\"非负整数列是可图化的当且仅当它们的和为偶数\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j11wmlbh4c\",\"created\":1482676777899,\"text\":\"任意n阶无向简单图的最大度≤n-1\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9j12omwas8c\",\"created\":1482676838867,\"text\":\"通路和回路\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b9j12rq1yq04\",\"created\":1482676845588,\"text\":\"通路\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j13h0td0gg\",\"created\":1482676900659,\"text\":\"始点\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j13kc4kpsk\",\"created\":1482676907873,\"text\":\"终点\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j13ljbh1c0\",\"created\":1482676910485,\"text\":\"长度\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j140k541s0\",\"created\":1482676943186,\"text\":\"简单通路\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j14fx74g84\",\"created\":1482676976627,\"text\":\"初级通路/路径\",\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"b9j15d60igow\",\"created\":1482677048994,\"text\":\"复杂通路\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j13wpdehsg\",\"created\":1482676934795,\"text\":\"回路\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j149ib8cg0\",\"created\":1482676962667,\"text\":\"简单回路\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j14kvo854w\",\"created\":1482676987419,\"text\":\"初级回路/圈\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j14qtvhygo\",\"created\":1482677000371,\"text\":\"奇圈\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j14sw7muos\",\"created\":1482677004866,\"text\":\"偶圈\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j14y044e0w\",\"created\":1482677015986,\"text\":\"圈的长度至少为3\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9j158vqgoow\",\"created\":1482677039666,\"text\":\"复杂回路\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9j15j4qlxk4\",\"created\":1482677061978,\"text\":\"定理\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j15nejg34s\",\"created\":1482677071282,\"text\":\"在n阶图G中，若从顶点u到v(u≠v)存在通路，则从u到v存在长度小于等于n-1的通路\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j16fbly144\",\"created\":1482677132050,\"text\":\"在n阶图G中，若从顶点u到v(u≠v)存在通路，则从u到v一定存在长度小于等于n-1的初级通路\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j16v8kvago\",\"created\":1482677166697,\"text\":\"在n阶图G中，若存在v到自身的回路，则一定存在v到自身长度小于等于n的回路\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j17rbn3pk4\",\"created\":1482677236538,\"text\":\"在n阶图G中，若存在v到自身的简单回路，则一定存在v到自身长度小于等于n的初级回路\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9j188boe0ow\",\"created\":1482677273545,\"text\":\"图的连通性\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j4epguxeog\",\"created\":1482686244379,\"text\":\"连通、连通图、非连通图\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4fee66g8o\",\"created\":1482686298636,\"text\":\"连通分支、连通分支数\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4fm9tr6wo\",\"created\":1482686315787,\"text\":\"短程线、距离\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4k4rqnmog\",\"created\":1482686669509,\"text\":\"点割集、割点、边割集/割集、割边、桥\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4pymxh3c4\",\"created\":1482687126343,\"text\":\"点连通度/连通度、边连通度\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4rf13t5c8\",\"created\":1482687240392,\"text\":\"可达、相互可达\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4sde9gco4\",\"created\":1482687315199,\"text\":\"弱连通图/连通图、单向连通图、强连通图\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9j4var6rvso\",\"created\":1482687544542,\"text\":\"二部图/二分图/偶图\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9j4vncbrc0g\",\"created\":1482687571942,\"text\":\"n(n≥2)阶无向图G是二部图当且仅当G中无奇圈\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9jfcbv8e1c8\",\"created\":1482717090253,\"text\":\"图的矩阵表示\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b9jfw4oy3ugw\",\"created\":1482718641919,\"text\":\"关联矩阵\",\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"b9jg15djlp4c\",\"created\":1482719035227,\"text\":\"邻接矩阵\",\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"b9jwwsz6n7s4\",\"created\":1482766653649,\"text\":\"图的运算\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b9jwz1266vc4\",\"created\":1482766827973,\"text\":\"P311\",\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9kgt6jotygo\",\"created\":1482822791929,\"text\":\"欧拉图与哈密顿图\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"b9kgt9qxwt4c\",\"created\":1482822798898,\"text\":\"欧拉图\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"b9kgtb2ft68s\",\"created\":1482822801770,\"text\":\"欧拉通路\"},\"children\":[{\"data\":{\"id\":\"b9kgtebtr3co\",\"created\":1482822808868,\"text\":\"半欧拉图\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kgtic0fvkk\",\"created\":1482822817586,\"text\":\"欧拉回路\"},\"children\":[{\"data\":{\"id\":\"b9kgtlmev74s\",\"created\":1482822824745,\"text\":\"欧拉图\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kgtvg1ywow\",\"created\":1482822846129,\"text\":\"平凡图是欧拉图\"},\"children\":[]},{\"data\":{\"id\":\"b9kgu55iu7ks\",\"created\":1482822867273,\"text\":\"定理\"},\"children\":[{\"data\":{\"id\":\"b9kgu6t12fsc\",\"created\":1482822870858,\"text\":\"无向图G是欧拉图当且仅当G是连通图且没有奇度顶点\"},\"children\":[]},{\"data\":{\"id\":\"b9kgvzn0qu8k\",\"created\":1482823011985,\"text\":\"无向图G是半欧拉图当且仅当G是连通的且恰有两个奇度顶点\"},\"children\":[]},{\"data\":{\"id\":\"b9kgxa0a7bc4\",\"created\":1482823112919,\"text\":\"有向图D是欧拉图当且仅当D是强连通的且每个顶点的入度等于出度\"},\"children\":[]},{\"data\":{\"id\":\"b9kgxus7snc4\",\"created\":1482823158144,\"text\":\"有向图D是半欧拉图当且仅当D是单向连通的且恰有两个奇度顶点，其中一个顶点的入度比出度大1，另一个顶点的出度比入度大1，而其余定点的入度等于出度\"},\"children\":[]},{\"data\":{\"id\":\"b9kgyswixw8c\",\"created\":1482823232415,\"text\":\"G是非平凡的欧拉图当且仅当G是连通的且是若干个边不重的圈的并\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9kj24hvw2ok\",\"created\":1482829134964,\"text\":\"哈密顿图\"},\"children\":[{\"data\":{\"id\":\"b9kj2aqokdcg\",\"created\":1482829148556,\"text\":\"哈密顿通路\"},\"children\":[{\"data\":{\"id\":\"b9kj36ytxfk0\",\"created\":1482829218706,\"text\":\"半哈密顿图\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kj3lwsqcgk\",\"created\":1482829251235,\"text\":\"哈密顿回路\"},\"children\":[{\"data\":{\"id\":\"b9kj3nirvy80\",\"created\":1482829254740,\"text\":\"哈密顿图\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kj3ppbj2g4\",\"created\":1482829259490,\"text\":\"平凡图是哈密顿图\"},\"children\":[]}]}]},{\"data\":{\"id\":\"b9kja9ddxv4s\",\"created\":1482829772489,\"text\":\"最短路问图、中国邮递员问题与货郎担问题\"},\"children\":[{\"data\":{\"id\":\"b9kn6c9i69cs\",\"created\":1482840749767,\"text\":\"带权图G=<V,E,W>\"},\"children\":[{\"data\":{\"id\":\"b9kn8h6dob48\",\"created\":1482840917191,\"text\":\"权\"},\"children\":[]},{\"data\":{\"id\":\"b9kn8j23chcs\",\"created\":1482840921285,\"text\":\"长度\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kn8ny71hs8\",\"created\":1482840931933,\"text\":\"最短路问题\"},\"children\":[{\"data\":{\"id\":\"b9kn9rls2h44\",\"created\":1482841018254,\"text\":\"最短路径\"},\"children\":[]},{\"data\":{\"id\":\"b9kn9vgtrkoc\",\"created\":1482841026661,\"text\":\"距离\"},\"children\":[]}]},{\"data\":{\"id\":\"b9kn8r9s1kow\",\"created\":1482840939164,\"text\":\"中国邮递员问题\"},\"children\":[]},{\"data\":{\"id\":\"b9kn8ymt4fsw\",\"created\":1482840955189,\"text\":\"货郎担问题\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-pink\",\"version\":\"1.4.33\"}","fileGuid":"97b8f01619f86b3614c0a57d21097ec0","csrf_token":"cdfb52c4ab5136373d2c7af9030b9174"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Request"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by zhangbobell** [comment]
这个问题是由于我们服务器不稳定，确实是属于偶发性的问题，具体原因我们正在排查，刷新页面就好了，不会对数据造成任何影响，我们将在未来持续改进该问题。
