### ISSUE TITLE
脑图报错反馈

### ISSUE THREAD

**Issue by lizhengnacl** [fex-team/kityminder-editor#360]
错误
 {"data":null,"status":-1,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"da20e0d38843e14dfa9f55e40f553402","csrf_token":"6e94daeb7539afc708ecc4dbfe6d7eac"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":""}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by zhangbobell** [comment]
错误 -1 问题一般是由于网络状况差导致的，换个网络状况好的地方刷新一下就好了。
