### ISSUE TITLE
时常崩溃

### ISSUE THREAD

**Issue by TianYongwei** [fex-team/kityminder-editor#378]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>发生了一个数据库错误</h1>\n\t\t<p>使用给出的设置无法连接数据库.</p><p>Filename: core/Loader.php</p><p>Line Number: 346</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/touch","data":{"fileName":"新建脑图","parentGuid":"b647dded510ac0fda78de872545e2d31","template":"default","version":"1.4.37","csrf_token":"849524a1aa23d8b86fb48fbd0ea953f8"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by TianYongwei** [comment]
是我造作频率太高了么

**Comment by TianYongwei** [comment]
错误
 {"data":"<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","status":400,"config":{"method":"POST","transformResponse":[null],"url":"bos/rename","data":{"newName":"JavaScript","selectedFileGuids":"b29371c9cea2d53139bd30cd76f424a0","csrf_token":"849524a1aa23d8b86fb48fbd0ea953f8"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Request"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by althe** [comment]
我出现了跟你一样的情况
