### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by cuttino001** [fex-team/kityminder-editor#379]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>发生了一个数据库错误</h1>\n\t\t<p>使用给出的设置无法连接数据库.</p><p>Filename: core/Loader.php</p><p>Line Number: 346</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"607c453748d8\",\"created\":1450145532,\"text\":\"新人入职\"},\"children\":[{\"data\":{\"id\":\"bbqp5xcseu80\",\"created\":1490768036154,\"text\":\"熟悉项目\"},\"children\":[]},{\"data\":{\"id\":\"bbqp6lwj4u80\",\"created\":1490768089591,\"text\":\"熟悉代码\"},\"children\":[]},{\"data\":{\"id\":\"bbqp6rvsqow0\",\"created\":1490768102607,\"text\":\"了解规范\"},\"children\":[{\"data\":{\"id\":\"bbqp73to73c0\",\"created\":1490768128600,\"text\":\"PMS 禅道\"},\"children\":[]},{\"data\":{\"id\":\"bbqp74zx1880\",\"created\":1490768131154,\"text\":\"周报\"},\"children\":[]},{\"data\":{\"id\":\"bbqp7q2oqi00\",\"created\":1490768177034,\"text\":\"分支\"},\"children\":[]},{\"data\":{\"id\":\"bbqp7yo6d0g0\",\"created\":1490768195748,\"text\":\"开发流程\"},\"children\":[]},{\"data\":{\"id\":\"bbqp83frg2o0\",\"created\":1490768206123,\"text\":\"提测\"},\"children\":[]},{\"data\":{\"id\":\"bbqp84xw8000\",\"created\":1490768209396,\"text\":\"生产bug处理\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.37\"}","fileGuid":"c79b55db8ead333d45c9172ea1a16338","csrf_token":"1d0047c8aa0a64a3f973e805efb673fa"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by zhangbobell** [comment]
从运维那边反馈得到的消息，是下午整个集群出了点故障，现在已经恢复了，如果从现在开始，仍然出现 500, 503 等错误，请说明。
