### ISSUE TITLE
脑图页面提示出错了，错误码500，详细信息如下

### ISSUE THREAD

**Issue by ruantongtong** [fex-team/kityminder-editor#380]
错误
 {"data":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":504,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"8bfbc9576f75\",\"created\":1490694317,\"text\":\"工作记录\"},\"children\":[{\"data\":{\"id\":\"bbpz1gf0chs0\",\"created\":1490694336969,\"text\":\"2017\"},\"children\":[{\"data\":{\"id\":\"bbpz1iku3kwk\",\"created\":1490694341675,\"text\":\"3月\"},\"children\":[{\"data\":{\"id\":\"bbpz1l505yww\",\"created\":1490694347248,\"text\":\"第4周\"},\"children\":[{\"data\":{\"id\":\"bbpz1pweegw0\",\"created\":1490694357611,\"text\":\"周2\"},\"children\":[{\"data\":{\"id\":\"bbpz28rsgtko\",\"created\":1490694398692,\"text\":\"1、临时停运时限设置需求，整理为脑图，方便理解\"},\"children\":[]},{\"data\":{\"id\":\"bbpz301b994c\",\"created\":1490694458040,\"text\":\"2、与刘聪对所写测试点进行review，并向她学习相关业务及工作流程\"},\"children\":[]},{\"data\":{\"id\":\"bbpz3mlhhsg8\",\"created\":1490694507149,\"text\":\"3、尝试编写部分测试case\"},\"children\":[]}]},{\"data\":{\"id\":\"bbqqrakxrm04\",\"created\":1490772531702,\"text\":\"周3\"},\"children\":[{\"data\":{\"id\":\"bbqqrfhwjdkc\",\"created\":1490772542404,\"text\":\"1、编写临时停运设置需求case，完成了司机变动原因设置相关case的编写\"},\"children\":[]},{\"data\":{\"id\":\"bbqqs3yb5i0c\",\"created\":1490772595638,\"text\":\"2、测试”接机礼宾账号信息“提测任务\"},\"children\":[]}]}]}]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.37\"}","fileGuid":"689e8a16ca0266770d3ee63a9501e21e","csrf_token":"4b5f09f2e3df7032492f1dbd2932287b"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Gateway Time-out"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 BIDUBrowser/8.7 Safari/537.36

**Comment by cuttino001** [comment]
现在一直是503错误

**Comment by cuttino001** [comment]
现在一直是503错误

**Comment by zhangbobell** [comment]
从运维那边反馈得到的消息，是下午整个集群出了点故障，现在已经恢复了，如果从现在开始，仍然出现 500, 503 等错误，请说明。
