### ISSUE TITLE
页面弹窗 500

### ISSUE THREAD

**Issue by Farb** [fex-team/kityminder-editor#381]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>发生了一个数据库错误</h1>\n\t\t<p>使用给出的设置无法连接数据库.</p><p>Filename: core/Loader.php</p><p>Line Number: 346</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"cdbe1d83935a\",\"created\":1490775505,\"text\":\"存储系统文件目录文档说明\"},\"children\":[{\"data\":{\"id\":\"bbqru5kd2tk4\",\"created\":1490775576986,\"text\":\"Schedule\"},\"children\":[]},{\"data\":{\"id\":\"bbqruk35dpcg\",\"created\":1490775608597,\"text\":\"PrivateDataResource\"},\"children\":[]},{\"data\":{\"id\":\"bbqrvcozzc0k\",\"created\":1490775670868,\"text\":\"Img\"},\"children\":[]},{\"data\":{\"id\":\"bbqrvk9cugw0\",\"created\":1490775687337,\"text\":\"UEditor\"},\"children\":[]},{\"data\":{\"id\":\"bbqrvpw930o4\",\"created\":1490775699605,\"text\":\"分支主题\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.37\"}","fileGuid":"3d31cc7a743eabdd4eb5d3eaa82f5d7a","csrf_token":"0c9f31ad973a87ca000feb723d918b75"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by zhangbobell** [comment]
从运维那边反馈得到的消息，是下午整个集群出了点故障，现在已经恢复了，如果从现在开始，仍然出现 500, 503 等错误，请说明。
