### ISSUE TITLE
在脑图中如何删除不要的历史

### ISSUE THREAD

**Issue by huoxudong125** [fex-team/kityminder-editor#394]
自动保存，会导致同一时间里在两个标签页打开的同一文档状态不一致，且是以最后一次切换到标签页为主，而不是以最后修改的标签页为主。
希望增加一个删除不需要的历史记录的按钮

**Comment by zhangbobell** [comment]
直接 Ctrl + s 手动同步到云端，直接覆盖即可。

**Comment by huoxudong125** [comment]
@zhangbobell 多谢
