### ISSUE TITLE
当我保存脑图文件时报错 

### ISSUE THREAD

**Issue by althe** [fex-team/kityminder-editor#398]
错误
 {"data":"read tcp 192.168.10.100:60080->123.125.112.229:80: i/o timeout","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"96462cac50c2\",\"created\":1492431702,\"text\":\"mxonline\"},\"children\":[{\"data\":{\"id\":\"bc72xa5ut7s0\",\"created\":1492431813601,\"text\":\"users 用户管理\",\"layout_mind_offset\":{\"x\":-15,\"y\":-29},\"layout\":null},\"children\":[{\"data\":{\"id\":\"bc730c1begg0\",\"created\":1492432052773,\"text\":\"userProfile表\\nnick_name birthday gender\\naddress mobile image\",\"layout\":null,\"background\":\"#92d050\"},\"children\":[]},{\"data\":{\"id\":\"bc7fs063eow0\",\"created\":1492468074456,\"text\":\"EmailVerifyRcord表\\nEmail code send_type send_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bc7fsgis8tc0\",\"created\":1492468110051,\"text\":\"Banner表\\ntitle image url index add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bc7fuq2etwg0\",\"created\":1492468287558,\"text\":\"此2个相对独立的功能\\n不会和其他表产生import\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bc72xpuvkjk0\",\"created\":1492431847766,\"text\":\"course 课程管理\",\"layout_mind_offset\":{\"x\":-13,\"y\":1},\"layout\":null,\"note\":\"分析课程管理界面：①需要有张表来存储课程的基础信息。②课程下面有课程章节，是没有办法和课程信息表放到一起的，所以需要新建一张表来存放课程章节信息，和课程信息是一对多的关系。③每个章节又有若干的视频信息，所以需要一张新表存放章节视频信息，和章节是一对多关系，④还有个课程资源，和课程表是一对多关系。所以当前模块是三层结构。\"},\"children\":[{\"data\":{\"id\":\"bc8a3phr2fc0\",\"created\":1492553624883,\"text\":\"course表\\nname desc detail image\\nlearn_times degree students fav_nums\\nclick_nums add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bc8aoyl2m400\",\"created\":1492555290322,\"text\":\"Lesson表\\ncourse name learn_times add_time \",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bc8ari6s7bk0\",\"created\":1492555489722,\"text\":\"Video表\\nlesson name url learn_time add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bc8asn1bqyo0\",\"created\":1492555578640,\"text\":\"resource表\\ncourse name url add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bc72xzv3ecg0\",\"created\":1492431869547,\"text\":\"organization 机构和教师管理\",\"layout_mind_offset\":{\"x\":2,\"y\":-24},\"layout\":null,\"note\":\"因为教师是属于机构内的，\\n所以我们放到一起管理\",\"layout_fish-bone-master_offset\":{\"x\":-126,\"y\":0}},\"children\":[{\"data\":{\"id\":\"bcahbyw6nyo0\",\"created\":1492777139943,\"text\":\"courseOrg表\\nname city address fav_nums students \\nclick_nums add_time image\",\"layout\":null,\"background\":\"#92d050\"},\"children\":[]},{\"data\":{\"id\":\"bcahc8bwt8g0\",\"created\":1492777160485,\"text\":\"teacher表\\norg name work_years work_company\\nfav_num course_num click_num work_position\\npoints\",\"layout\":null,\"background\":\"#92d050\"},\"children\":[]},{\"data\":{\"id\":\"bcai8bs86600\",\"created\":1492779675655,\"text\":\"cityDict表\\ncity desc add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bc72yru4d480\",\"created\":1492431930438,\"text\":\"operation 用户操作管理\",\"layout_mind_offset\":{\"x\":-2,\"y\":19},\"layout\":null,\"note\":\"分层结构设计\\n可以很好的解决循环引用问题\",\"layout_fish-bone-master_offset\":{\"x\":-119,\"y\":1},\"priority\":1},\"children\":[{\"data\":{\"id\":\"bcaj2iavyaw0\",\"created\":1492782040769,\"text\":\"UserAsk表\\nname mobile course_name add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaj2oxjers0\",\"created\":1492782055199,\"text\":\"UserMessage表\\nuser message has_read add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaj2uyf8480\",\"created\":1492782068313,\"text\":\"UserCourse表\\nuser course add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaj32growg0\",\"created\":1492782084660,\"text\":\"UserFavorite表\\nuser fav_id fav_type add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaj3jmguvs0\",\"created\":1492782122010,\"text\":\"CourseComments表\\nuser course comments add_time\",\"background\":\"#92d050\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bcaxyin28gw0\",\"created\":1492824044697,\"text\":\"xadmin后台管理模块配置\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaxyy450xk0\",\"created\":1492824078381,\"text\":\"用户注册登陆功能实现\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcaxzx7tj2o0\",\"created\":1492824154791,\"text\":\"课程机构管理页面实现\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcay4r88rds0\",\"created\":1492824533577,\"text\":\"课程管理页面实现\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcay4zebolc0\",\"created\":1492824551359,\"text\":\"讲师管理页面实现\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcay5j06bao0\",\"created\":1492824594039,\"text\":\"个人中心和全局搜索功能实现\",\"progress\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bcay5ykz57c0\",\"created\":1492824627949,\"text\":\"首页细节以及全局404和403页面配置\",\"progress\":1,\"layout\":null},\"children\":[]}]},\"template\":\"fish-bone\",\"theme\":\"fresh-green\",\"version\":\"1.4.41\"}","fileGuid":"2accda229ae5b6668d601d112097ced4","csrf_token":"046802388de366c17542a6b03ed634b0"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by zhangbobell** [comment]
这个是后端服务不稳定造成的，属于偶发性的问题，不会影响到数据，刷新即可。另外，我们会通过升级迁移的方式进一步保证服务的稳定性。
