### ISSUE TITLE
另存为PNG点击无效

### ISSUE THREAD

**Issue by ysh329** [fex-team/kityminder-editor#404]
在Chrome和FireFox试了均无效，
其它另存为方式都可以

**Comment by zhangbobell** [comment]
能否提供一下无法导出 PNG 的脑图的分享链接地址以及你所使用的浏览器的具体版本信息？

**Comment by ysh329** [comment]
导出->PNG，点击没有反应
浏览器版本：Linux Chrmoe Version 58.0.3029.96 (64-bit)
脑图地址：http://naotu.baidu.com/file/121840729bbdbe4ec7d00c5336505cba

**Comment by zhangbobell** [comment]
这个地址我没有权限，能否提供一下「分享链接」地址？

**Comment by ysh329** [comment]
@zhangbobell 
不好意思，分享地址：
[点击这里](http://naotu.baidu.com/file/121840729bbdbe4ec7d00c5336505cba?token=c9a801309e3877be)

**Comment by zhangbobell** [comment]
你这个是因为图片来源于 csdn，CSDN 的图片服务器做了 CORS 限制，因此无法导出。你可以下载下来，手动上传到脑图的图片服务器。

**Comment by ysh329** [comment]
@zhangbobell 原来如此，十分感谢！ :laughing:
