### ISSUE TITLE
上传本地图片时，有时图片显示不出来

### ISSUE THREAD

**Issue by huangnuoen** [fex-team/kityminder-editor#407]
图片格式为png，上传多次都无法显示？

**Comment by zhangbobell** [comment]
该问题是否稳定出现？能否提供一下图片？

**Comment by huangnuoen** [comment]
昨天上传10张图片，出现了2 次上传不了的情况，其它图片可以成功上传，单单有2 张失败，但今天重试了该图已经成功上传。

**Comment by zhangbobell** [comment]
先关了 issue，如果仍有问题，可以再打开。
