### ISSUE TITLE
用户体验优化建议

### ISSUE THREAD

**Issue by Tasfa** [fex-team/kityminder-editor#413]
1、输入无法换行，比如想在一个方格中输入：
a
b
2、键盘右键，最好是判断用户节点没有展开时，先展开节点再选择

**Comment by zhangbobell** [comment]
1. shift + enter 换行
2. 键盘右键是什么键。

**Comment by Tasfa** [comment]
就是就是上下左右键

Tasfa

在 2017年6月6日，下午3:55，Bo Zhang <notifications@github.com<mailto:notifications@github.com>> 写道：


  1.  shift + enter 换行
  2.  键盘右键是什么键。

**Comment by zhangbobell** [comment]
右键展开的功能我们需要考虑后决定是否加入，因为这样会引起按键歧义。

**Comment by Tasfa** [comment]
可以加个判断啊，如果没有展开就展开，展开了的话就是移动

Tasfa

在 2017年6月9日，上午11:25，Bo Zhang <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #413<https://github.com/fex-team/kityminder-editor/issues/413>.

**Comment by Tasfa** [comment]
加一个判断，如果是未展开，那就按→键展开，如果是已经展开，那→的功能就是选择，这个也不会歧义


________________________________
发件人: Bo Zhang <notifications@github.com>
发送时间: 2017年6月9日 3:25
收件人: fex-team/kityminder-editor
抄送: Tasfa; Author
主题: Re: [fex-team/kityminder-editor] 用户体验优化建议 (#413)


右键展开的功能我们需要考虑后决定是否加入，因为这样会引起按键歧义。

―
