### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Oldify** [fex-team/kityminder-editor#415]
这是？？？
--------------

错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"50aba77c601d\",\"created\":1496991903,\"text\":\"探究“扩张边界”对城市发展的影响——基于俄勒冈州的双重差分估计结果\"},\"children\":[{\"data\":{\"id\":\"bdfzdnpf54ow\",\"created\":1496992010519,\"text\":\"摘要\",\"layout\":null,\"priority\":1},\"children\":[{\"data\":{\"id\":\"bdfze9lp42kg\",\"created\":1496992058183,\"text\":\"“扩张边界控制“是城市规划中的常用手段，本文利用俄勒冈州城市高精度GIS的DID结果对这一政策对于城市发展的影响进行探究。\",\"priority\":1,\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg19wa6a3uo\",\"created\":1496997357952,\"text\":\"结论\",\"priority\":2,\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdg1b7cpchz4\",\"created\":1496997460413,\"text\":\"UGB的存在限制了发展，因为UGB内外的发展速度不同\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg1beribzeo\",\"created\":1496997476546,\"text\":\"以往使用的横截面数据大多无法正确衡量UGB对发展的影响\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdfzfq8l7bi8\",\"created\":1496992172760,\"text\":\"多余内容\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdfzgbd6wt1c\",\"created\":1496992218751,\"text\":\"对于UGBs对城市发展（以房产市场为例）的影响，现有研究结果之间并不统一\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdfzrmgnirk0\",\"created\":1496993104911,\"text\":\"本文的数据为面板数据，这些数据代表了不随时间变化的变量和普遍存在的地图的临时效应？？？，因而可以减轻UGB内生而带来的影响\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg18tq1o7i8\",\"created\":1496997274017,\"text\":\"同时本文也在估计“随时间变化的因素”上运用了新的方法\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bdg1dpqe43cw\",\"created\":1496997657151,\"text\":\"文献综述\",\"layout\":null,\"priority\":2},\"children\":[{\"data\":{\"id\":\"bdg1g0t96osg\",\"created\":1496997837997,\"text\":\"Urban Growth  Boundaries (UGBs)在城市发展规划中越来越常用\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg1gvv5po1s\",\"created\":1496997905593,\"text\":\"衡量UGBs（对经济发展速度）的影响遇到的第一个挑战来自：两者之间存在联系。房价、城市化率、其他相关方面的收入等因素会影响城市规划者对UGBs位置的决策；然而房价等这些因素本身也受到UGBs的影响。\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdgl8ut4o16o\",\"created\":1497053698578,\"text\":\"随后有研究利用了工具变量法和quasi-experiment方法处理了ugbs和地价的内生问题\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdglly9rc740\",\"created\":1497054724848,\"text\":\"也有人利用好rdd方法处理了这一内生性\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdglnbe9u6tc\",\"created\":1497054831783,\"text\":\"关于企业空间EZ的研究也遇到了空间地理位置非随机分布的问题\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdgloawgvsow\",\"created\":1497054909071,\"text\":\"Oregon的ugbs的目的在于限制而非停止城市的发展\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdgloux45c74\",\"created\":1497054952646,\"text\":\"但ugbs外的土地也会存在发展，比如ugbs落地前的土地规划，以及农用地森林用地的发展\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdglqt2xjke8\",\"created\":1497055105372,\"text\":\"本文研究的三个特点：选取直接的指标，高精度数据与准自然实验，DID分析\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdgmlvoqwa9s\",\"created\":1497057540334,\"text\":\"研究政策背景\",\"layout\":null,\"priority\":2},\"children\":[{\"data\":{\"id\":\"bdgmnov1t4w0\",\"created\":1497057682206,\"text\":\"参议会Bill 10（1969）要求所有城市建立完善的土地使用规划及目标；Bill 100（1973）指出了Bill 10的不足之处，并建立了土地保护及发展委员会（LCDC），并且建立了土地使用种类目录\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhfouonb08w\",\"created\":1497139585431,\"text\":\"UGBs出现于1973年，但直到1974年政府文件中才出现“UGBS”的字样，且没有相关规定跟进\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdg1dtj2oo3k\",\"created\":1496997665416,\"text\":\"数据来源、样本概况和变量构建\",\"layout\":null,\"priority\":3},\"children\":[{\"data\":{\"id\":\"bdhghs381z40\",\"created\":1497141852343,\"text\":\"俄勒冈州位于美国西海岸，加州之北，华盛顿州之南；超过70%的人口聚集在威拉美特河谷地带；该河谷也是著名的葡萄酒产区\",\"layout\":null,\"image\":\"\",\"imageTitle\":\"\",\"imageSize\":\"\"},\"children\":[{\"data\":{\"id\":\"bdhgn3ljd2ww\",\"created\":1497142269216,\"text\":\"图1\",\"image\":\"http://kityminder-img.gz.bcebos.com/69bdbdb840d0a6befaf9789359efe9651ef33346\",\"imageTitle\":\"威拉美特河谷在俄勒冈州的位置\",\"imageSize\":{\"width\":200,\"height\":149},\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgnikxhqf4\",\"created\":1497142301831,\"text\":\"图2\",\"image\":\"http://kityminder-img.gz.bcebos.com/9df49be781efd727dc1082a2ae5349528974b900\",\"imageTitle\":\"威拉美特河谷概况\",\"imageSize\":{\"width\":147,\"height\":200},\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdhfsexxqnls\",\"created\":1497139864621,\"text\":\"Table 1中展示了数据库中包含的主要指标，包括：土地（是否被）使用（Land Development）、UGBs位置（1980-2000）、土地所有权类型、海拔、坡度、土壤质量、距高速路的距离、距市中心距离、距城市边界（city boundaries）距离\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhfw2f9eznk\",\"created\":1497140150827,\"text\":\"数据类型：均为时间序列数据\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhfw70n8zr4\",\"created\":1497140160827,\"text\":\"土地使用类型的划分方法：将区域内土地分成0.36公顷的方块，按照Anderson Level I System对土地类型进行划分\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhg3na2adj4\",\"created\":1497140744774,\"text\":\"Developed Land\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhg4t3ax98g\",\"created\":1497140835790,\"text\":\"Areas of intensive use with much of the land covered with structures or anthropogenic impervious surfaces (e.g., high-density residential, commercial, industrial, roads, etc.)\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhg5698f5s0\",\"created\":1497140864447,\"text\":\"or less intensive uses where the land cover matrix includes both vegetation and structures (e.g., low-density residential, recreational facilities, cemeteries, parking lots, utility corridors, etc.)\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhg65z3vuo0\",\"created\":1497140942199,\"text\":\"including any land functionally related to urban or built-up environments (e.g., parks, golf courses, etc.)\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bdhg7ch83vgg\",\"created\":1497141034719,\"text\":\"Non-Developed Land\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhg7jjiqb5s\",\"created\":1497141050095,\"text\":\"agriculture, grassland/shrub land, forest, wetland, mining, barren, ice/snow, water,\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhg81nrr7k0\",\"created\":1497141089535,\"text\":\"mechanically disturbed and non-mechanically disturbed\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhg8inooq9s\",\"created\":1497141126535,\"text\":\"In the western U.S., the last two categories are predominately associated with forest harvesting and wildfire (Sleeter et al., 2012). In the data we use for estimation, only 0.3% of our plots are classified as mechanically or non-mechanically disturbed\",\"layout\":null},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bdhgabrh8934\",\"created\":1497141268255,\"text\":\"LCT数据库\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhgare1rpc0\",\"created\":1497141302271,\"text\":\"以100平方千米为尺度将土地分成blocks\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgc1vnnojk\",\"created\":1497141403468,\"text\":\"LCT数据库中29%的blocks位于Willamette河谷中\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgb8hzun0g\",\"created\":1497141339515,\"text\":\"将每个blocks分为0.36公顷的plots，每个blocks中凭借包含大致28000个plots\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdhgjwq0bvuo\",\"created\":1497142019156,\"text\":\"DLCD数据库反映了1980-2000年来UGBs位置的变化\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhgpb3b7if4\",\"created\":1497142442256,\"text\":\"LCT和DLCD数据库交叠后的结果\",\"image\":\"http://kityminder-img.gz.bcebos.com/4785ef1875b313fe09878762fb7d7d7d99c5343a\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":102},\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgq0hj8qv4\",\"created\":1497142497536,\"text\":\"为了更好地观察UGBs对土地的影响，距离UGBs超过2km的地块被排除\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgr7hv5vk0\",\"created\":1497142591157,\"text\":\"UGBs的主要目的在于影响私人土地所有者的开发决策，因此排除了“2km带”之内的公有土地，包括被公共设施占用的私人土地（如道路）等。\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgskfd2ku8\",\"created\":1497142697668,\"text\":\"水域、湿地由于开发难度较大，排除\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdhgt0zcc6ps\",\"created\":1497142733705,\"text\":\"为了更好地控制变量，在“土地利用”指标之外，还考虑了土壤质量、坡度、海拔、distances to the closest state-owned highway, city center, city limit.\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bdhgwiwn7zls\",\"created\":1497143007816,\"text\":\"城市发展：城市规模起先都很小，随后在人口数量、人均收入上都出现了明显的极差扩大的趋势\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhgz5dydr7k\",\"created\":1497143213481,\"text\":\"分支主题\",\"image\":\"http://kityminder-img.gz.bcebos.com/3733429894c8ae1abd696815fc172985575700f7\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":93}},\"children\":[]}]}]},{\"data\":{\"id\":\"bdg1ecdhle68\",\"created\":1496997706437,\"text\":\"基本计量模型表达式\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bdhh8j7chn9c\",\"created\":1497143948833,\"text\":\"We assume that the relationship between the outcome (development), Yit={0,1}, and the treatment (location within the UGB), Gi={0,1}, is given by\",\"priority\":1},\"children\":[{\"data\":{\"id\":\"bdhh9ctv6d4w\",\"created\":1497144013322,\"text\":\"Eq.1\",\"image\":\"http://kityminder-img.gz.bcebos.com/4291f7aca0367743c73b6a594803f4929a300015\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":32}},\"children\":[{\"data\":{\"id\":\"bdhhaljd8u0w\",\"created\":1497144110642,\"text\":\"下标I代表区块，下标t代表时间；T为哑变量，T=0表示在UGB建立（1973年）之前，T=1表示在UGB建立（2000年）之后\"},\"children\":[]},{\"data\":{\"id\":\"bdhhdhczoqo0\",\"created\":1497144336642,\"text\":\"Xit代表除了控制变量之外make land development more or less profitable的其余协变量，如proximity to the city center, 发展成本、returns to the land in non-developed uses\"},\"children\":[]},{\"data\":{\"id\":\"bdhhglyfderk\",\"created\":1497144581738,\"text\":\"此模型只讨论距离UGBs05km之内的plots，为了减少其他因素想断点回归一样对因变量的影响。\"},\"children\":[]},{\"data\":{\"id\":\"bdhhjjqpbqbk\",\"created\":1497144812010,\"text\":\"γ=0时，我们得到了基本的双重差分（DID）模型\"},\"children\":[]},{\"data\":{\"id\":\"bdhi3hsayi9s\",\"created\":1497146375036,\"text\":\"平均实验效果ATE的衡量。其中G代表土地是否treated，T代表在treatment之前还是之后\"},\"children\":[{\"data\":{\"id\":\"bdhi3msekbnk\",\"created\":1497146385926,\"text\":\"Eq.2\",\"image\":\"http://kityminder-img.gz.bcebos.com/bfa495967cdc57824f017f99756622c2a14d82ab\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":31}},\"children\":[]},{\"data\":{\"id\":\"bdhn2kdbperk\",\"created\":1497160407846,\"text\":\"采用ATE\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bdg1ei3bmrcw\",\"created\":1496997718883,\"text\":\"实证结果\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg1emy0t0jk\",\"created\":1496997729447,\"text\":\"结论\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bdg1enyo89hc\",\"created\":1496997731663,\"text\":\"学习心得\",\"layout\":null},\"children\":[]}]},\"template\":\"default\",\"theme\":\"snow\",\"version\":\"1.4.43\"}","fileGuid":"7058c5c54785ba7e34f6364dd898f91d","csrf_token":"9731bde9e72814ec604be4f2fd9f62b9"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; InfoPath.2; rv:11.0) like Gecko

**Comment by zhangbobell** [comment]
你好，503 错误是服务器故障，正在联系运维部门同事解决。感谢反馈！
