### ISSUE TITLE
建议：不同主题之间增加关联

### ISSUE THREAD

**Issue by Yaoomingtal** [fex-team/kityminder-editor#422]
## 最近在复习期末

- 平时节点不是非常多不明显，当对书本进行细化整理时，发现好多知识点是联系起来的
- 不能添加联系，强迫症表示非常不爽

## 建议
增加不同节点之间的关联

- 可用类似HTML中a标签实现的页面内跳转的思路，在本节点处添加类似 Flag 的东西，弹出一个需要相关联的节点的 List（可用细化目录的方式，如类似markdown的多级Header），链接到对应的节点

- 近距离的话，同属于某个 2级或者3级目录下的节点，可使用连线进行link。从左侧或者右侧的大块空白画线进行链接

**Comment by zhangbobell** [comment]
duplicate with #9
