### ISSUE TITLE
【新功能】实现自动调节思维导图的紧凑疏松是否方便呢

### ISSUE THREAD

**Issue by liaojieliang** [fex-team/kityminder-editor#426]
hi，

我在使用时想到这个问题，有时候整个思维导图各个层级不是很均衡，有时候层级比较多，连接线太长的话可见显示区域就放不下整个图了。如果可以调节连接线长短使得整个思维导图变紧凑那就会很棒。

**Comment by zhangbobell** [comment]
你可以使用「紧凑型」的主题，选中之后，连线就变短了。

**Comment by liaojieliang** [comment]
哦哦，不错！感谢提醒。
