### ISSUE TITLE
页面自动保存时弹框报错

### ISSUE THREAD

**Issue by Bubble2** [fex-team/kityminder-editor#432]
错误
 {"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n<HTML><HEAD><TITLE>错误消息</TITLE>\r\n<META http-equiv=Content-Type content=\"text/html; charset=UTF-8\">\r\n<STYLE id=L_10060_1>A {\r\n\tFONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: 宋体, tahoma\r\n}\r\nA:hover {\r\n\tFONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: 宋体, tahoma\r\n}\r\nTD {\r\n\tFONT-SIZE: 9pt; FONT-FAMILY: 宋体, tahoma\r\n}\r\nTD.titleBorder {\r\n\tBORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: 宋体, tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left\r\n}\r\nTD.titleBorderx {\r\n\tBORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: 宋体, tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left\r\n}\r\n.TitleDescription {\r\n\tFONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: 宋体, tahoma\r\n}\r\nSPAN.explain {\r\n\tFONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225\r\n}\r\nSPAN.TryThings {\r\n\tFONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225\r\n}\r\n.TryList {\r\n\tMARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: 宋体, tahoma\r\n}\r\n.X {\r\n\tBORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: 宋体, verdana; BACKGROUND-COLOR: #d1c2b4\r\n}\r\n.adminList {\r\n\tMARGIN-TOP: 2px\r\n}\r\n</STYLE>\r\n<META content=\"MSHTML 6.00.2800.1170\" name=GENERATOR></HEAD>\r\n<BODY bgColor=#f3f3ed>\r\n<TABLE cellSpacing=0 cellPadding=0 width=\"100%\">\r\n  <TBODY>\r\n  <TR>\r\n    <TD class=titleBorderx width=30>\r\n      <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>\r\n        <TBODY>\r\n        <TR>\r\n          <TD id=L_10060_x class=x valign=middle align=center>X</TD>\r\n        </TR>\r\n        </TBODY>\r\n      </TABLE>\r\n    </TD>\r\n    <TD class=titleBorder id=L_10060_2>网络访问消息:<SPAN class=TitleDescription> 无法显示此页</SPAN> </TD>\r\n  </TR>\r\n  </TBODY>\r\n</TABLE>\r\n\r\n<TABLE id=spacer>\r\n  <TBODY>\r\n  <TR>\r\n    <TD height=10></TD></TR></TBODY></TABLE>\r\n<TABLE width=400>\r\n  <TBODY>\r\n  <TR>\r\n    <TD noWrap width=25></TD>\r\n    <TD width=400><SPAN class=explain><ID id=L_10060_3><B>解释:</B></ID></SPAN><ID id=L_10060_4> 在页面检索完成之前，请求超时。 </ID><BR><BR>\r\n    <B><SPAN class=tryThings><ID id=L_10060_5><B>尝试下列:</B></ID></SPAN></B> \r\n      <UL class=TryList>\r\n        <LI id=L_10060_6><B>刷新页:</B> 单击“刷新”按钮来再次搜索此页。超时可能是由于 Internet 拥塞造成的。\r\n<LI id=L_10060_7><B>检查拼写:</B> 请检查您是否正确键入了网页地址。键入的网页地址不正确。\r\n<LI id=L_10060_8><B>联系网站:</B> 您可能想要联系网站的管理员，以确认网页仍然存在。您可以使用网站主页上列出的电子邮件地址或电话号码与他们联系。\r\n\r\n      </UL>\r\n<ID id=L_10060_9>如果您仍然看不到请求的页面，请与您的管理员或支持人员联系。</ID> <BR><BR>\r\n    </TD>\r\n  </TR>\r\n  </TBODY>\r\n</TABLE>\r\n\r\n<TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>\r\n\r\n<TABLE width=400>\r\n  <TBODY>\r\n  <TR>\r\n    <TD noWrap width=25></TD>\r\n    <TD width=400 id=L_10060_10><B>技术信息(提供给支持人员)</B> \r\n      <UL class=adminList>\r\n        <LI id=L_10060_11>错误代码 10060: 连接超时\r\n<LI id=L_10060_12>背景信息: 网关不能从您要访问的网站接收到及时响应。这可能表明网络阻塞，或者该网站遇到技术困难。\r\n<LI id=L_10060_13>日期: 2017/6/30 6:09:54 [GMT]\r\n<LI id=L_10060_14>服务器: tmg2.focuschina.com\r\n<LI id=L_10060_15>源: 防火墙\r\n\r\n      </UL>\r\n    </TD>\r\n  </TR>\r\n  </TBODY>\r\n</TABLE>\r\n\r\n</BODY>\r\n</HTML>\r\n\r\n","status":504,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"aa3646cef587\",\"created\":1498793820,\"text\":\"转岗心得分享\"},\"children\":[{\"data\":{\"id\":\"bdxqb5zc6ew0\",\"created\":1498794504439,\"text\":\"动机、目的\",\"priority\":1},\"children\":[{\"data\":{\"id\":\"bdxqclrq0so0\",\"created\":1498794617172,\"text\":\"最初的动机是什么？\"},\"children\":[{\"data\":{\"id\":\"bdxt3ybmeog0\",\"created\":1498802402548,\"text\":\"可以去写js了，切图太乏味了\"},\"children\":[]},{\"data\":{\"id\":\"bdxt4lmgir40\",\"created\":1498802453270,\"text\":\"技多不压身，多学点以后找工作好找\"},\"children\":[]},{\"data\":{\"id\":\"bdxt5bpycp40\",\"created\":1498802510077,\"text\":\"前端行业发展趋势，小前端到大前端\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bdxqe45e7mw0\",\"created\":1498794735545,\"text\":\"行动、过程\",\"priority\":2},\"children\":[{\"data\":{\"id\":\"bdxta5anrq00\",\"created\":1498802887913,\"text\":\"工作内容\"},\"children\":[{\"data\":{\"id\":\"bdxtayu5e740\",\"created\":1498802952218,\"text\":\"html、css\"},\"children\":[]}]},{\"data\":{\"id\":\"bdxtap488ig0\",\"created\":1498802931060,\"text\":\"工作环境\"},\"children\":[]}]},{\"data\":{\"id\":\"bdxqfktgrzk0\",\"created\":1498794850193,\"text\":\"心得、体会\",\"priority\":3},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"a36badbf045e7bf1305cf3a1f24ec1c4","csrf_token":"49339b835337ac6eef0441e202017e4c"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Proxy Timeout ( è¿æ¥è¶æ¶ã )"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by zhangbobell** [comment]
看错误信息像是你所在的内部网络拦截了网络请求，建议联系你的网络管理员进行处理。
