### ISSUE TITLE
错误-1

### ISSUE THREAD

**Issue by zhihuiting** [fex-team/kityminder-editor#434]
错误
 {"data":null,"status":-1,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"71c68d4645ffdec641aab9530cd52623","csrf_token":"49801d79b6682e72fc3edc9e15a3c5fb"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":""}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by zhangbobell** [comment]
-1 错误一般是由于你所在的网络和百度脑图服务器之间的通信不稳定造成的，一般刷新就好，属于偶发性的问题，不会影响到数据。
