### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ConGorz** [fex-team/kityminder-editor#435]
错误
 http://naotu.baidu.com/?p=p
行号：1
错误信息：Uncaught SyntaxError: Unexpected token <
列号：1
错误对象：SyntaxError: Unexpected token <

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36

**Comment by zhangbobell** [comment]
duplicate with #431
