### ISSUE TITLE
错误400

### ISSUE THREAD

**Issue by zhihuiting** [fex-team/kityminder-editor#442]
错误
 {"data":"","status":400,"config":{"method":"POST","transformResponse":[null],"url":"bos/open","data":{"fileGuid":"93d95b8ee02098b7c6c7172e97a3e1c6","csrf_token":"a4750d280fbd7304f4c3a86146f40c87"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Request"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by zhangbobell** [comment]
400 错误是由于你的网络环境不稳定，请使用更稳定的网络进行操作。
