### ISSUE TITLE
Error: 502 Bad Gateway

### ISSUE THREAD

**Issue by icnwyl** [fex-team/kityminder-editor#445]
中英文都不行，多试几次报错如下
错误
 {"data":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":502,"config":{"method":"POST","transformResponse":[null],"url":"bos/rename","data":{"newName":"aaa","selectedFileGuids":"4640b94b679b17bdcbee63291fae707e","csrf_token":"34a4a6ca68656ed09b78ab549894f252"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Gateway"}

浏览器信息：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
502 错误是由于访问人数太多，服务器负载过大造成的。我们后续会通过服务器迁移的方式升级。

**Comment by icnwyl** [comment]
502是我试多了以后偶然遇到的，不是我主要面对的问题，我的问题还是创建了node后没法输入名字
现在发现和ibus输入法也有关，不知道谁的问题，把信息贴这里以供参考
ubuntu 16.04
ibus 1.5.11
Chrome 59
创建node输入名称后按回车，输入框内容自动清空，导致新node名称都是空的，FF就没问题
临时解决办法，输入完成后先切换ibus输入法到英文，再按回车，成功保存

**Comment by zhangbobell** [comment]
已经通过扩容解决，如果仍然有 502 错误，请反馈，谢谢。输入法的问题，已经新开一个 issue，请在新的 issue 下参与讨论 #486
