### ISSUE TITLE
502

### ISSUE THREAD

**Issue by zymkoko** [fex-team/kityminder-editor#446]
错误
 {"data":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":502,"config":{"method":"POST","transformResponse":[null],"url":"bos/get_root_dir","data":{"csrf_token":"976d973793cf9fbe276ebdb960039852"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Gateway"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
duplicate with #445
