### ISSUE TITLE
用户登录后无法实际退出

### ISSUE THREAD

**Issue by sailorhzr** [fex-team/kityminder-editor#448]
2个问题：
问题一：同一浏览器中，用户A登录后退出，跳转到贴吧的404页面。退出页面似乎不对吧。
问题二：通过贴吧404页面下的跳转，调整到贴吧首页后，退出当前用户A。使用用户B的百度账号登录，通过百度首页的所有产品下拉菜单访问脑图，无需再次输入用户名、密码。用户B可以直接访问之前用户A的脑图

**Comment by zhangbobell** [comment]
该问题已经解决，请确认一下，如果仍然存在，欢迎继续反馈。
