### ISSUE TITLE
保存出错

### ISSUE THREAD

**Issue by nothing0here** [fex-team/kityminder-editor#450]
错误
 {"data":"","status":400,"config":{"method":"POST","transformResponse":[null],"url":"bos/rename","data":{"newName":"Home","selectedFileGuids":"5ca37a3901fe23c68a42ba398c1aa565","csrf_token":"e0a2eb32417d2750277e5af5f9296603"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Bad Request"}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by zhangbobell** [comment]
400 错误是你所在的网络不稳定造成的，请使用更稳定的网络环境。
