### ISSUE TITLE
按住Alt键拖动时如果点击到某个主题，脑图会变成拖动模式的问题

### ISSUE THREAD

**Issue by GengDaPeng** [fex-team/kityminder-editor#451]
当按住Alt键用鼠标拖动的时候，如果点到了某个主题，鼠标会选中它，并且脑图会切换到拖动模式。也就是说松开Alt键并不能回到正常的模式，而是还会留在拖动模式里，鼠标的形状变成了“拖动小手”。需要点击侧边的十字才能取消脑图的拖动模式。大概就是这样，如果描述不清请自行探索理解。最终想要的效果就是，按住Alt键拖动时，鼠标只能拖动页面，松开Alt键就回到不可拖动状态。以上（话说我终于找到了四种问题反馈方法，我说过我会一个一个试的  不知道你们是否知道我是谁）

**Comment by zhangbobell** [comment]
提供一下该问题的复现步骤，以及你使用的浏览器的详细版本信息。

**Comment by lusn45010** [comment]
这个问题有解决吗？需要升级新版本的kityminder？
