### ISSUE TITLE
脑图崩溃

### ISSUE THREAD

**Issue by wangaiyun** [fex-team/kityminder-editor#454]
{"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/touch","data":{"fileName":"视频互选插播广告副本","parentGuid":"beaa8cce794e63f349dc89295279be8e","template":"","version":"1.4.43","csrf_token":"5376ee2472fe87bbda587a3857cee827"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
503 错误是服务器压力过大造成的，已经通过扩容解决，如果仍然有 503 错误弹出，请反馈，谢谢。
