### ISSUE TITLE
今天使用时出错,不能新建脑图,贴上log

### ISSUE THREAD

**Issue by williamnie** [fex-team/kityminder-editor#455]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/touch","data":{"fileName":"新建脑图","parentGuid":"a20f36efb5fe72f9bc46bc9850d45916","template":"default","version":"1.4.43","csrf_token":"a26808cfa5edc99d857ca82148ba0cf9"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Crosswalk/18.46.461.0 Safari/537.36

**Comment by zhangbobell** [comment]
503 错误是服务器压力过大造成的，已经通过扩容解决，如果仍然有 503 错误弹出，请反馈，谢谢。
