### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by 979771154** [fex-team/kityminder-editor#457]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"809d2767fdb5\",\"created\":1479710422,\"text\":\"描述统计学：表格法和图形法\"},\"children\":[{\"data\":{\"id\":\"bepb1gewq74g\",\"created\":1501595105646,\"text\":\"前言\"},\"children\":[{\"data\":{\"id\":\"bepb1ogxsiog\",\"created\":1501595123182,\"text\":\"分类型数据 \"},\"children\":[]},{\"data\":{\"id\":\"bepb22d9hhk4\",\"created\":1501595153435,\"text\":\"数量型数据\"},\"children\":[]},{\"data\":{\"id\":\"bepb24a4fsw0\",\"created\":1501595157599,\"text\":\"数据可视化\"},\"children\":[{\"data\":{\"id\":\"bepb2a4h4hcs\",\"created\":1501595170318,\"text\":\" 常常用于描述汇总和表述一个数据集信息的图形显示的效用\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepbaj03ol4w\",\"created\":1501595816558,\"text\":\"汇总分类变量的数据\"},\"children\":[{\"data\":{\"id\":\"bepb36hfbns4\",\"created\":1501595240758,\"text\":\"频数分布\"},\"children\":[{\"data\":{\"id\":\"bepb3lytwgwg\",\"created\":1501595274462,\"text\":\" 频数分布\",\"note\":\"是表格\",\"priority\":null,\"progress\":9},\"children\":[{\"data\":{\"id\":\"bepb3zuosmos\",\"created\":1501595304687,\"text\":\" 是一种数据的表格汇总，表示在几个互不重叠组别中的每一个项目的个数即频数\"},\"children\":[]}]},{\"data\":{\"id\":\"bepb7errmvsc\",\"created\":1501595572254,\"text\":\"相对频数分布\",\"note\":\"也是表格形式\",\"priority\":null,\"progress\":9,\"layout_right_offset\":{\"x\":1,\"y\":-3}},\"children\":[{\"data\":{\"id\":\"bepb7t201e04\",\"created\":1501595603348,\"text\":\"相对频数=组的频数/n\"},\"children\":[]}]},{\"data\":{\"id\":\"bepb8k114e0w\",\"created\":1501595662062,\"text\":\"百分数频数分布\"},\"children\":[{\"data\":{\"id\":\"bepb8wsp5ewo\",\"created\":1501595689857,\"text\":\"百分数频数分布=组的频数*100/n\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepbb63ntn48\",\"created\":1501595866839,\"text\":\"条形图和饼形图\"},\"children\":[{\"data\":{\"id\":\"bepbb9un01s0\",\"created\":1501595875000,\"text\":\"条形图\"},\"children\":[{\"data\":{\"id\":\"bepbbcj4txc0\",\"created\":1501595880835,\"text\":\"用来描绘已汇总的分类型数据的频数分布、相对频数分布、百分数频数分布\",\"layout_right_offset\":{\"x\":-7,\"y\":1},\"color\":\"black\",\"progress\":null},\"children\":[]}]},{\"data\":{\"id\":\"bepbe8yk26o8\",\"created\":1501596108153,\"text\":\"饼形图\"},\"children\":[{\"data\":{\"id\":\"bepbebl4ilcg\",\"created\":1501596113871,\"text\":\"同条形图的作用一样，每组所占面积=相对频数*360\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bepbfgv4o8w0\",\"created\":1501596203724,\"text\":\"数量型数据汇总\"},\"children\":[{\"data\":{\"id\":\"bepbflnde9cs\",\"created\":1501596214139,\"text\":\"频数分布\"},\"children\":[{\"data\":{\"id\":\"bepbfrrgyygw\",\"created\":1501596227448,\"text\":\"组数 \"},\"children\":[{\"data\":{\"id\":\"bepbgm0zp5sg\",\"created\":1501596293327,\"text\":\"组是通过对数据规定范围而形成的，这个规定的范围用于对数据进行分组\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbfvplv8gk\",\"created\":1501596236042,\"text\":\"组宽\"},\"children\":[{\"data\":{\"id\":\"bepbh1d26884\",\"created\":1501596326708,\"text\":\"每组组宽相同，近似组宽=（数据最大值-数据最小值）/组数；若近似组宽为9.34，则可取10\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbfzyk6eww\",\"created\":1501596245291,\"text\":\"组限\",\"note\":\"相邻两组的下组限之差就是组宽\\n\",\"progress\":9},\"children\":[{\"data\":{\"id\":\"bepbiw5r9wgk\",\"created\":1501596472111,\"text\":\"选择组限必须使每一个数值属于且只属于一组，下组限定义为被分到该组的最小可能的数据值，上组限则为被分到该组的最大可能的数据值\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbg6t9dlsk\",\"created\":1501596260208,\"text\":\"组中值\"},\"children\":[{\"data\":{\"id\":\"bepbkeoztts0\",\"created\":1501596590822,\"text\":\"上组限和下组限的中间值\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepbm5n8m5ck\",\"created\":1501596727852,\"text\":\"相对频数分布、和百分数频数分布\"},\"children\":[]},{\"data\":{\"id\":\"bepbm8fwvwg0\",\"created\":1501596733939,\"text\":\"打点图\"},\"children\":[{\"data\":{\"id\":\"bepbmyrqdx4w\",\"created\":1501596791250,\"text\":\"是一种最简单的数据图形汇总方式，横轴是数据的值域，每一个数据值用横轴上的点表示\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbq0tycco4\",\"created\":1501597030830,\"text\":\"直方图\"},\"children\":[{\"data\":{\"id\":\"bepbq5sqt7cc\",\"created\":1501597041641,\"text\":\"一种常用的描述数量型数据的图形描述方式，直方图是相互连接的\"},\"children\":[{\"data\":{\"id\":\"bepbrz934vsw\",\"created\":1501597184120,\"text\":\"图形的尾部向左延伸些，则图形左偏\"},\"children\":[{\"data\":{\"id\":\"bepbtb8epm8s\",\"created\":1501597288565,\"text\":\"考试成绩的直方图是这种直方图的典型应用\",\"progress\":9},\"children\":[]}]},{\"data\":{\"id\":\"bepbsj1kb34g\",\"created\":1501597227201,\"text\":\"图形尾部向右延伸些，则图形右偏\"},\"children\":[{\"data\":{\"id\":\"bepbtm9tsnc4\",\"created\":1501597312595,\"text\":\"房屋的价格、工资、销售量常常导致直方图右偏\",\"progress\":9},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bepbuh2p8iok\",\"created\":1501597379645,\"text\":\"累计分布\"},\"children\":[{\"data\":{\"id\":\"bepbuqgr57cc\",\"created\":1501597400085,\"text\":\"累计频数分布\"},\"children\":[{\"data\":{\"id\":\"bepbvcv6fyo8\",\"created\":1501597448847,\"text\":\"表示的是小于或者等于每一组上组限的数据项个数，而不是每一组的频数\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbutrb7koc\",\"created\":1501597407254,\"text\":\"累计相对频数分布\"},\"children\":[]},{\"data\":{\"id\":\"bepbux8u6pkw\",\"created\":1501597414844,\"text\":\"累计百分数频数分布\"},\"children\":[]}]},{\"data\":{\"id\":\"bepbw6ebiww0\",\"created\":1501597513131,\"text\":\"茎叶显示\",\"image\":\"http://img3.imgtn.bdimg.com/it/u=1897291883,925841950&fm=26&gp=0.jpg\",\"imageTitle\":\"那位高手能用excel帮我制作茎叶图\",\"imageSize\":{\"width\":200,\"height\":162}},\"children\":[{\"data\":{\"id\":\"bepbwbuhpc84\",\"created\":1501597524993,\"text\":\"茎叶显示是同时用于显示数据的等级顺序和分布的图形显示\"},\"children\":[{\"data\":{\"id\":\"bepbx5aanz4k\",\"created\":1501597589075,\"text\":\"优点一：易于手绘\",\"priority\":1},\"children\":[]},{\"data\":{\"id\":\"bepbxg693m88\",\"created\":1501597612775,\"text\":\"优点二：在一个组内，由于茎叶显示提供了实际的数据值，因此茎叶显示比直方图提供更多的信息\",\"priority\":1},\"children\":[]}]},{\"data\":{\"id\":\"bepbysc82h44\",\"created\":1501597717622,\"text\":\"数据过多时把每个高位数字拆分为两个或更多的茎 \"},\"children\":[]},{\"data\":{\"id\":\"bepbzhx43xss\",\"created\":1501597773304,\"text\":\"对于超过3位数的数据也可用茎叶显示 \"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepcb1sftrco\",\"created\":1501598678563,\"text\":\"用表格方式汇总两个变量的数据\",\"color\":\"#ff0000\",\"font-size\":18,\"font-weight\":\"bold\"},\"children\":[{\"data\":{\"id\":\"bepcbak9ehkc\",\"created\":1501598697660,\"text\":\"交叉分组表（行百分比是重点）\",\"font-weight\":\"bold\",\"color\":\"#ff0000\",\"font-size\":18},\"children\":[{\"data\":{\"id\":\"bepcbeaj3e8s\",\"created\":1501598705778,\"text\":\" 是一种汇总两个变量数据的方法\"},\"children\":[]}]},{\"data\":{\"id\":\"bepcbpdp1gws\",\"created\":1501598729914,\"text\":\"辛普森悖论\",\"color\":\"#ff0000\",\"font-weight\":\"bold\",\"font-size\":18},\"children\":[{\"data\":{\"id\":\"bepcbwq6w7sc\",\"created\":1501598745907,\"text\":\"依据综合和未综合数据得到的相反的结论被称为辛普森悖论，因为可能存在一个影响结论的隐藏变量\",\"color\":\"#ff0000\",\"font-weight\":\"bold\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepcd3fvatc0\",\"created\":1501598838885,\"text\":\"用图形显示方式汇总两个变量的数据\"},\"children\":[{\"data\":{\"id\":\"bepd90l3qg0g\",\"created\":1501601340324,\"text\":\"散点图和趋势图\"},\"children\":[{\"data\":{\"id\":\"bepd99kagtss\",\"created\":1501601359866,\"text\":\"散点图\"},\"children\":[{\"data\":{\"id\":\"bepd9bl867ks\",\"created\":1501601364276,\"text\":\"分支主题\"},\"children\":[]}]}]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"a4574ad8399575833a2381223a8d2a92","csrf_token":"2cb4e1ffb6b0ce9e1a61abc4fccf8dfd"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
