### ISSUE TITLE
谷歌浏览器 报错，很频繁，用了一会报错不下于10次

### ISSUE THREAD

**Issue by Alukarlile** [fex-team/kityminder-editor#458]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"6c00de53b3c1\",\"created\":1501579362,\"text\":\"钉钉\",\"resource\":[]},\"children\":[{\"data\":{\"id\":\"beppg972yuos\",\"created\":1501635760936,\"text\":\"注册\",\"layout_mind_offset\":{\"x\":31,\"y\":-57}},\"children\":[]},{\"data\":{\"id\":\"beppmoincq8s\",\"created\":1501636264472,\"text\":\"登陆\",\"layout_mind_offset\":{\"x\":20,\"y\":-131}},\"children\":[{\"data\":{\"id\":\"bepppa104bcc\",\"created\":1501636468022,\"text\":\"消息\"},\"children\":[{\"data\":{\"id\":\"beppqqkfw80k\",\"created\":1501636582390,\"text\":\"通知类消息\"},\"children\":[]},{\"data\":{\"id\":\"beppqs9pcbso\",\"created\":1501636586095,\"text\":\"群消息，单人聊天\"},\"children\":[]},{\"data\":{\"id\":\"beppuqj6gbcc\",\"created\":1501636895771,\"text\":\"其他\"},\"children\":[]}]},{\"data\":{\"id\":\"bepppdw42fsc\",\"created\":1501636476434,\"text\":\"DING\"},\"children\":[{\"data\":{\"id\":\"bepps0skkr48\",\"created\":1501636683014,\"text\":\"任务\"},\"children\":[]},{\"data\":{\"id\":\"bepps319y4o4\",\"created\":1501636687894,\"text\":\"会议\",\"layout_right_offset\":{\"x\":3,\"y\":-1}},\"children\":[]},{\"data\":{\"id\":\"bepps3e04bkk\",\"created\":1501636688663,\"text\":\"DING\"},\"children\":[]},{\"data\":{\"id\":\"bepps3qjw80k\",\"created\":1501636689422,\"text\":\"收到的\"},\"children\":[]},{\"data\":{\"id\":\"bepps45r3e0o\",\"created\":1501636690341,\"text\":\"发出的\"},\"children\":[]},{\"data\":{\"id\":\"beppsoualeok\",\"created\":1501636735361,\"text\":\"回收站\"},\"children\":[]}]},{\"data\":{\"id\":\"bepppnusz0w8\",\"created\":1501636498122,\"text\":\"公司模块\"},\"children\":[{\"data\":{\"id\":\"bepptr64tnkk\",\"created\":1501636818794,\"text\":\"人事统计\"},\"children\":[{\"data\":{\"id\":\"beppuxmxf9c0\",\"created\":1501636911235,\"text\":\"待我审批\"},\"children\":[{\"data\":{\"id\":\"beprs26697kk\",\"created\":1501642328233,\"text\":\"待我审批的\"},\"children\":[]},{\"data\":{\"id\":\"beprs5ocjd44\",\"created\":1501642335862,\"text\":\"我已审批的\"},\"children\":[]}]},{\"data\":{\"id\":\"beppuz3l6rcw\",\"created\":1501636914419,\"text\":\"出勤天数\"},\"children\":[{\"data\":{\"id\":\"beprsrgbf20w\",\"created\":1501642383266,\"text\":\"排行\"},\"children\":[]},{\"data\":{\"id\":\"beprtbprpigo\",\"created\":1501642427373,\"text\":\"出勤天数，休息天数\"},\"children\":[]},{\"data\":{\"id\":\"beprtgukv08w\",\"created\":1501642438548,\"text\":\"迟到，早退，缺卡，矿工，外勤\"},\"children\":[]}]},{\"data\":{\"id\":\"beppuzl05ios\",\"created\":1501636915472,\"text\":\"未读日志\"},\"children\":[{\"data\":{\"id\":\"beprxvjfa2gw\",\"created\":1501642783983,\"text\":\"我收到的\"},\"children\":[]},{\"data\":{\"id\":\"beprxynrn9k4\",\"created\":1501642790775,\"text\":\"我发出的\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bepptynvlu04\",\"created\":1501636835105,\"text\":\"常用应用\"},\"children\":[{\"data\":{\"id\":\"beppvb4apnkk\",\"created\":1501636940583,\"text\":\"考勤打卡\"},\"children\":[{\"data\":{\"id\":\"bepryd68vlkw\",\"created\":1501642822367,\"text\":\"打卡\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beps0sgzeawo\",\"created\":1501643012396,\"text\":\"上班打卡，下班打卡，外勤打卡\"},\"children\":[]}]},{\"data\":{\"id\":\"beprzxzdxfs4\",\"created\":1501642946029,\"text\":\"申请\"},\"children\":[{\"data\":{\"id\":\"beps16g654w0\",\"created\":1501643042822,\"text\":\"补卡申请，申请记录\"},\"children\":[]}]},{\"data\":{\"id\":\"beprydo4swoc\",\"created\":1501642823449,\"text\":\"统计\"},\"children\":[{\"data\":{\"id\":\"beps2toz64g0\",\"created\":1501643171785,\"text\":\"同出勤天数\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beppvhxcnrk8\",\"created\":1501636955401,\"text\":\"签到\"},\"children\":[{\"data\":{\"id\":\"beps421rimg4\",\"created\":1501643268336,\"text\":\"签到\"},\"children\":[]},{\"data\":{\"id\":\"beps42i3xvs4\",\"created\":1501643269325,\"text\":\"足迹\"},\"children\":[]}]},{\"data\":{\"id\":\"beppvi7ooa8s\",\"created\":1501636956026,\"text\":\"日志\"},\"children\":[{\"data\":{\"id\":\"beps4dfiuuww\",\"created\":1501643293113,\"text\":\"日报\"},\"children\":[]},{\"data\":{\"id\":\"beps4flr2igw\",\"created\":1501643297843,\"text\":\"周报\"},\"children\":[]},{\"data\":{\"id\":\"beps4hcvxs84\",\"created\":1501643301661,\"text\":\"月报\"},\"children\":[]},{\"data\":{\"id\":\"beps4ip6hu04\",\"created\":1501643304581,\"text\":\"业绩日报\"},\"children\":[]},{\"data\":{\"id\":\"beps4o1yrtsg\",\"created\":1501643316238,\"text\":\"其他\"},\"children\":[]}]},{\"data\":{\"id\":\"beppvihlae8g\",\"created\":1501636956625,\"text\":\"公告\"},\"children\":[{\"data\":{\"id\":\"beps4uosivsc\",\"created\":1501643330679,\"text\":\"已读，未读\"},\"children\":[]},{\"data\":{\"id\":\"beps4xfobfkg\",\"created\":1501643336658,\"text\":\"发公告\"},\"children\":[]}]},{\"data\":{\"id\":\"beppvirxqww0\",\"created\":1501636957250,\"text\":\"审批\"},\"children\":[{\"data\":{\"id\":\"beps5phb3b40\",\"created\":1501643397706,\"text\":\"出勤休假，待我审批的，我发起的，抄送我的，可添加/管理\"},\"children\":[]}]},{\"data\":{\"id\":\"beppvj2t3yg4\",\"created\":1501636957907,\"text\":\"钉邮\",\"note\":\"具有完整的邮箱功能\\n\"},\"children\":[]},{\"data\":{\"id\":\"beppvjeq3ww8\",\"created\":1501636958628,\"text\":\"钉盘\"},\"children\":[{\"data\":{\"id\":\"beps8jqhf1ss\",\"created\":1501643620293,\"text\":\"我的文件\"},\"children\":[]},{\"data\":{\"id\":\"beps8n7rpq0w\",\"created\":1501643627869,\"text\":\"共享文件\"},\"children\":[]},{\"data\":{\"id\":\"beps8pago60c\",\"created\":1501643632385,\"text\":\"企业内部文件\"},\"children\":[]}]},{\"data\":{\"id\":\"beppw3j0qz48\",\"created\":1501637002423,\"text\":\"智能报表\",\"note\":\"内容多为H5页面\\n\"},\"children\":[]}]},{\"data\":{\"id\":\"bepptz0x76wo\",\"created\":1501636835894,\"text\":\"其他应用\"},\"children\":[{\"data\":{\"id\":\"beppwyqpflkw\",\"created\":1501637070368,\"text\":\"电话会议\"},\"children\":[]},{\"data\":{\"id\":\"beppx09g9ag4\",\"created\":1501637073679,\"text\":\"客户管理\"},\"children\":[]},{\"data\":{\"id\":\"bepq347ppbsw\",\"created\":1501637552466,\"text\":\"办公电话\"},\"children\":[]},{\"data\":{\"id\":\"beppx0k0peok\",\"created\":1501637074318,\"text\":\"天猫企业购\"},\"children\":[]},{\"data\":{\"id\":\"beppx0ssbdkc\",\"created\":1501637074848,\"text\":\"易快报\"},\"children\":[]},{\"data\":{\"id\":\"beppx11a9y8k\",\"created\":1501637075362,\"text\":\"其他\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beppqbmmfqos\",\"created\":1501636549871,\"text\":\"联系人\"},\"children\":[{\"data\":{\"id\":\"bepqgcystnso\",\"created\":1501638590252,\"text\":\"钉钉好友\"},\"children\":[{\"data\":{\"id\":\"bepsbv7vi3kk\",\"created\":1501643880382,\"text\":\"新的好友\"},\"children\":[]},{\"data\":{\"id\":\"bepsbwyzhmo0\",\"created\":1501643884198,\"text\":\"好友列表\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqgdttedk4\",\"created\":1501638592127,\"text\":\"手机通讯录\",\"note\":\"可匹配手机通讯录\\n\\n\"},\"children\":[]},{\"data\":{\"id\":\"bepqge3vqeos\",\"created\":1501638592736,\"text\":\"我的群组\"},\"children\":[{\"data\":{\"id\":\"bepsd0rtrh4c\",\"created\":1501643970836,\"text\":\"我创建的，我加入的\"},\"children\":[]},{\"data\":{\"id\":\"bepsd4tn7lcs\",\"created\":1501643979654,\"text\":\"发起群聊\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqgecz12go\",\"created\":1501638593286,\"text\":\"企业主页\"},\"children\":[{\"data\":{\"id\":\"bepsdgg4bogk\",\"created\":1501644004957,\"text\":\"公司信息\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqgenufvkg\",\"created\":1501638593943,\"text\":\"公司通讯录\"},\"children\":[{\"data\":{\"id\":\"bepse5yiansw\",\"created\":1501644060488,\"text\":\"可划分部门\"},\"children\":[]},{\"data\":{\"id\":\"bepsecepak0s\",\"created\":1501644074528,\"text\":\"外部联系人\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqou1y3sow\",\"created\":1501639254361,\"text\":\"常用联系人\"},\"children\":[]}]},{\"data\":{\"id\":\"beppqcvrwq8s\",\"created\":1501636552602,\"text\":\"我的\"},\"children\":[{\"data\":{\"id\":\"bepqpz0wwqo0\",\"created\":1501639343546,\"text\":\"个人信息\"},\"children\":[{\"data\":{\"id\":\"bepseqtm3mwo\",\"created\":1501644105905,\"text\":\"头像，昵称，电话，钉钉号，二维码名片，性别，生日，地区，个人实名认证\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqq06kcfco\",\"created\":1501639346065,\"text\":\"钉钉卡\"},\"children\":[]},{\"data\":{\"id\":\"bepqq11pngg0\",\"created\":1501639347948,\"text\":\"我的客服\"},\"children\":[]},{\"data\":{\"id\":\"bepqq1bob1ss\",\"created\":1501639348551,\"text\":\"红包\"},\"children\":[]},{\"data\":{\"id\":\"bepqqipf968s\",\"created\":1501639386387,\"text\":\"收藏\"},\"children\":[{\"data\":{\"id\":\"bepsfkg37808\",\"created\":1501644170390,\"text\":\"收藏消息\"},\"children\":[]}]},{\"data\":{\"id\":\"bepqq1npptkw\",\"created\":1501639349279,\"text\":\"表情\"},\"children\":[]},{\"data\":{\"id\":\"bepqq1w5e74g\",\"created\":1501639349789,\"text\":\"福利社\"},\"children\":[]},{\"data\":{\"id\":\"bepqq270v1ss\",\"created\":1501639350446,\"text\":\"邀请\"},\"children\":[]},{\"data\":{\"id\":\"bepqqxwy8woc\",\"created\":1501639419494,\"text\":\"设置\"},\"children\":[{\"data\":{\"id\":\"bepsfz804j4s\",\"created\":1501644202553,\"text\":\"账号与安全，新消息通知\"},\"children\":[]},{\"data\":{\"id\":\"bepsgay7ue8k\",\"created\":1501644228083,\"text\":\"隐私\"},\"children\":[]},{\"data\":{\"id\":\"bepsgfq9n0o4\",\"created\":1501644238486,\"text\":\"通用\"},\"children\":[{\"data\":{\"id\":\"bepsgsfz334g\",\"created\":1501644266162,\"text\":\"多语言\"},\"children\":[]},{\"data\":{\"id\":\"bepsgxxgts84\",\"created\":1501644278104,\"text\":\"字体大小\"},\"children\":[]},{\"data\":{\"id\":\"bepsh020ha80\",\"created\":1501644282732,\"text\":\"密聊\"},\"children\":[]},{\"data\":{\"id\":\"bepsh1rgc0wg\",\"created\":1501644286447,\"text\":\"全屏语音，一键清理\"},\"children\":[]}]},{\"data\":{\"id\":\"bepsghtn8a0o\",\"created\":1501644243044,\"text\":\"关于钉钉\"},\"children\":[]},{\"data\":{\"id\":\"bepsgkziv5kw\",\"created\":1501644249930,\"text\":\"实验室\"},\"children\":[]},{\"data\":{\"id\":\"bepsgn5edy8k\",\"created\":1501644254639,\"text\":\"退出登录\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"beppnasoq28s\",\"created\":1501636312968,\"text\":\"忘记密码\",\"layout_mind_offset\":{\"x\":416,\"y\":98}},\"children\":[]},{\"data\":{\"id\":\"beppnm6g7d44\",\"created\":1501636337745,\"text\":\"账号挂失\",\"layout_mind_offset\":{\"x\":418,\"y\":91}},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"654f936ba3cfc9e4669a9673df4af79a","csrf_token":"2b6de30e5c6c5f70b32f7fb8582dd3b7"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by Arohy-Q** [comment]
我也是同样的问题，比较烦，希望开发人员尽快解决

**Comment by evanzou** [comment]
我也是这个问题，应该是脑图网络方面的问题，目前只有一个暂时的办法，就是每次报错的时候，把报错提示叉掉，然后按ctrl+s手动保存，这样就不用每次刷新页面了。 这样虽然好点，但也挺麻烦的，希望开发人员早点解决这个问题。

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
