### ISSUE TITLE
移动端问题反馈

### ISSUE THREAD

**Issue by shuli083** [fex-team/kityminder-editor#46]
移动端：测试手机华为X2，浏览器竖屏打开脑图，出现问题如图下图：

![screenshot_2015-07-25-10-19-47](https://cloud.githubusercontent.com/assets/13491835/8887507/61d32dae-32b7-11e5-9a2b-a491e97604fa.png)

横屏打开脑图无法点击选择。
![screenshot_2015-07-25-10-20-17](https://cloud.githubusercontent.com/assets/13491835/8887506/61d24efc-32b7-11e5-973e-e5d65de2c489.png)

**Comment by zhangbobell** [comment]
你好，目前脑图在移动端还没有做适配，所以移动端操作起来很不方便，未来我们会对移动端做适配。
