### ISSUE TITLE
【功能缺陷】xmind格式的导入和导出会丢失备注！！！

### ISSUE THREAD

**Issue by Arohy-Q** [fex-team/kityminder-editor#461]
如题，以xmind格式导入和导出时均会导致备注无法同步导入/导出；望尽快实现该功能。

**Comment by zhangbobell** [comment]
duplicate with #170

**Comment by magicbo00** [comment]
在kityminder.core.js	 的8222行后增加如下代码，可以实现纯文本备注的导入                   
//处理备注
	                        if (topic['notes']) {
	                        obj.data.note = topic.notes.plain;
	                        }
