### ISSUE TITLE
提示我网络连接断开，但我的网络是正常的

### ISSUE THREAD

**Issue by TobisLee** [fex-team/kityminder-editor#465]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"b2d4db2e696d\",\"created\":1501899897,\"text\":\"python\"},\"children\":[{\"data\":{\"id\":\"besb36vzuxs0\",\"created\":1501899921509,\"text\":\"OOP\",\"layout_mind_offset\":{\"x\":7.000000312924442,\"y\":-109.99998158216422},\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besb43hcnow0\",\"created\":1501899992457,\"text\":\"类和实例\",\"layout\":null,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"besb48aa6w80\",\"created\":1501900002915,\"text\":\"类\",\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besb6t0tpxk0\",\"created\":1501900204783,\"text\":\"类是抽象的模板\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besb4l5xig00\",\"created\":1501900030949,\"text\":\"class关键字定义类，类名通常是大写开头的单词\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besb556vzw00\",\"created\":1501900074542,\"text\":\"(object)表示是从哪个类继承下来的\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"besb4efivhc0\",\"created\":1501900016291,\"text\":\"实例\",\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besb8jcm8080\",\"created\":1501900340456,\"text\":\"实例是根据类创建出来的一个个具体的对象\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besb56ul6mg0\",\"created\":1501900078152,\"text\":\"类名+()创建实例\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besb5er9efs0\",\"created\":1501900095365,\"text\":\"定义__init__方法，把我们认为该类必须具有的属性强制填写进去，__init__方法的第一个参数永远是self,表示创建的实例本身。\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"besbe1rjp6o0\",\"created\":1501900772362,\"text\":\"方法\",\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besbe5cc8bk0\",\"created\":1501900780149,\"text\":\"方法就是与实例绑定的函数，可以直接访问实例的数据\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besbeoqqfgo0\",\"created\":1501900822379,\"text\":\"通过在实例上调用方法，可以直接操作对象的数据，但无需知道方法内部的实现细节，做到了数据封装\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"besbhgvgqhs0\",\"created\":1501901040343,\"text\":\"访问限制\",\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besbhkpcwko0\",\"created\":1501901048681,\"text\":\"如果要让内部属性不被外部访问，可以在属性的名称前加上两个下划线__，使其变成私有变量\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besbiqfq02w0\",\"created\":1501901139523,\"text\":\"变量名类似__xxx__是特殊变量，是可以直接从外部访问的\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"besbkgfagfs0\",\"created\":1501901274457,\"text\":\"以一个下划线开头的变量名表示：虽然我可以被访问，但请把我当成私有变量\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"besbn3w6fqg0\",\"created\":1501901482273,\"text\":\"继承和多态\",\"layout\":null,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"besgf2nfv2o0\",\"created\":1501914958204,\"text\":\"继承\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"besgf99t2y00\",\"created\":1501914972617,\"text\":\"子类继承父类，就可以直接使用父类具有的功能，\\n还可以自己添加新的方法，或者覆写父类的方法\"},\"children\":[]}]},{\"data\":{\"id\":\"besbn7mvc3k0\",\"created\":1501901490417,\"text\":\"多态\",\"expandState\":\"collapse\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"besby3rh3ww0\",\"created\":1501902343994,\"text\":\"鸭子类型特点：对于Python这样的动态语言来说，不一定传入继承的父类的类型，\\n只要保证传入对象有一个相应的方法就可以\",\"note\":\"class Animal(object):\\n\\tdef run(self):\\n\\t\\tprint('animal run')\\n\\nclass Dog(Animal):\\n\\tdef run(self):\\n\\t\\tprint('Dog run')\\n\\nclass Timer(object):\\n\\tdef run(self):\\n\\t\\tprint('Timer run')\\n\\ndef run_twice(animal):\\n\\tanimal.run()\\n\\tanimal.run()\\n\\nrun_twice(Animal())\\nrun_twice(Dog())\\nrun_twice(Timer())\\n\\n执行结果：\\nanimal run\\nanimal run\\nDog run\\nDog run\\nTimer run\\nTimer run\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"besgi69voc80\",\"created\":1501915201184,\"text\":\"获取对象信息\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"besgia63a3s0\",\"created\":1501915209662,\"text\":\"使用type()判断对象的类型\",\"resource\":[]},\"children\":[]},{\"data\":{\"id\":\"besgmb4jcps0\",\"created\":1501915525201,\"text\":\"types模块中定义的常量可用来判断一个对象是否是函数\"},\"children\":[]},{\"data\":{\"id\":\"besgmtdhm1c0\",\"created\":1501915564924,\"text\":\"isinstance()判断一个对象是否是该类型本身，或者位于该类型的父继承链上\"},\"children\":[]},{\"data\":{\"id\":\"besgoqkqi9c0\",\"created\":1501915715561,\"text\":\"dir()获得一个对象的所有属性和方法，返回一个包含字符串的list\"},\"children\":[]},{\"data\":{\"id\":\"besgrbo57sw0\",\"created\":1501915918208,\"text\":\"hasattr():是否有某个属性\"},\"children\":[]},{\"data\":{\"id\":\"besgs562pk80\",\"created\":1501915982418,\"text\":\"getattr():获取某个属性\"},\"children\":[]},{\"data\":{\"id\":\"besgsem1tqw0\",\"created\":1501916002975,\"text\":\"setattr():设置某个属性\"},\"children\":[]}]},{\"data\":{\"id\":\"besgvi4nvbc0\",\"created\":1501916245724,\"text\":\"实例属性和类属性\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"besgvpqiywo0\",\"created\":1501916262283,\"text\":\"在写程序的时候，千万不要把实例属性和类属性使用相同的名字，\\n相同名称的实例属性会将类属性屏蔽掉\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beshbwenuxc0\",\"created\":1501917530630,\"text\":\"OOP高级编程\",\"layout_mind_offset\":{\"x\":-77.00000344216832,\"y\":8.000000357627961}},\"children\":[{\"data\":{\"id\":\"beshc58e1ig0\",\"created\":1501917549842,\"text\":\"使用__slots__\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beshcavsaa00\",\"created\":1501917562140,\"text\":\"使用__slots__可以限制实例的属性\"},\"children\":[]},{\"data\":{\"id\":\"beshcs5unzk0\",\"created\":1501917599754,\"text\":\"格式：__slots__ = ('name', 'age')#用tuple定义允许绑定的属性名称\"},\"children\":[]},{\"data\":{\"id\":\"beshdieeym80\",\"created\":1501917656868,\"text\":\"__slots__定义的属性仅对当前实例起作用，对继承的子类是不起作用的\"},\"children\":[]},{\"data\":{\"id\":\"beshe8icusg0\",\"created\":1501917713703,\"text\":\"若在子类中也定义__slots__,那么子类允许定义的属性就是自身的__slots__,加上父类的__slots__\"},\"children\":[]}]},{\"data\":{\"id\":\"beshfasxxhk0\",\"created\":1501917797061,\"text\":\"使用@property\",\"note\":\"class Screen(object):\\n\\n    @property\\n    def width(self):        #getWidth()\\n        return self._width\\n\\n    @width.setter\\n    def width(self, value): #setWidth()\\n        self._width = value\\n\\n    @property\\n    def height(self):       #getHeight()\\n        return self._height\\n\\n    @height.setter\\n    def height(self, value):#setHeight()\\n        self._height = value\\n\\n    @property\\n    def resolution(self):   #getResolution()\\n        return self._height * self._width\\n\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beshzcgco480\",\"created\":1501919367936,\"text\":\"@property装饰器就是负责把一个方法变成属性调用的\"},\"children\":[]},{\"data\":{\"id\":\"beshzt2w1dc0\",\"created\":1501919404128,\"text\":\"把一个getter方法变成属性，只需要加上@property\"},\"children\":[]},{\"data\":{\"id\":\"besi0j3o1zs0\",\"created\":1501919460771,\"text\":\"@xxx.setter负责把一个setter方法变成属性赋值\"},\"children\":[]},{\"data\":{\"id\":\"besi1nknxiw0\",\"created\":1501919548870,\"text\":\"定义只读属性：只定义getter方法，不定义setter方法\"},\"children\":[]}]},{\"data\":{\"id\":\"beskykof8940\",\"created\":1501927770804,\"text\":\"多重继承\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beskypm9eow0\",\"created\":1501927781557,\"text\":\"Python允许使用多重继承，Mixln就是一种常见的设计\"},\"children\":[]}]},{\"data\":{\"id\":\"besl4mrcx540\",\"created\":1501928245520,\"text\":\"定制类\"},\"children\":[{\"data\":{\"id\":\"besl4peigg00\",\"created\":1501928251274,\"text\":\"__str__():返回用户看到的字符串\"},\"children\":[]},{\"data\":{\"id\":\"besl5rzucjk0\",\"created\":1501928335281,\"text\":\"__repr__():返回程序开发者看到的字符串\"},\"children\":[]},{\"data\":{\"id\":\"besl69yaywo0\",\"created\":1501928374370,\"text\":\"__iter__():如果一个类想被用于for...in循环，就必须实现该方法，\\n然后，for循环就会不断调用该迭代对象的__next__()方法拿到循环的下一个值，\\n直到遇到StopIteration错误时推出循环\"},\"children\":[]},{\"data\":{\"id\":\"besl9d6h7dk0\",\"created\":1501928616487,\"text\":\"__getitem__():可以让对象按照下标取出元素\\n__delitem__():删除某个元素\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beshbxll0g00\",\"created\":1501917533225,\"text\":\"分支主题\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"classic\",\"version\":\"1.4.43\"}","fileGuid":"6ea748ec1ea1038384aabf10dcc538b1","csrf_token":"071361f9c4ee9b4ca354054c48581352"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
