### ISSUE TITLE
报错提交

### ISSUE THREAD

**Issue by suiyia** [fex-team/kityminder-editor#466]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"aa9b9036ec53\",\"created\":1490576578,\"text\":\"问题总结\"},\"children\":[{\"data\":{\"id\":\"bete2qrdbug0\",\"created\":1502009909687,\"text\":\"计算机网络\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete3s7k0800\",\"created\":1502009991207,\"text\":\"[Network] 计算机网络基础知识总结\",\"hyperlink\":\"http://www.cnblogs.com/maybe2030/p/4781555.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete47e42rs0\",\"created\":1502010024255,\"text\":\"简析TCP的三次握手与四次分手\",\"hyperlink\":\"http://www.jellythink.com/archives/705\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete4bd4v340\",\"created\":1502010032903,\"text\":\"DNS解析过程\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete8u5r1p40\",\"created\":1502010387272,\"text\":\"一张图看懂DNS域名解析全过程\",\"hyperlink\":\"http://www.maixj.net/ict/dns-chaxun-9208\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete8umac200\",\"created\":1502010388272,\"text\":\" DNS原理总结及其解析过程详解\",\"hyperlink\":\"http://blog.csdn.net/yipiankongbai/article/details/25031461\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bete4bw17ds0\",\"created\":1502010034046,\"text\":\"TCP UDP\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete94yc8s00\",\"created\":1502010410768,\"text\":\"TCP和UDP的最完整的区别\",\"hyperlink\":\"http://blog.csdn.net/li_ning_/article/details/52117463\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bete5v4n1dc0\",\"created\":1502010154289,\"text\":\"HTTP HTTPS\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete72aodao0\",\"created\":1502010248256,\"text\":\"图解HTTPS\",\"hyperlink\":\"http://www.admin5.com/article/20150523/600105.shtml\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete7358hbk0\",\"created\":1502010250103,\"text\":\"HTTPS那些事（一）HTTPS原理\",\"hyperlink\":\"http://www.guokr.com/post/114121/\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete73ls9hs0\",\"created\":1502010251104,\"text\":\"聊聊HTTPS和SSL/TLS协议\",\"hyperlink\":\"http://www.techug.com/post/https-ssl-tls.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bete2sqaxhs0\",\"created\":1502009913976,\"text\":\"操作系统\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bete32jjmc00\",\"created\":1502009935335,\"text\":\"JavaSE\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betefketa3c0\",\"created\":1502010914601,\"text\":\"面试题集1，2，3\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betefyktqd40\",\"created\":1502010945440,\"text\":\"Java面试题全集（上）\",\"hyperlink\":\"http://blog.csdn.net/jackfrued/article/details/44921941/\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"betefzq3rcw0\",\"created\":1502010947936,\"text\":\"Java面试题全集（中）\",\"hyperlink\":\"http://blog.csdn.net/jackfrued/article/details/44931137/\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"beteg07a4vs0\",\"created\":1502010948974,\"text\":\"Java面试题全集（下）\",\"hyperlink\":\"http://blog.csdn.net/jackfrued/article/details/44931161/\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"betefl46gyo0\",\"created\":1502010916135,\"text\":\"HashMap\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"beteglnb53k0\",\"created\":1502010995656,\"text\":\"Java8系列之重新认识HashMap\",\"hyperlink\":\"http://www.importnew.com/20386.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"betegml7nuo0\",\"created\":1502010997706,\"text\":\"java中HashMap详解\",\"hyperlink\":\"http://blog.csdn.net/caihaijiang/article/details/6280251\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"betefls05ko0\",\"created\":1502010917576,\"text\":\"虚拟机相关\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betehnaooyg0\",\"created\":1502011077610,\"text\":\"极客学院讲解深入理解 Java 虚拟机\",\"hyperlink\":\"http://wiki.jikexueyuan.com/project/java-vm/garbage-collection-mechanism.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"betehnwmum80\",\"created\":1502011078937,\"text\":\"博客讲解\",\"hyperlink\":\"http://blog.csdn.net/yano_nankai/article/details/50957578\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"betefm96i1c0\",\"created\":1502010918614,\"text\":\"类之间的关系\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"beteig505280\",\"created\":1502011140393,\"text\":\"Java类之间的关联关系\",\"hyperlink\":\"http://blog.csdn.net/vickyway/article/details/7583545\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"beteiodwb9k0\",\"created\":1502011158345,\"text\":\"Java 函数调用是传值还是传引用？从字节码角度来看看\",\"hyperlink\":\"https://mp.weixin.qq.com/s?__biz=MjM5NzMyMjAwMA==&mid=2651478800&idx=2&sn=33f12b6c3e1bfa45da70ec08a6cbb7fc&chksm=bd25376f8a52be79063b4104ade4af114e1e22b8ad24d15b03758e335e378c01cce0b42e88f3&mpshare=1&scene=23&srcid=0719uBzWETmpQUwhPuDRUGQM#rd\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"beteiyvhoi00\",\"created\":1502011181177,\"text\":\"多线程\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betej38rzj40\",\"created\":1502011190688,\"text\":\"Java中的多线程你只要看这一篇就够了\",\"hyperlink\":\"http://www.cnblogs.com/wxd0108/p/5479442.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"betej5fx2k80\",\"created\":1502011195473,\"text\":\"Java多线程学习（吐血超详细总结）\",\"hyperlink\":\"http://www.mamicode.com/info-detail-517008.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"betek3n0i6g0\",\"created\":1502011269913,\"text\":\"String\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betek6n953s0\",\"created\":1502011276457,\"text\":\"通过反编译深入理解Java String及intern\",\"hyperlink\":\"http://www.sohu.com/a/113479112_208397\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bete2wzsplc0\",\"created\":1502009923257,\"text\":\"设计模式\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"beteaufocpk0\",\"created\":1502010544600,\"text\":\"分支主题\",\"hyperlink\":\"http://blog.csdn.net/jason0539/article/list/1\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bete38bnvm80\",\"created\":1502009947919,\"text\":\"MySQL\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betel9mm7880\",\"created\":1502011361313,\"text\":\"MySQL 数据库面试题\",\"hyperlink\":\"http://www.cnblogs.com/Curry-Coder/p/6810757.html\",\"hyperlinkTitle\":\"\"},\"children\":[]},{\"data\":{\"id\":\"betemcrwy0g0\",\"created\":1502011446528,\"text\":\"MySQL隔离级别\",\"hyperlink\":\"http://www.cnblogs.com/snsdzjlz320/p/5761387.html\",\"hyperlinkTitle\":\"\"},\"children\":[]},{\"data\":{\"id\":\"betemdwp1eg0\",\"created\":1502011448994,\"text\":\"MySQL 索引\"},\"children\":[{\"data\":{\"id\":\"betepek0n2o0\",\"created\":1502011685497,\"text\":\"MySQL索引类型一览 让MySQL高效运行起来\",\"hyperlink\":\"http://database.51cto.com/art/200910/156685.htm\",\"hyperlinkTitle\":\"\"},\"children\":[]},{\"data\":{\"id\":\"betepey1icg0\",\"created\":1502011686345,\"text\":\"MySQL索引原理及慢查询优化\",\"hyperlink\":\"https://tech.meituan.com/mysql-index.html\",\"hyperlinkTitle\":\"\"},\"children\":[]},{\"data\":{\"id\":\"betepug4o9c0\",\"created\":1502011720090,\"text\":\"MySQL索引背后的数据结构及算法原理\",\"hyperlink\":\"http://blog.codinglabs.org/articles/theory-of-mysql-index.html\",\"hyperlinkTitle\":\"\"},\"children\":[]},{\"data\":{\"id\":\"betepvusceo0\",\"created\":1502011723153,\"text\":\"MySQL有哪些索引类型 ?\",\"hyperlink\":\"https://segmentfault.com/q/1010000003832312\",\"hyperlinkTitle\":\"\"},\"children\":[]}]},{\"data\":{\"id\":\"betemelenbs0\",\"created\":1502011450488,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"betemf66m5s0\",\"created\":1502011451745,\"text\":\"分支主题\"},\"children\":[]}]},{\"data\":{\"id\":\"bete2v3ih740\",\"created\":1502009919128,\"text\":\"数据结构\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete9d41t1s0\",\"created\":1502010428528,\"text\":\"KMP\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bete9f9c6iw0\",\"created\":1502010433201,\"text\":\"字符串匹配的KMP算法\",\"hyperlink\":\"http://www.ruanyifeng.com/blog/2013/05/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm.html\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bete9n35hnk0\",\"created\":1502010450241,\"text\":\"红黑树\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bete3d103jc0\",\"created\":1502009958159,\"text\":\"JavaEE\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"betejs70xeg0\",\"created\":1502011245001,\"text\":\"开涛 Ioc DI 解析\",\"hyperlink\":\"http://jinnianshilongnian.iteye.com/blog/1413846\",\"hyperlinkTitle\":\"\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"beteq8cm8f40\",\"created\":1502011750353,\"text\":\"博客推荐\"},\"children\":[{\"data\":{\"id\":\"beteqbwty8g0\",\"created\":1502011758106,\"text\":\"LeetCode 题型\",\"hyperlink\":\"http://blog.csdn.net/yano_nankai?viewmode=contents\",\"hyperlinkTitle\":\"\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue-compat\",\"version\":\"1.4.43\"}","fileGuid":"1b5ba794da177936d0a99299eff9b1db","csrf_token":"1f3b13216580a6b9ced46ecaa904c445"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
