### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by yang-xd** [fex-team/kityminder-editor#467]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"text\":\"微信公众号\"},\"children\":[{\"data\":{\"text\":\"云邦客\"},\"children\":[{\"data\":{\"text\":\"邀请注册\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"text\":\"显示邀请人信息\"},\"children\":[]},{\"data\":{\"text\":\"手机号短信验证注册\"},\"children\":[]},{\"data\":{\"text\":\"设置密码\"},\"children\":[]}]},{\"data\":{\"text\":\"完善会员信息\"},\"children\":[{\"data\":{\"text\":\"姓名\"},\"children\":[]},{\"data\":{\"text\":\"身份证号\"},\"children\":[]},{\"data\":{\"text\":\"绑定银行卡\"},\"children\":[{\"data\":{\"text\":\"卡号\"},\"children\":[]},{\"data\":{\"text\":\"开户行（或者预留手机）\"},\"children\":[]}]},{\"data\":{\"text\":\"选择产品\"},\"children\":[{\"data\":{\"text\":\"价值1000元产品。3-5种选择\"},\"children\":[]}]},{\"data\":{\"text\":\"收货地址\"},\"children\":[{\"data\":{\"text\":\"选择省、市、区\"},\"children\":[]},{\"data\":{\"text\":\"填写详细地址\"},\"children\":[]}]},{\"data\":{\"text\":\"点击跳转到支付界面\"},\"children\":[]}]},{\"data\":{\"text\":\"个人中心界面\"},\"children\":[{\"data\":{\"text\":\"显示个人信息\"},\"children\":[]},{\"data\":{\"text\":\"编辑头像\"},\"children\":[]},{\"data\":{\"text\":\"个人ID号码（会员卡号）\"},\"children\":[]},{\"data\":{\"text\":\"推荐与被推荐关系\"},\"children\":[{\"data\":{\"text\":\"我的推荐人\"},\"children\":[]},{\"data\":{\"text\":\"我推荐的人列表\"},\"children\":[]}]},{\"data\":{\"text\":\"收益显示\"},\"children\":[{\"data\":{\"text\":\"我的现金\"},\"children\":[]},{\"data\":{\"text\":\"我的额度\"},\"children\":[{\"data\":{\"text\":\"额度显示\"},\"children\":[{\"data\":{\"text\":\"达到200元时，系统提示云邦城邀请信息，距离进入云邦城进度。同时推送消息给到该会员的推荐人（亲爱的伙伴，你的会员XXX已经满足进入云邦城的条件，为了确保您的权益，请您快速定位云邦城，乘坐收益翻倍的快车道。）\\r\\n云邦客与云邦城衔接，如果云邦客会员进入商城，微信系统会提示该会员的推荐人（恭喜您！亲爱的伙伴，您的会员XXX已经成功开启云邦城财富之旅，正在奔向收入翻2.5倍的路上。）向该会员推送本人的云邦城推广码（提示6小时后该会员若没收到推荐人发来的云邦城推广码，微信系统会自动向该会员推送云邦城开放码。）\"},\"children\":[]}]},{\"data\":{\"text\":\"借款列表\"},\"children\":[{\"data\":{\"text\":\"40天免息\"},\"children\":[]},{\"data\":{\"text\":\"40天后可分期付款20%\"},\"children\":[]},{\"data\":{\"text\":\"40天后按照信用卡计息\"},\"children\":[]},{\"data\":{\"text\":\"提前3天提醒会员还款\"},\"children\":[]}]}]}]}]},{\"data\":{\"text\":\"人脉系统（推荐码）\"},\"children\":[{\"data\":{\"text\":\"一度人脉\"},\"children\":[{\"data\":{\"text\":\"奖励订单额的30%现金\"},\"children\":[]}]},{\"data\":{\"text\":\"二度人脉\"},\"children\":[{\"data\":{\"text\":\"奖励订单额20%的额度\"},\"children\":[]}]},{\"data\":{\"text\":\"三度人脉\"},\"children\":[{\"data\":{\"text\":\"奖励订单额20%的额度\"},\"children\":[]}]}]}]},{\"data\":{\"text\":\"云邦城\"},\"children\":[{\"data\":{\"text\":\"注册方式\"},\"children\":[{\"data\":{\"text\":\"邀请注册\"},\"children\":[{\"data\":{\"text\":\"推广人推广码\"},\"children\":[]}]},{\"data\":{\"text\":\"非邀请注册\"},\"children\":[{\"data\":{\"text\":\"商城开放码\"},\"children\":[]}]}]},{\"data\":{\"text\":\"注册界面\"},\"children\":[{\"data\":{\"text\":\"显示邀请人信息\"},\"children\":[]},{\"data\":{\"text\":\"手机号短信验证注册\"},\"children\":[]},{\"data\":{\"text\":\"设置密码\"},\"children\":[]}]},{\"data\":{\"text\":\"完善会员信息\"},\"children\":[{\"data\":{\"text\":\"姓名\"},\"children\":[]},{\"data\":{\"text\":\"身份证号\"},\"children\":[]},{\"data\":{\"text\":\"绑定银行卡\"},\"children\":[{\"data\":{\"text\":\"卡号\"},\"children\":[]},{\"data\":{\"text\":\"开户行（或者预留手机）\"},\"children\":[]}]},{\"data\":{\"text\":\"收货地址\"},\"children\":[{\"data\":{\"text\":\"选择省、市、区\"},\"children\":[]},{\"data\":{\"text\":\"填写详细地址\"},\"children\":[]}]}]},{\"data\":{\"text\":\"商城界面\"},\"children\":[{\"data\":{\"text\":\"产品展示\"},\"children\":[]},{\"data\":{\"text\":\"产品类别筛选\"},\"children\":[]},{\"data\":{\"text\":\"产品价格筛选\"},\"children\":[]}]},{\"data\":{\"text\":\"订单界面\"},\"children\":[{\"data\":{\"text\":\"选购产品套餐\"},\"children\":[]},{\"data\":{\"text\":\"点击支付\"},\"children\":[]}]},{\"data\":{\"text\":\"个人中心界面\"},\"children\":[{\"data\":{\"text\":\"显示个人信息\"},\"children\":[]},{\"data\":{\"text\":\"编辑头像\"},\"children\":[]},{\"data\":{\"text\":\"个人ID号码（会员卡号）\"},\"children\":[]},{\"data\":{\"text\":\"推荐与被推荐关系\"},\"children\":[{\"data\":{\"text\":\"我的推荐人\"},\"children\":[]},{\"data\":{\"text\":\"我推荐的人列表\"},\"children\":[]}]},{\"data\":{\"text\":\"收益显示\"},\"children\":[{\"data\":{\"text\":\"我的现金\"},\"children\":[]},{\"data\":{\"text\":\"我的积分\"},\"children\":[]},{\"data\":{\"text\":\"收益明细显示\"},\"children\":[{\"data\":{\"text\":\"推荐奖\"},\"children\":[]},{\"data\":{\"text\":\"日分红\"},\"children\":[]},{\"data\":{\"text\":\"月分红\"},\"children\":[]}]}]},{\"data\":{\"text\":\"商品管理\"},\"children\":[{\"data\":{\"text\":\"商品上传\"},\"children\":[{\"data\":{\"text\":\"商品名称\"},\"children\":[]},{\"data\":{\"text\":\"商品图片\"},\"children\":[]},{\"data\":{\"text\":\"商品库存\"},\"children\":[]},{\"data\":{\"text\":\"选择商品价格\"},\"children\":[]},{\"data\":{\"text\":\"商品详情\"},\"children\":[]}]},{\"data\":{\"text\":\"商品删除\"},\"children\":[]},{\"data\":{\"text\":\"商品上传和删除需后台审核\"},\"children\":[]}]}]},{\"data\":{\"text\":\"商城级别\"},\"children\":[{\"data\":{\"text\":\"500元\"},\"children\":[]},{\"data\":{\"text\":\"2000元\"},\"children\":[]},{\"data\":{\"text\":\"4000元\"},\"children\":[]},{\"data\":{\"text\":\"40000元\"},\"children\":[]},{\"data\":{\"text\":\"40万元\"},\"children\":[]},{\"data\":{\"text\":\"超过2000元有代理权限\"},\"children\":[]},{\"data\":{\"text\":\"购买哪个级别的商品就可以上传哪个价格的商品，向下兼容\"},\"children\":[]},{\"data\":{\"text\":\"会员升级只需要补差价就可以\"},\"children\":[]}]},{\"data\":{\"text\":\"奖励制度\"},\"children\":[{\"data\":{\"text\":\"500元级别\"},\"children\":[{\"data\":{\"text\":\"直推\"},\"children\":[{\"data\":{\"text\":\"订单金额的30%现金\"},\"children\":[]},{\"data\":{\"text\":\"每500元一个积分，被推广人购买满多少个500，就有多少积分\"},\"children\":[]}]},{\"data\":{\"text\":\"日分红\"},\"children\":[{\"data\":{\"text\":\"平台每天总收入的订单额30%平均分给我们的会员。分红金额累积到订单的2.5倍时，此会员的推广码作废（不再享有通过此推广码进来的会员的提成和积分）也不再享有月分红奖励。如需启动，可重新购买产品，对于长时间不续费的会员，后台管理员有删除该会员的权限。\"},\"children\":[]}]},{\"data\":{\"text\":\"月分红\"},\"children\":[{\"data\":{\"text\":\"平台总营业额的5%，按照会员积分加权分红\"},\"children\":[]}]},{\"data\":{\"text\":\"提现手续费5%\"},\"children\":[]}]},{\"data\":{\"text\":\"代理级别\"},\"children\":[{\"data\":{\"text\":\"直推\"},\"children\":[{\"data\":{\"text\":\"订单金额的30%现金\"},\"children\":[]},{\"data\":{\"text\":\"每500元一个积分，被推广人购买满多少个500，就有多少积分\"},\"children\":[]}]},{\"data\":{\"text\":\"日分红\"},\"children\":[]},{\"data\":{\"text\":\"月分红\"},\"children\":[]},{\"data\":{\"text\":\"购物折扣\"},\"children\":[{\"data\":{\"text\":\"代理\\r\\n2千     4千   4万      40万\\r\\n95折  9折    85折    8折\"},\"children\":[]}]}]},{\"data\":{\"text\":\"上传商品\"},\"children\":[{\"data\":{\"text\":\"产品分为平台产品和会员上传产品两类，会员上传产品必须经过平台审核，会员B扫A的二维码进入商城后，若B购买平台产品，则A享受B购买金额30%提成和500倍数的积分。若B购买A商家产品，则A享受40%成本款和500倍数的积分。若B购买其他商家产品，则A只享受500倍数的积分，不享受提成，此时，其他商家仅享受40%成本款\"},\"children\":[]}]}]}]},{\"data\":{\"text\":\"云帮主\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"f7786c566adf5952cc317459ac118d75","csrf_token":"3c4abdc92c339d9ce46b90c1201715c6"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by evanzou** [comment]
我也是这个问题，应该是脑图网络方面的问题，目前只有一个暂时的办法，就是每次报错的时候，把报错提示叉掉，然后按ctrl+s手动保存，这样就不用每次刷新页面了。 这样虽然好点，但也挺麻烦的，希望开发人员早点解决这个问题。

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
