### ISSUE TITLE
错误：500

### ISSUE THREAD

**Issue by bjkonglu** [fex-team/kityminder-editor#468]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"ca7b626ca24f\",\"created\":1502075240,\"text\":\"SparkContext\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu2a1iysqg0\",\"created\":1502078188310,\"text\":\"TaskScheduler\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu2b6xdb9k0\",\"created\":1502078278429,\"text\":\"创建TaskSchedulerImpl\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu2emw1aps0\",\"created\":1502078548270,\"text\":\"根据SparkConf获取任务需要的配置信息，CPU数、调度模式等\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu2g271amg0\",\"created\":1502078659951,\"text\":\"创建TaskResultGetter，以线程池形式对Worker上的Excutor发送的Task的执行结果进行处理\",\"progress\":1,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu2bsa874g0\",\"created\":1502078324919,\"text\":\"根据不同的部署模式生成不同的SchedulerBackend\",\"layout_right_offset\":{\"x\":-10,\"y\":7},\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu2manqgr40\",\"created\":1502079148560,\"text\":\"LocalSchedulerBackend采用Scoket方式与LauncherServer进行通信\",\"priority\":1,\"progress\":1,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu2dquzu7k0\",\"created\":1502078478550,\"text\":\"TaskSchedulerImpl初始化\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu2q3syqoo0\",\"created\":1502079447095,\"text\":\"TaskSchedulerImpl持有SchedulerBackend引用\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu2q8hnbrs0\",\"created\":1502079457295,\"text\":\"创建Pool(调度队列、调度算法以及TaskSetManager集合)\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu2qe6722w0\",\"created\":1502079469663,\"text\":\"创建FIFOSchedulerBuilder或其他类型Builder操作Pool中的队列\",\"progress\":1,\"priority\":1,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu66b2caeo0\",\"created\":1502089180056,\"text\":\"创建DAGScheduler\",\"progress\":7,\"priority\":1,\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beu2vxi65ls0\",\"created\":1502079903567,\"text\":\"DAGScheduler\",\"layout_mind_offset\":{\"x\":-2,\"y\":88},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu51qgg2740\",\"created\":1502086000630,\"text\":\"数据结构\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu53dqo4ko0\",\"created\":1502086129678,\"text\":\"jobId与stageId关系\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu53pwznqo0\",\"created\":1502086156182,\"text\":\"Stage、ActiveJob\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu53zybqog0\",\"created\":1502086178030,\"text\":\"缓存RDD的partitions的位置信息\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu51wf6bwo0\",\"created\":1502086013614,\"text\":\"事件处理器DAGSchedulerEventProcessLoop？\",\"progress\":1,\"priority\":1,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8ravx75s0\",\"created\":1502096467535,\"text\":\"成员变量：listenerBus\",\"priority\":\"5\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8sh68cdk0\",\"created\":1502096559583,\"text\":\"成员变量：BlockManagerMaster(存在Endpoint)\",\"priority\":\"5\",\"progress\":1,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu2x3yon2o0\",\"created\":1502079995990,\"text\":\"Hadoop相关配置及Executor环境变量\",\"layout_mind_offset\":{\"x\":-43,\"y\":-60},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu2xx017400\",\"created\":1502080059198,\"text\":\"SparkHadoopUtil获取Hadoop相关配置信息\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu2yspowbk0\",\"created\":1502080128230,\"text\":\"executorEnvs包含Executor环境变量\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu574feaw80\",\"created\":1502086422862,\"text\":\"TaskScheduler启动\",\"layout_mind_offset\":{\"x\":-9,\"y\":-3},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu5ll3igb40\",\"created\":1502087556247,\"text\":\"SchedulerBacken(Endpoint)启动\",\"layout_right_offset\":{\"x\":25,\"y\":-24},\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu5m5gcrsg0\",\"created\":1502087600559,\"text\":\"LocalEndpoint创建与注册\",\"progress\":9,\"layout_right_offset\":{\"x\":9,\"y\":-43},\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu5moc9k6g0\",\"created\":1502087641671,\"text\":\"通过ListenerBus引用向事件队列增加事件\",\"progress\":9,\"layout_right_offset\":{\"x\":-5,\"y\":32},\"expandState\":\"expand\"},\"children\":[]}]}]},{\"data\":{\"id\":\"beu6a9nj1ig0\",\"created\":1502089490440,\"text\":\"创建HeartbeatReceiver(Endpoint)\",\"layout_mind_offset\":{\"x\":571,\"y\":269},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu6c5ubnvc0\",\"created\":1502089638872,\"text\":\"成员变量scheduler：TaskScheduler\",\"progress\":8,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu6md51ysg0\",\"created\":1502090438400,\"text\":\"启动测量系统MetricsSystem\",\"layout_mind_offset\":{\"x\":500,\"y\":280},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu6nfdoppk0\",\"created\":1502090521640,\"text\":\"注册Sources:告诉测量系统数据从哪收集测量数据\",\"layout_right_offset\":{\"x\":65,\"y\":14},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu6pkj62n40\",\"created\":1502090689584,\"text\":\"注册Sinks:告诉测量系统往哪里输出测量数据\",\"layout_right_offset\":{\"x\":48,\"y\":24},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu6qweyrxc0\",\"created\":1502090793815,\"text\":\"给Sinks增加Jetty的ServletContextHandler:为了SparkUI访问测量数据\",\"layout_right_offset\":{\"x\":59,\"y\":14},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu79t35vi80\",\"created\":1502092275490,\"text\":\"创建执行环境SparkEnv\",\"layout_mind_offset\":{\"x\":524,\"y\":-255},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"beu7byzrvag0\",\"created\":1502092445074,\"text\":\"创建安全管理器SecurityManager\",\"layout_right_offset\":{\"x\":6,\"y\":-3},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7cldz7c80\",\"created\":1502092493822,\"text\":\"Netty消息系统\",\"layout_right_offset\":{\"x\":31,\"y\":28},\"priority\":1,\"progress\":1,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7jua2o140\",\"created\":1502093061726,\"text\":\"实例化ShufferManager\",\"layout_right_offset\":{\"x\":209.00001057982445,\"y\":15.000007450580597},\"progress\":8,\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu7uz8tvnc0\",\"created\":1502093934541,\"text\":\"创建广播管理器BroadcastManager:存储配置信息到本地，为了容灾会复制到其他节点\",\"progress\":6,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu7d490aio0\",\"created\":1502092534881,\"text\":\"map任务输出跟踪器mapOutputTracker\",\"layout_right_offset\":{\"x\":53,\"y\":49},\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu7fsl54ds0\",\"created\":1502092744585,\"text\":\"Driver:MapOutputTrackerMaster(Endpoint)\",\"layout_right_offset\":{\"x\":-3,\"y\":-15},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7i26078o0\",\"created\":1502092922166,\"text\":\"Worker:MapOutputTrackerWorker(Lookup Endpoint Ref)\",\"layout_right_offset\":{\"x\":-7,\"y\":-22},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu7krxo17c0\",\"created\":1502093134987,\"text\":\"块传输服务BlockTransferService\",\"layout_right_offset\":{\"x\":35,\"y\":70},\"progress\":5,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7nbiyfo00\",\"created\":1502093334361,\"text\":\"创建块管理器BlockManager\",\"layout_right_offset\":{\"x\":86,\"y\":147},\"progress\":8,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7qdhcx0g0\",\"created\":1502093573711,\"text\":\"BlockManagerMaster\",\"layout_right_offset\":{\"x\":93,\"y\":-10},\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu7r1n9ub40\",\"created\":1502093626311,\"text\":\"Driver:创建BlockManagerMasterEndpoint\",\"layout_right_offset\":{\"x\":67,\"y\":-21},\"progress\":7,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7tdoxi140\",\"created\":1502093809261,\"text\":\"Worker:寻找BlockManagerMasterEndpoint Ref\",\"layout_right_offset\":{\"x\":24,\"y\":6},\"progress\":7,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu7wtf8hdk0\",\"created\":1502094078596,\"text\":\"创建MetricsSystem\",\"layout_right_offset\":{\"x\":30,\"y\":70},\"progress\":7,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu7xjphgeg0\",\"created\":1502094135812,\"text\":\"创建SparkEnv\",\"layout_right_offset\":{\"x\":27,\"y\":115},\"progress\":8,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu7zegiw680\",\"created\":1502094281115,\"text\":\"SparkUI\",\"layout_mind_offset\":{\"x\":486,\"y\":-266},\"expandState\":\"collapse\",\"layout_right_offset\":{\"x\":-90,\"y\":161}},\"children\":[{\"data\":{\"id\":\"beu82htmr080\",\"created\":1502094523530,\"text\":\"listenerBus:监听器模型\",\"layout_right_offset\":{\"x\":57,\"y\":-63},\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu879972f40\",\"created\":1502094896701,\"text\":\"事件阻塞队列\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu87r6v9h40\",\"created\":1502094935742,\"text\":\"监听器数组\",\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu883dgutc0\",\"created\":1502094962263,\"text\":\"事件匹配监听器线程\",\"progress\":8,\"layout_right_offset\":{\"x\":2,\"y\":7},\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu8dt5eie80\",\"created\":1502095410192,\"text\":\"XXXListener:监听listenerBus中的事件获取数据\",\"layout_right_offset\":{\"x\":50,\"y\":-53},\"progress\":8,\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"beu8gnk01r40\",\"created\":1502095633107,\"text\":\"JobProgressListener\",\"progress\":2,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8gyy6z940\",\"created\":1502095657909,\"text\":\"EnvironmentListener\",\"layout_right_offset\":{\"x\":2,\"y\":-2},\"progress\":2,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8hcdzx600\",\"created\":1502095687163,\"text\":\"StorageStatusListener\",\"progress\":2,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8huhcp280\",\"created\":1502095726548,\"text\":\"ExecutorListener\",\"progress\":2,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8i065k6w0\",\"created\":1502095738932,\"text\":\"StorageListener\",\"progress\":2,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8i88ty8o0\",\"created\":1502095756508,\"text\":\"....\",\"progress\":1,\"expandState\":\"expand\"},\"children\":[]}]},{\"data\":{\"id\":\"beu8f6ubrcg0\",\"created\":1502095518362,\"text\":\"SparkUI的创建与初始化\",\"layout_right_offset\":{\"x\":34,\"y\":-33},\"progress\":9,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"beu8fxw8fbs0\",\"created\":1502095577250,\"text\":\"Spark UI页面布局与展示\",\"layout_right_offset\":{\"x\":34,\"y\":-24},\"progress\":1,\"priority\":9,\"expandState\":\"expand\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"321c6e241a3e64a96e7d9a1425c1fa46","csrf_token":"8eb6b08c69e4fdb07a4c6f353f8127bc"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36

**Comment by evanzou** [comment]
我也是这个问题，应该是脑图网络方面的问题，目前只有一个暂时的办法，就是每次报错的时候，把报错提示叉掉，然后按ctrl+s手动保存，这样就不用每次刷新页面了。 这样虽然好点，但也挺麻烦的，希望开发人员早点解决这个问题。

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
