### ISSUE TITLE
chrome浏览器报错误500

### ISSUE THREAD

**Issue by evanzou** [fex-team/kityminder-editor#469]
每隔十几秒就报一次错误500

**Comment by evanzou** [comment]
我也是这个问题，应该是脑图网络方面的问题，目前只有一个暂时的办法，就是每次报错的时候，把报错提示叉掉，然后按ctrl+s手动保存，这样就不用每次刷新页面了。 这样虽然好点，但也挺麻烦的，希望开发人员早点解决这个问题。

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
