### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yhf213** [fex-team/kityminder-editor#474]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"b12236c29256\",\"created\":1502343550,\"text\":\"区块链应用0810\"},\"children\":[{\"data\":{\"id\":\"bewogr7g1800\",\"created\":1502343898726,\"text\":\"Gartner\"},\"children\":[{\"data\":{\"id\":\"bewoiykmrmg0\",\"created\":1502344071490,\"text\":\"为从区块链中获益，这项技术必须向一个不信任的环境增添信任，而且要利用一种分布式分类账本的机制。\"},\"children\":[]},{\"data\":{\"id\":\"bewoiz14x5s0\",\"created\":1502344072488,\"text\":\"但经验证，只有比特币与以太坊才具备一定的规模。尽管现在有70多种不同的区块链平台技术可以使用，\\n但大多数区块链平台在未来24个月的时间内都还是处于不成熟的状态\"},\"children\":[]},{\"data\":{\"id\":\"bewoizkj0qo0\",\"created\":1502344073660,\"text\":\"确保你对于区块链所制定的当前计划与技术当前的成熟度以及发展能力保持相互关联。\"},\"children\":[]},{\"data\":{\"id\":\"bewomqe1as80\",\"created\":1502344367133,\"text\":\"区块链往往伴随着大量的炒作，这就意味着这项技术可以实现的与其有望实现的可能会不相符。\"},\"children\":[]},{\"data\":{\"id\":\"bewomqh7me00\",\"created\":1502344367325,\"text\":\"花点时间去确定实际上区块链是否是一个很好的企业解决方案（以其目前的形式来看），以及它与你的\\n信息管理需求的关系。\"},\"children\":[]},{\"data\":{\"id\":\"bewomqjpf0g0\",\"created\":1502344367476,\"text\":\"区块链不够成熟，而且也缺少标准，从而无法合理保证实现竞争性分类账本与平台间的互操作性\"},\"children\":[]},{\"data\":{\"id\":\"bewoos0r0g80\",\"created\":1502344527412,\"text\":\"不要认为你现在正在使用的技术会长长久久的提供支持，同时还要意识到最好的选择仍未出现。因此，应该将\\n当前的各种可选技术作为一种短期试验性的选择\"},\"children\":[]},{\"data\":{\"id\":\"bewoos3fw1s0\",\"created\":1502344527574,\"text\":\"测试智能合约时要始终小心谨慎，并确保你的法务与合规团队能够提供政策与操作风险管理监督。\"},\"children\":[]},{\"data\":{\"id\":\"bewoprodkqw0\",\"created\":1502344605028,\"text\":\"区块链带来了很多关于治理的问题以及政治、社会和组织问题，而这些问题可能会为当前的商业模式带来巨大的成本。\"},\"children\":[]},{\"data\":{\"id\":\"bewoqvwcqxs0\",\"created\":1502344692581,\"text\":\"眼下，知识可能是从区块链项目中获得的唯一价值，因此要确保这些知识是有价值的，并记录下来传达给高级管理人员\"},\"children\":[]}]},{\"data\":{\"id\":\"bewogrroiiw0\",\"created\":1502343899950,\"text\":\"Scry.info\"},\"children\":[{\"data\":{\"id\":\"bewor1vjzls0\",\"created\":1502344705594,\"text\":\"Scry开源协议在创建全新的数据化流动智能合约市场，让一切数据可量化并自动通过智能合约进行交易。\"},\"children\":[]},{\"data\":{\"id\":\"bewor2ai1eo0\",\"created\":1502344706497,\"text\":\"Scry的协议层可以便捷的帮助传统互联网数据注入合约构建自己的区块链应用产品。同时Scry分类计算具备实时\\n学习的能力，它能够读取结构化和非结构化的数据\"},\"children\":[]},{\"data\":{\"id\":\"bewor2d98vs0\",\"created\":1502344706664,\"text\":\"Scry协议底层能够补充和提高个人企业与认知的数据决策，提醒人们注意预料之外的种种联系，并对导向\\n正确决策的各种可能性进行量化\"},\"children\":[]}]},{\"data\":{\"id\":\"bewogrumcfk0\",\"created\":1502343900128,\"text\":\"Overstock\"},\"children\":[{\"data\":{\"id\":\"bewoy5lt1uo0\",\"created\":1502345262261,\"text\":\"美国知名在线购物网站Overstock.com宣布正式接受以太坊支付。还将支持其他主要加密货币的支付，包括比特币、\\nBitcion Cash、莱特币、达氏币以及Monero。\"},\"children\":[]},{\"data\":{\"id\":\"bewoy5zz0i00\",\"created\":1502345263117,\"text\":\"Overstock是一家致力于创新区块链技术的公司，同时也是第一家通过区块链互联网发行126000股票的公开交易机构。\"},\"children\":[]},{\"data\":{\"id\":\"bewoy62cimw0\",\"created\":1502345263261,\"text\":\"产品的美元成本在购买的时候用汇率转换成比特币。因此，虽然比特币的数量可能不同于购买时的数量，\\n但它将代表每笔交易时准确的美元价值\"},\"children\":[]},{\"data\":{\"id\":\"bewp03s5q1c0\",\"created\":1502345415019,\"text\":\"ShapeShift为实用数字货币的用户提供了一种便捷的支付方式，让他们可以在各个连锁店之间进行无缝和私密的交易\"},\"children\":[]}]},{\"data\":{\"id\":\"bewogrxbng00\",\"created\":1502343900291,\"text\":\"澳大利亚\"},\"children\":[{\"data\":{\"id\":\"bewp1tmdg5s0\",\"created\":1502345549630,\"text\":\"澳大利亚的立法者正在推动比特币作为官方货币。提议中还包括呼吁澳大利亚央行考虑推出自己的加密货币。\"},\"children\":[]},{\"data\":{\"id\":\"bewp1tyg5u80\",\"created\":1502345550360,\"text\":\"今年，澳大利亚储备银行透露，它已经创建了一个专注于技术的内部工作小组。\"},\"children\":[]},{\"data\":{\"id\":\"bewp3fky63k0\",\"created\":1502345675797,\"text\":\"并不是所有的澳大利亚议会成员都同意扩大加密货币的使用，其中甚至还包括参与区块链倡议的各方。\"},\"children\":[]}]},{\"data\":{\"id\":\"bewp1s5ik3c0\",\"created\":1502345546434,\"text\":\"VC\"},\"children\":[{\"data\":{\"id\":\"bewp5hakugw0\",\"created\":1502345836252,\"text\":\"加密货币和区块链领域中并非所有VC都是寻求参与ICO以及为了短期最大利润而迅速转手ICO代币。很多VC投资者\\n都采取了“耐心资本”的长期策略来获得最大化利润。\"},\"children\":[]},{\"data\":{\"id\":\"bewp5ho21mg0\",\"created\":1502345837067,\"text\":\"比特币领域的绝大多数VC公司都为交易所、交易平台和钱包的必要基础设施的形成做出了贡献。\"},\"children\":[]},{\"data\":{\"id\":\"bewp5hqg95k0\",\"created\":1502345837212,\"text\":\"一些VC公司也许把一些加密货币项目当成了短线投资，而另一些VC公司和天使投资人是真的看上了\\n比特币、以太坊和其他加密货币所提供的技术。\"},\"children\":[]}]},{\"data\":{\"id\":\"bewp1s9ri140\",\"created\":1502345546691,\"text\":\"墨链\"},\"children\":[{\"data\":{\"id\":\"bewp7j7gq2w0\",\"created\":1502345997146,\"text\":\"Fabric在今年7月发布了1.0版本，由于其更好的权限控制和安全保障，吸引了垂直切入\\n大文化产业的墨链InkChain的关注\"},\"children\":[]},{\"data\":{\"id\":\"bewp7jm3n400\",\"created\":1502345998031,\"text\":\"墨链InkChain是以“纸贵版权”团队为核心打造的，面向大文化产业的自主区块链底层和文化资产交易\\n平台，以及由此构建的分布式经济生态\"},\"children\":[]},{\"data\":{\"id\":\"bewp8u52oco0\",\"created\":1502346099310,\"text\":\"截至2017年7月，纸贵的版权数据规模达500万件，版权登记量突破30万件，其中包括了贾平凹、潘朴、\\n韩鲁华等等重要用户的原创作品。\"},\"children\":[]},{\"data\":{\"id\":\"bewp8u7w71k0\",\"created\":1502346099481,\"text\":\"2016 年以影视大片、动漫娱乐、文艺小说等新兴文创产品为代表的文化企业实现营收达 80314 亿元，\\n比上年增长 7.5%，而这个增速还在持续提升。\"},\"children\":[]},{\"data\":{\"id\":\"bewpbbzn9x40\",\"created\":1502346294892,\"text\":\"墨链独创的POI算法，目的是为了激励各种各样的交互行为，获得正向反馈，从而促进社区繁荣。\"},\"children\":[]},{\"data\":{\"id\":\"bewpbc2ls7c0\",\"created\":1502346295071,\"text\":\"墨链的第一批节点将包括墨链文创交易所、政府部门、IP 上下游产业链中的相关参与者、公有云服务商、文创类应用等。\"},\"children\":[]}]},{\"data\":{\"id\":\"bewp1sclw600\",\"created\":1502345546863,\"text\":\"闪电网络\"},\"children\":[{\"data\":{\"id\":\"bewpdp023fc0\",\"created\":1502346479944,\"text\":\"比特币头8年产生的140GB内存就已经让我们焦头烂额了，而且这8年的用户数量还算少的（以后会越来越多）\"},\"children\":[]},{\"data\":{\"id\":\"bewpdpfbjcw0\",\"created\":1502346480866,\"text\":\"用户需求的增加只会抹杀隔离见证创造的优势，并抬高手续费。\"},\"children\":[]},{\"data\":{\"id\":\"bewpdphopy80\",\"created\":1502346481010,\"text\":\"唯一能够实现最佳扩容的方法就是Pieter Wuille提出的每年实现17.7%的容量增长。\"},\"children\":[]},{\"data\":{\"id\":\"bewpdpkeo680\",\"created\":1502346481174,\"text\":\"分支主题\"},\"children\":[]}]},{\"data\":{\"id\":\"bewp1sewmio0\",\"created\":1502345547002,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"bewp1sh7jvk0\",\"created\":1502345547141,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"bewp1sjhw2o0\",\"created\":1502345547279,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"bewp1slpqhc0\",\"created\":1502345547413,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"bewp1snmo740\",\"created\":1502345547529,\"text\":\"分支主题\"},\"children\":[]},{\"data\":{\"id\":\"bewp1spklhc0\",\"created\":1502345547647,\"text\":\"分支主题\"},\"children\":[]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"cac62985549fd2a2c692c94852bf7010","csrf_token":"ce7e5a931d74aaba4f8971b4bd600685"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
