### ISSUE TITLE
http 500

### ISSUE THREAD

**Issue by HyiiiiiiiiaiiiiiiniiiiL** [fex-team/kityminder-editor#475]
绘制完成保存时，报server  error
{"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"bdd91d875287\",\"created\":1502261027,\"text\":\"试单馆\"},\"children\":[{\"data\":{\"id\":\"bevv3gaw6p4o\",\"created\":1502261044069,\"text\":\"后台添加广告位\"},\"children\":[{\"data\":{\"id\":\"bevv5o8pr484\",\"created\":1502261218080,\"text\":\"1.对新建广告位字段填写完整性测试\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevvy1ska6wc\",\"created\":1502263441775,\"text\":\"完整填写字段的测试\",\"layout_filetree-down_offset\":{\"x\":-8,\"y\":1},\"background\":\"#c2d69b\"},\"children\":[]},{\"data\":{\"id\":\"bevvy9kgscw8\",\"created\":1502263458699,\"text\":\"对必须填写字段缺失的测试\",\"background\":\"#c2d69b\"},\"children\":[]},{\"data\":{\"id\":\"bevvyj2hfc0g\",\"created\":1502263479380,\"text\":\"对非必须填写字段缺失的测试\",\"background\":\"#c2d69b\"},\"children\":[]}]},{\"data\":{\"id\":\"bevv72kyppko\",\"created\":1502261327660,\"text\":\"2.对新建广告位每个字段测试\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevv82l4lx4w\",\"created\":1502261406034,\"text\":\"广告标题(对应产品名)\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevv8nyt9z40\",\"created\":1502261452574,\"text\":\"对广告标题长度进行测试\",\"background\":\"#d6e3bc\"},\"children\":[{\"data\":{\"id\":\"bevvvjo43i0w\",\"created\":1502263245595,\"text\":\"正常长度的测试（刚好显示在界面上，无需换行）\",\"background\":\"#eaf1dd\"},\"children\":[]},{\"data\":{\"id\":\"bevvvqafh0oo\",\"created\":1502263260005,\"text\":\"较长长度的测试(测试当标题长度过长时，是否会显示......)\",\"background\":\"#eaf1dd\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevw2jqm2bk0\",\"created\":1502263794295,\"text\":\"权重：决定广告的显示\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevw4n7we9kw\",\"created\":1502263958599,\"text\":\"相同权重值排序后广告的显示\",\"background\":\"#d6e3bc\"},\"children\":[]},{\"data\":{\"id\":\"bevw5jte2s08\",\"created\":1502264029556,\"text\":\"不同权重值排序后广告的显示\",\"background\":\"#d6e3bc\"},\"children\":[]}]},{\"data\":{\"id\":\"bevw83drubk0\",\"created\":1502264228876,\"text\":\"扩展字段\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevwa1v1qp4o\",\"created\":1502264382295,\"text\":\"扩展字段完整填写测试\",\"background\":\"#d6e3bc\"},\"children\":[{\"data\":{\"id\":\"bevwats4xzk8\",\"created\":1502264443069,\"text\":\"扩展各个字段正常填写测试\",\"background\":\"#eaf1dd\"},\"children\":[{\"data\":{\"id\":\"bevwrdc2hjsc\",\"created\":1502265739459,\"text\":\"字段1：企业id\",\"background\":\"#eaf1dd\"},\"children\":[{\"data\":{\"id\":\"bevwxocdadk4\",\"created\":1502266233607,\"text\":\"添加相同id的测试\"},\"children\":[]},{\"data\":{\"id\":\"bevwy26vu00g\",\"created\":1502266263750,\"text\":\"添加不同id的测试\"},\"children\":[]}]},{\"data\":{\"id\":\"bevwsh1qif40\",\"created\":1502265825906,\"text\":\"字段2:产品规格\",\"background\":\"#eaf1dd\"},\"children\":[]},{\"data\":{\"id\":\"bevwsoipcagw\",\"created\":1502265842169,\"text\":\"字段3:产地\",\"background\":\"#eaf1dd\"},\"children\":[{\"data\":{\"id\":\"bevwtw93ahsk\",\"created\":1502265937367,\"text\":\"正常长度：不会换行的长度\"},\"children\":[]},{\"data\":{\"id\":\"bevwu463hk8o\",\"created\":1502265954600,\"text\":\"非正常长度：会换行的长度\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bevwaindw9c8\",\"created\":1502264418837,\"text\":\"扩展字段非完整填写测试\",\"background\":\"#d6e3bc\"},\"children\":[{\"data\":{\"id\":\"bevwux15pfk0\",\"created\":1502266017428,\"text\":\"不填写字段1，填写2,3\",\"background\":\"#eaf1dd\"},\"children\":[]},{\"data\":{\"id\":\"bevwvch2fywc\",\"created\":1502266051042,\"text\":\"填1，不填2，填3\",\"background\":\"#eaf1dd\"},\"children\":[]},{\"data\":{\"id\":\"bevwvxvnqts8\",\"created\":1502266097636,\"text\":\"填1，填2，不填3\",\"background\":\"#eaf1dd\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bewlj0s8j88c\",\"created\":1502335612973,\"text\":\"逛一逛广告位\",\"layout_filetree-down_offset\":{\"x\":0,\"y\":28}},\"children\":[{\"data\":{\"id\":\"bewll0cm3zks\",\"created\":1502335768757,\"text\":\"权重\"},\"children\":[]},{\"data\":{\"id\":\"bewlo8hl6mg4\",\"created\":1502336021564,\"text\":\"链接\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevx2a9sq00g\",\"created\":1502266594798,\"text\":\"手机号码\"},\"children\":[{\"data\":{\"id\":\"bevx2wnrlu04\",\"created\":1502266643531,\"text\":\"已绑定\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevx3f222vk8\",\"created\":1502266683578,\"text\":\"是否正常显示手机号\",\"background\":\"#c2d69b\"},\"children\":[]},{\"data\":{\"id\":\"bevx3l1vviwc\",\"created\":1502266696628,\"text\":\"是否可修改\",\"background\":\"#c2d69b\"},\"children\":[]}]},{\"data\":{\"id\":\"bevx34y7cv4g\",\"created\":1502266661577,\"text\":\"未绑定\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevx4aqojls0\",\"created\":1502266752547,\"text\":\"不输入手机号\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevx4mkhk7k8\",\"created\":1502266778294,\"text\":\"提示：请输入手机号\",\"background\":\"#d6e3bc\"},\"children\":[]}]},{\"data\":{\"id\":\"bevx4irkmawo\",\"created\":1502266770015,\"text\":\"输入手机号\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevx4r0p5eok\",\"created\":1502266787981,\"text\":\"输入正确格式的手机号\",\"background\":\"#d6e3bc\"},\"children\":[]},{\"data\":{\"id\":\"bevx4xub85s8\",\"created\":1502266802832,\"text\":\"输入非正确格式手机号\",\"background\":\"#d6e3bc\"},\"children\":[{\"data\":{\"id\":\"bevx54r9jc0k\",\"created\":1502266817886,\"text\":\"提示：请输入正确手机号\",\"background\":\"#eaf1dd\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bevx9w0pki88\",\"created\":1502267190686,\"text\":\"程序流程测试\"},\"children\":[{\"data\":{\"id\":\"bevxcc14w34s\",\"created\":1502267382269,\"text\":\"点击广告，公司名，Logo\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevxh7rs76og\",\"created\":1502267764817,\"text\":\"商铺信息\",\"background\":\"#c2d69b\"},\"children\":[]}]},{\"data\":{\"id\":\"bevxd04nq9cs\",\"created\":1502267434725,\"text\":\"点击申请使用\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevxhg07f6wo\",\"created\":1502267782741,\"text\":\"支付界面\",\"background\":\"#c2d69b\"},\"children\":[]}]},{\"data\":{\"id\":\"bevxefp8x28g\",\"created\":1502267546986,\"text\":\"支付界面\",\"background\":\"#76923c\"},\"children\":[{\"data\":{\"id\":\"bevxeoq8lswk\",\"created\":1502267566637,\"text\":\"未登录\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevxetcyj604\",\"created\":1502267576718,\"text\":\"已注册\",\"background\":\"#eaf1dd\"},\"children\":[{\"data\":{\"id\":\"bevy2s6609sk\",\"created\":1502269454870,\"text\":\"登录成功后回到支付界面\"},\"children\":[{\"data\":{\"id\":\"bevy343p28g8\",\"created\":1502269480842,\"text\":\"支付成功显示订单详细信息，并发送短信，并给  返回试单馆按钮\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevy1xnbxz40\",\"created\":1502269388428,\"text\":\"未注册\"},\"children\":[{\"data\":{\"id\":\"bevy2gtkuq04\",\"created\":1502269430164,\"text\":\"注册后登录\"},\"children\":[{\"data\":{\"id\":\"bevy3djsk5k4\",\"created\":1502269501406,\"text\":\"登录成功后回到支付界面\"},\"children\":[{\"data\":{\"id\":\"bevy3lrl200g\",\"created\":1502269519292,\"text\":\"支付成功显示订单详细信息，并发送短信，并给  返回试单馆按钮\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bevxepv5qowg\",\"created\":1502267569111,\"text\":\"已登录\",\"background\":\"#c2d69b\"},\"children\":[{\"data\":{\"id\":\"bevxf1qjwso4\",\"created\":1502267594954,\"text\":\"提交订单\",\"background\":\"#eaf1dd\"},\"children\":[{\"data\":{\"id\":\"bevy0tuq34wk\",\"created\":1502269301803,\"text\":\"支付成功显示订单详细信息，并发送短信，并给  返回试单馆按钮\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bewlc9ixc6os\",\"created\":1502335083452,\"text\":\"兼容性测试\",\"layout_bottom_offset\":{\"x\":-179,\"y\":-4}},\"children\":[{\"data\":{\"id\":\"bewlcddx84gk\",\"created\":1502335091857,\"text\":\"IE8,IE10,火狐，chrom\"},\"children\":[]}]},{\"data\":{\"id\":\"bewlohrl3vkg\",\"created\":1502336041760,\"text\":\"UI测试\",\"layout_bottom_offset\":{\"x\":-210,\"y\":0}},\"children\":[{\"data\":{\"id\":\"bewloy2l5340\",\"created\":1502336077254,\"text\":\"顶端导航固定测试\",\"background\":\"#76923c\"},\"children\":[]},{\"data\":{\"id\":\"bewlpey17ogg\",\"created\":1502336113984,\"text\":\"加商城页头页尾\",\"background\":\"#76923c\"},\"children\":[]},{\"data\":{\"id\":\"bewlpvdrh1k4\",\"created\":1502336149763,\"text\":\"加入试单馆，联系我们，返回顶部右侧边固定\",\"background\":\"#76923c\"},\"children\":[]}]},{\"data\":{\"id\":\"bewlxfxv3mwo\",\"created\":1502336743064,\"text\":\"URL测试\",\"layout_bottom_offset\":{\"x\":-156.24999767169356,\"y\":0}},\"children\":[{\"data\":{\"id\":\"bewlxwra480g\",\"created\":1502336779671,\"text\":\"主页    url：mall.smm.cn/activity/shidan\"},\"children\":[]},{\"data\":{\"id\":\"bewlya6ssewc\",\"created\":1502336808907,\"text\":\"web支付前   url：www.smm.cn/activity/orderpay\"},\"children\":[]},{\"data\":{\"id\":\"bewlyili6jso\",\"created\":1502336827211,\"text\":\"web支付成功   url：www.smm.cn/activity/paysuccess\"},\"children\":[]},{\"data\":{\"id\":\"bewlymgyd6gw\",\"created\":1502336835643,\"text\":\"h5支付前  m.smm.cn/mall/activity/orderpay\"},\"children\":[]},{\"data\":{\"id\":\"bewlyquspios\",\"created\":1502336845187,\"text\":\"h5支付成功   m.smm.cn/mall/activity/paysuccess\"},\"children\":[]}]}]},\"template\":\"filetree\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"63cc0ec816db59d1e88912adce662d99","csrf_token":"f078f24f29ef0d2d447122e3e16d4f60"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
