### ISSUE TITLE
经常会保存失败

### ISSUE THREAD

**Issue by shihp** [fex-team/kityminder-editor#476]
windows系统 chrome浏览器

错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"13e563c3122c\",\"created\":1502372230,\"text\":\"GO LANG 平台与架构\"},\"children\":[{\"data\":{\"id\":\"bewyi9oz2yg0\",\"created\":1502372228432,\"text\":\"系统\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bewyi8o6uhs0\",\"created\":1502372226207,\"text\":\"Linux\"},\"children\":[]},{\"data\":{\"id\":\"bewyi8o6rkw0\",\"created\":1502372226207,\"text\":\"FreeBSD\"},\"children\":[]},{\"data\":{\"id\":\"bewyi8o6tuw0\",\"created\":1502372226207,\"text\":\"Mac OS X（也称为 Darwin）\"},\"children\":[]}]},{\"data\":{\"id\":\"bewyih27ddc0\",\"created\":1502372244470,\"text\":\"编译器\"},\"children\":[{\"data\":{\"id\":\"bewyii28s480\",\"created\":1502372246648,\"text\":\"Go 原生编译器 gc\"},\"children\":[{\"data\":{\"id\":\"bewyipv7bds0\",\"created\":1502372263637,\"text\":\"支持windows\"},\"children\":[]}]},{\"data\":{\"id\":\"bewyim1qvew0\",\"created\":1502372255325,\"text\":\"非原生编译器 gccgo\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"15fc919c20515cf3b0f2844c98ec6b85","csrf_token":"effb0dbfbdc188d686f756db21589363"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by zhangbobell** [comment]
503 错误是服务器压力过大造成的，已经通过扩容解决，如果仍然有 503 错误弹出，请反馈，谢谢。
