### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xia296** [fex-team/kityminder-editor#477]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"ccf6fc7f09ef\",\"created\":1502243857,\"text\":\"淘支付\"},\"children\":[{\"data\":{\"id\":\"bevp0bxzs7c0\",\"created\":1502243872830,\"text\":\"商家\",\"expandState\":\"expand\",\"layout_right_offset\":{\"x\":-14,\"y\":-78}},\"children\":[{\"data\":{\"id\":\"bevp0ynrwc00\",\"created\":1502243922278,\"text\":\"我的店铺\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bevpjhqstxc0\",\"created\":1502245374375,\"text\":\"店铺设置\"},\"children\":[{\"data\":{\"id\":\"bevpk52nl1k0\",\"created\":1502245425157,\"text\":\"人均消费\"},\"children\":[]},{\"data\":{\"id\":\"bevpk8yoq140\",\"created\":1502245433625,\"text\":\"营业时间段（起止时分）\"},\"children\":[]},{\"data\":{\"id\":\"bevpkxqonkw0\",\"created\":1502245487560,\"text\":\"店铺电话\"},\"children\":[]},{\"data\":{\"id\":\"bevpl8n30mw0\",\"created\":1502245511287,\"text\":\"店铺介绍\"},\"children\":[]},{\"data\":{\"id\":\"bevplt41ml40\",\"created\":1502245555848,\"text\":\"店铺地址\"},\"children\":[]},{\"data\":{\"id\":\"bevpm4fntls0\",\"created\":1502245580495,\"text\":\"其它服务\"},\"children\":[{\"data\":{\"id\":\"bevpm8ki73k0\",\"created\":1502245589495,\"text\":\"WiFi\"},\"children\":[]},{\"data\":{\"id\":\"bevpmbxte1c0\",\"created\":1502245596831,\"text\":\"免费停车\"},\"children\":[]},{\"data\":{\"id\":\"bexd6l39ne80\",\"created\":1502413629519,\"text\":\"茶水\"},\"children\":[]},{\"data\":{\"id\":\"bexd6ptjp0g0\",\"created\":1502413639815,\"text\":\"糕点\"},\"children\":[]},{\"data\":{\"id\":\"bexd6t8z8gg0\",\"created\":1502413647279,\"text\":\"聚会\"},\"children\":[]},{\"data\":{\"id\":\"bexd78bpejk0\",\"created\":1502413680095,\"text\":\"其它\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpml1xqhs0\",\"created\":1502245616671,\"text\":\"商户环境照片\"},\"children\":[]},{\"data\":{\"id\":\"bevpmucooe00\",\"created\":1502245636912,\"text\":\"店铺名称\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpoad7c4w0\",\"created\":1502245750136,\"text\":\"店铺折扣\"},\"children\":[{\"data\":{\"id\":\"bevppkiu2i00\",\"created\":1502245850608,\"text\":\"选择折扣比例（限时限次修改（1天一次，11-12））\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpo4a3quw0\",\"created\":1502245736888,\"text\":\"我的商品\"},\"children\":[{\"data\":{\"id\":\"bevpqt11mc80\",\"created\":1502245947488,\"text\":\"添加商品（后台审核）\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevpvmolnds0\",\"created\":1502246325496,\"text\":\"服务商品\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevpqwlc8wo0\",\"created\":1502245955245,\"text\":\"商品封面\"},\"children\":[]},{\"data\":{\"id\":\"bevprd6zr880\",\"created\":1502245991383,\"text\":\"单价\"},\"children\":[]},{\"data\":{\"id\":\"bevprgkv1g80\",\"created\":1502245998752,\"text\":\"数量\"},\"children\":[]},{\"data\":{\"id\":\"bevprm136cg0\",\"created\":1502246010617,\"text\":\"类别（商户行业类别2级一样)\"},\"children\":[]},{\"data\":{\"id\":\"bevps2a99q00\",\"created\":1502246046000,\"text\":\"有效时间（起止年月日）\"},\"children\":[]},{\"data\":{\"id\":\"bevptth3fu80\",\"created\":1502246183551,\"text\":\"商品介绍\"},\"children\":[]},{\"data\":{\"id\":\"bevptyx60680\",\"created\":1502246195407,\"text\":\"使用规则\"},\"children\":[]},{\"data\":{\"id\":\"bevpu2h04g00\",\"created\":1502246203136,\"text\":\"轮播图\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpw22xa1s0\",\"created\":1502246359013,\"text\":\"线上商品（下一步再考虑）\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpyk1t0og0\",\"created\":1502246554856,\"text\":\"商品状态\"},\"children\":[{\"data\":{\"id\":\"bevpys5bgrk0\",\"created\":1502246572483,\"text\":\"审核通过，自动上架\"},\"children\":[]},{\"data\":{\"id\":\"bevpzt8crsg0\",\"created\":1502246653207,\"text\":\"审核失败（说明原因）\"},\"children\":[]},{\"data\":{\"id\":\"bevq04i12y00\",\"created\":1502246677737,\"text\":\"下架\"},\"children\":[{\"data\":{\"id\":\"bevq1lhavjk0\",\"created\":1502246793062,\"text\":\"可以重新上架，不需审核\"},\"children\":[]}]},{\"data\":{\"id\":\"bevq0uiuaow0\",\"created\":1502246734382,\"text\":\"未审核（新添加、编辑后需要重新审核后）\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevpom14m0g0\",\"created\":1502245775527,\"text\":\"注销店铺\"},\"children\":[{\"data\":{\"id\":\"bevpopzcp2o0\",\"created\":1502245784128,\"text\":\"说明注销原因，由后台审核\"},\"children\":[]}]},{\"data\":{\"id\":\"bevq2u2lgf40\",\"created\":1502246890128,\"text\":\"收款二维码\"},\"children\":[]},{\"data\":{\"id\":\"bevq4bz4u4o0\",\"created\":1502247007465,\"text\":\"兑换订单\"},\"children\":[]},{\"data\":{\"id\":\"bevq4k7rbnc0\",\"created\":1502247025401,\"text\":\"付款订单\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpc83y55s0\",\"created\":1502244804853,\"text\":\"申请店铺（由后台审核）\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bevp2bu8weg0\",\"created\":1502244029332,\"text\":\"门牌照\"},\"children\":[]},{\"data\":{\"id\":\"bevp1yluuv40\",\"created\":1502244000526,\"text\":\"店铺电话\"},\"children\":[]},{\"data\":{\"id\":\"bevp1tbve6o0\",\"created\":1502243989038,\"text\":\"商户行业类别2级\"},\"children\":[]},{\"data\":{\"id\":\"bevp3ktp54o0\",\"created\":1502244127254,\"text\":\"店铺地址\"},\"children\":[{\"data\":{\"id\":\"bevp3nt08q00\",\"created\":1502244133742,\"text\":\"按地址搜索，地图定位、经纬度\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpaikdkg00\",\"created\":1502244670886,\"text\":\"商户环境照片（至少1张，最多5张）\"},\"children\":[]},{\"data\":{\"id\":\"bevp1pbwo3c0\",\"created\":1502243980333,\"text\":\"店铺名称\"},\"children\":[]},{\"data\":{\"id\":\"bevp4rbow280\",\"created\":1502244219766,\"text\":\"认证\"},\"children\":[{\"data\":{\"id\":\"bevp7o31wtc0\",\"created\":1502244447806,\"text\":\"有营业执照\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevp5eqcdxk0\",\"created\":1502244270718,\"text\":\"营业执照照片\"},\"children\":[]},{\"data\":{\"id\":\"bevp53y0rhs0\",\"created\":1502244247238,\"text\":\"营业执照号码\"},\"children\":[]}]},{\"data\":{\"id\":\"bevp7xiaa4o0\",\"created\":1502244468318,\"text\":\"没营业执照\"},\"children\":[{\"data\":{\"id\":\"bevp83e3v680\",\"created\":1502244481126,\"text\":\"营业执照照片改为填写平台给予的申请表，拍照上传\"},\"children\":[]},{\"data\":{\"id\":\"bevp8s29qb40\",\"created\":1502244534830,\"text\":\"营业执照号码改为手机号\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevp62seylc0\",\"created\":1502244323086,\"text\":\"店铺简介(最多500个字)\"},\"children\":[]},{\"data\":{\"id\":\"bevp14gop9c0\",\"created\":1502243934910,\"text\":\"推荐人手机号码\"},\"children\":[]},{\"data\":{\"id\":\"bevp67y0b740\",\"created\":1502244334309,\"text\":\"店铺折扣\"},\"children\":[{\"data\":{\"id\":\"bevp6n2k7ls0\",\"created\":1502244367236,\"text\":\"限时限次修改（1天一次，11-12）\"},\"children\":[]}]},{\"data\":{\"id\":\"bevpbw0aixs0\",\"created\":1502244778511,\"text\":\"商户协议勾选\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevp0h52mqo0\",\"created\":1502243884142,\"text\":\"会员\",\"expandState\":\"expand\",\"layout_right_offset\":{\"x\":4,\"y\":-59}},\"children\":[{\"data\":{\"id\":\"bevq7etuhvk0\",\"created\":1502247248768,\"text\":\"我的收藏\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bevq7yk2wts0\",\"created\":1502247291714,\"text\":\"收藏店铺\"},\"children\":[]},{\"data\":{\"id\":\"bevq80vo2800\",\"created\":1502247296768,\"text\":\"收藏商品\"},\"children\":[]}]},{\"data\":{\"id\":\"bevq839oc4g0\",\"created\":1502247301968,\"text\":\"收货地址（可以添加多个）\"},\"children\":[]},{\"data\":{\"id\":\"bevq8qvvbxs0\",\"created\":1502247353376,\"text\":\"个人信息\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bevqvxmit400\",\"created\":1502249170424,\"text\":\"真实姓名\"},\"children\":[]},{\"data\":{\"id\":\"bevqw9hn9y80\",\"created\":1502249196251,\"text\":\"头像\",\"layout_right_offset\":{\"x\":2,\"y\":35}},\"children\":[]},{\"data\":{\"id\":\"bevqx80i6080\",\"created\":1502249271402,\"text\":\"账号设置\"},\"children\":[{\"data\":{\"id\":\"bevqxcoy2w00\",\"created\":1502249281587,\"text\":\"修改登录密码\"},\"children\":[{\"data\":{\"id\":\"bevqyuvi6qo0\",\"created\":1502249399530,\"text\":\"旧密码\"},\"children\":[]},{\"data\":{\"id\":\"bevqyzqafmg0\",\"created\":1502249410098,\"text\":\"新密码、确认密码\"},\"children\":[]}]},{\"data\":{\"id\":\"bevqxib7www0\",\"created\":1502249293818,\"text\":\"修改支付密码\"},\"children\":[{\"data\":{\"id\":\"bevqxy7g2aw0\",\"created\":1502249328418,\"text\":\"手机号验证\"},\"children\":[]},{\"data\":{\"id\":\"bevqyc4mdk00\",\"created\":1502249358722,\"text\":\"支付密码、确认密码\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bevq8vmeypc0\",\"created\":1502247363689,\"text\":\"我的订单（线上订单、服务订单）\"},\"children\":[]},{\"data\":{\"id\":\"bevq96gp8480\",\"created\":1502247387288,\"text\":\"我的钱包\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bevra7q9b940\",\"created\":1502250289516,\"text\":\"现金余额\"},\"children\":[]},{\"data\":{\"id\":\"bevrazph0xc0\",\"created\":1502250350419,\"text\":\"现金收支流水\"},\"children\":[]},{\"data\":{\"id\":\"bevrba4oq140\",\"created\":1502250373107,\"text\":\"提现\"},\"children\":[{\"data\":{\"id\":\"bevrbt80g4w0\",\"created\":1502250414667,\"text\":\"微信、支付宝、银行卡\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevqr7okfm00\",\"created\":1502248800495,\"text\":\"在线培训（网址链接）\"},\"children\":[]},{\"data\":{\"id\":\"bevqroykrts0\",\"created\":1502248838106,\"text\":\"消息中心（系统消息、订单消息）\"},\"children\":[]},{\"data\":{\"id\":\"bevqs1cjwq00\",\"created\":1502248865072,\"text\":\"二维码邀请\"},\"children\":[]},{\"data\":{\"id\":\"bevr05a5c340\",\"created\":1502249500547,\"text\":\"系统设置\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevr0ivy29c0\",\"created\":1502249530163,\"text\":\"版本更新\"},\"children\":[]},{\"data\":{\"id\":\"bevr07qn4a80\",\"created\":1502249505898,\"text\":\"清理缓存\"},\"children\":[]},{\"data\":{\"id\":\"bevr0butppc0\",\"created\":1502249514858,\"text\":\"关于我们\"},\"children\":[]},{\"data\":{\"id\":\"bevr15ms1i80\",\"created\":1502249579675,\"text\":\"联系我们\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bevrf6a1mhc0\",\"created\":1502250678180,\"text\":\"会员角色说明（所有角色共存）\",\"expandState\":\"expand\",\"layout_right_offset\":{\"x\":-32,\"y\":-2}},\"children\":[{\"data\":{\"id\":\"bevrfc48nw00\",\"created\":1502250690890,\"text\":\"普通会员\",\"note\":\"1、消费满500个积分转一个分红点，分红点获取现金、现金券、商超券收益，最高所得3000个分红点；\"},\"children\":[]},{\"data\":{\"id\":\"bevrff9dsf40\",\"created\":1502250697731,\"text\":\"商家\",\"note\":\"1、消费满500个积分转一个分红点，分红点获取现金、现金券、商超券收益，最高所得3000个分红点；\\n2、消费者消费会赠送商家积分；\"},\"children\":[]},{\"data\":{\"id\":\"bevrfiwchyg0\",\"created\":1502250705650,\"text\":\"创客\",\"expandState\":\"collapse\",\"layout_right_offset\":{\"x\":0,\"y\":0}},\"children\":[{\"data\":{\"id\":\"bevrgyzy1yg0\",\"created\":1502250819060,\"text\":\"一星创客\",\"note\":\"直接分享3个会员，并且在平台消费100元，可获得21层每一层的1%奖励\"},\"children\":[]},{\"data\":{\"id\":\"bevrhamo3xc0\",\"created\":1502250844379,\"text\":\"二星创客\",\"note\":\"必须要满足上一级且旗下销售额200万-400万\"},\"children\":[]},{\"data\":{\"id\":\"bevrhc17jsw0\",\"created\":1502250847435,\"text\":\"三星创客\",\"note\":\"必须要满足上一级且旗下销售额400万-800万\"},\"children\":[]},{\"data\":{\"id\":\"bevrhdnozvk0\",\"created\":1502250850971,\"text\":\"四星创客\",\"note\":\"必须要满足上一级且旗下销售额800万-1600万\"},\"children\":[]},{\"data\":{\"id\":\"bevrhfhlhag0\",\"created\":1502250854956,\"text\":\"五星创客\",\"note\":\"必须要满足上一级且旗下销售额1600万及以上\"},\"children\":[]}]},{\"data\":{\"id\":\"bevri3bv9280\",\"created\":1502250906852,\"text\":\"渠道（向公司支付10万元，可以线下支付，平台根据发展代理商情况，可以取消资格）\"},\"children\":[]},{\"data\":{\"id\":\"bevri7kili00\",\"created\":1502250916083,\"text\":\"代理商（前期市场运营代理不收费，完成200个商家入驻，分享1500个会员；或者支付20万元）\",\"font-weight\":\"bold\"},\"children\":[]},{\"data\":{\"id\":\"bevsmuqnpi80\",\"created\":1502254101086,\"text\":\"代理点\",\"note\":\"必须是商家且缴1万成为代理点，可以销售公司直营产品；可以商超券抵扣；\"},\"children\":[]}]},{\"data\":{\"id\":\"bevspf8s9e80\",\"created\":1502254302446,\"text\":\"平台角色说明（利润月结)\"},\"children\":[{\"data\":{\"id\":\"bevspmmfy9k0\",\"created\":1502254318510,\"text\":\"（平台、技术）\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevsq1beggg0\",\"created\":1502254350494,\"text\":\"分公司\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bevsq4n9wpk0\",\"created\":1502254357742,\"text\":\"运营中心\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bevsv28tdq80\",\"created\":1502254744335,\"text\":\"分润说明\"},\"children\":[]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"6bc60c5c2a1c8d8cafe2ac3e370c9402","csrf_token":"49293f364ce08e962853259a41369bbe"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
