### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ViewSeas** [fex-team/kityminder-editor#479]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"3d53f8d9ebf4\",\"created\":1502433377,\"text\":\"新建脑图\"},\"children\":[{\"data\":{\"id\":\"bexk66efa60w\",\"created\":1502433345311,\"text\":\"文本框\"},\"children\":[{\"data\":{\"id\":\"bexk6v2bz34k\",\"created\":1502433399000,\"text\":\"文本\"},\"children\":[{\"data\":{\"id\":\"bexk7xgqc7sc\",\"created\":1502433482588,\"text\":\"可修改长度，最大4000.不靠换行\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk6vnor5kw\",\"created\":1502433400291,\"text\":\"数字（小数位 默认0）\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk682nwq8s\",\"created\":1502433348954,\"text\":\"文本域\"},\"children\":[{\"data\":{\"id\":\"bexk8dbkaqgc\",\"created\":1502433517104,\"text\":\"文本（长度4000）\"},\"children\":[]},{\"data\":{\"id\":\"bexk8du6t7cc\",\"created\":1502433518230,\"text\":\"大文本\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk68xcvc0k\",\"created\":1502433350810,\"text\":\"复选框\"},\"children\":[]},{\"data\":{\"id\":\"bexk69hobc0k\",\"created\":1502433352038,\"text\":\"单选按钮\"},\"children\":[{\"data\":{\"id\":\"bexkbxuq4iok\",\"created\":1502433796891,\"text\":\"枚举\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk69s6i1c8\",\"created\":1502433352674,\"text\":\"下拉框\"},\"children\":[{\"data\":{\"id\":\"bexkcf3y0204\",\"created\":1502433834454,\"text\":\"枚举\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk6a0f97kk\",\"created\":1502433353172,\"text\":\"日期控件\"},\"children\":[{\"data\":{\"id\":\"bexkdwefin4k\",\"created\":1502433950457,\"text\":\"发起格式不转，提交后转\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk6a80vfkg\",\"created\":1502433353632,\"text\":\"日期时间控件\"},\"children\":[]},{\"data\":{\"id\":\"bexk6ag3ltkw\",\"created\":1502433354120,\"text\":\"流程处理意见\"},\"children\":[{\"data\":{\"id\":\"bexkessoyz48\",\"created\":1502434020977,\"text\":\"态度/：已阅/同意/不同意\"},\"children\":[{\"data\":{\"id\":\"bexkgakbuzkg\",\"created\":1502434138017,\"text\":\"可隐藏，不可修改\"},\"children\":[]}]},{\"data\":{\"id\":\"bexketgaths8\",\"created\":1502434022404,\"text\":\"意见\"},\"children\":[]},{\"data\":{\"id\":\"bexketqpq5ck\",\"created\":1502434023034,\"text\":\"签名\"},\"children\":[]},{\"data\":{\"id\":\"bexkeuouvvkk\",\"created\":1502434025098,\"text\":\"日期时间\"},\"children\":[]}]},{\"data\":{\"id\":\"bexk6an280wg\",\"created\":1502433354541,\"text\":\"标签\"},\"children\":[]},{\"data\":{\"id\":\"bexk6aumk2wo\",\"created\":1502433354998,\"text\":\"签章\"},\"children\":[{\"data\":{\"id\":\"bexkkpy21sg8\",\"created\":1502434484956,\"text\":\"必须购买高级office和电子签章\"},\"children\":[]}]},{\"data\":{\"id\":\"bexkkc870ow0\",\"created\":1502434455094,\"text\":\"二维码\"},\"children\":[{\"data\":{\"id\":\"bexkl9ipt7cc\",\"created\":1502434527564,\"text\":\"设置二维码内容\"},\"children\":[]}]},{\"data\":{\"id\":\"bexkkckjkl4w\",\"created\":1502434455840,\"text\":\"关联表单\"},\"children\":[{\"data\":{\"id\":\"bexkm1pi7qgo\",\"created\":1502434588924,\"text\":\"对表单的查询引用\"},\"children\":[]},{\"data\":{\"id\":\"bexkmlxl480g\",\"created\":1502434632948,\"text\":\"用户选择\"},\"children\":[{\"data\":{\"id\":\"bexkmunyd544\",\"created\":1502434651957,\"text\":\"表里自行勾选，数据过滤做权限控制\"},\"children\":[]},{\"data\":{\"id\":\"bexkpgysq5ss\",\"created\":1502434857230,\"text\":\"仅显示列表：eg已发事项，不能穿透\"},\"children\":[]},{\"data\":{\"id\":\"bexkqodyvgg0\",\"created\":1502434951749,\"text\":\"显示已关联表单：穿透\"},\"children\":[]}]},{\"data\":{\"id\":\"bexkmmhnby80\",\"created\":1502434634161,\"text\":\"系统选择\"},\"children\":[{\"data\":{\"id\":\"bexknpyoj6wo\",\"created\":1502434720086,\"text\":\"唯一性\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bexkkcwii884\",\"created\":1502434456564,\"text\":\"数据关联\"},\"children\":[{\"data\":{\"id\":\"bexkrgelpxc0\",\"created\":1502435012737,\"text\":\"分支主题\"},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"439cca4e443a93c60b8855d4f73403e6","csrf_token":"eadcbcc4eaafe997b989b216495a9897"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
