### ISSUE TITLE
错误 出现问题了

### ISSUE THREAD

**Issue by huyunzhen** [fex-team/kityminder-editor#484]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"c6b737003bea\",\"created\":1502702896,\"text\":\"RecordPlay\"},\"children\":[{\"data\":{\"id\":\"bf2mugzgsv40\",\"created\":1502948691095,\"text\":\"RecordPlay.mxml\",\"layout_mind_offset\":{\"x\":-70,\"y\":-12}},\"children\":[{\"data\":{\"id\":\"bf2nk43dgzc0\",\"created\":1502950700501,\"text\":\"player:Player\"},\"children\":[]},{\"data\":{\"id\":\"bf2nko5hsy00\",\"created\":1502950744165,\"text\":\"applicationComplete\"},\"children\":[{\"data\":{\"id\":\"bf2nm25h5iw0\",\"created\":1502950853003,\"text\":\"loadDataxml\"},\"children\":[]},{\"data\":{\"id\":\"bf2nrzie1zc0\",\"created\":1502951317438,\"text\":\"initialConfig\"},\"children\":[]},{\"data\":{\"id\":\"bf2nt1g3ke00\",\"created\":1502951400018,\"text\":\"InitLoad.instance\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bf2mv27du3k0\",\"created\":1502948737286,\"text\":\"com.gnet.event.\",\"expandState\":\"expand\",\"layout_mind_offset\":{\"x\":48,\"y\":6}},\"children\":[{\"data\":{\"id\":\"bf2mtch1u5c0\",\"created\":1502948602910,\"text\":\"controller\",\"layout_left_offset\":{\"x\":-4,\"y\":-1}},\"children\":[{\"data\":{\"id\":\"bf2ntwdejs80\",\"created\":1502951467335,\"text\":\"InitLoad\"},\"children\":[{\"data\":{\"id\":\"bf2nuq66cp40\",\"created\":1502951532201,\"text\":\"instance\"},\"children\":[]},{\"data\":{\"id\":\"bf2nw1dncrk0\",\"created\":1502951634962,\"text\":\"loadReplayXMLUseLoader\"},\"children\":[]},{\"data\":{\"id\":\"bf2nylozlvc0\",\"created\":1502951835912,\"text\":\"parseContent\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bf2o79qfk0o0\",\"created\":1502952515155,\"text\":\"ModelLocator.locaTimeStaff:time\"},\"children\":[]},{\"data\":{\"id\":\"bf2o7ig0ubc0\",\"created\":1502952534117,\"text\":\"ModelLocator.recordDataMap:data\"},\"children\":[]}]},{\"data\":{\"id\":\"bf2oe3lufqo0\",\"created\":1502953050366,\"text\":\"firstLoadLayout\"},\"children\":[{\"data\":{\"id\":\"bf2oerlt9eg0\",\"created\":1502953102607,\"text\":\"GlobalEventDispatcher:EVENT_PLAYER_CHECK_LOADED\"},\"children\":[]},{\"data\":{\"id\":\"bf2oflr1d7s0\",\"created\":1502953168226,\"text\":\"Utils.switchView:VIEWTYPE_DOC\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bf2mtl2tvog0\",\"created\":1502948621641,\"text\":\"events\"},\"children\":[]},{\"data\":{\"id\":\"bf2mtnwyq680\",\"created\":1502948627817,\"text\":\"flvplayer\"},\"children\":[]},{\"data\":{\"id\":\"bf2mtryiacw0\",\"created\":1502948636617,\"text\":\"interfaces\"},\"children\":[]},{\"data\":{\"id\":\"bf2mtu77p080\",\"created\":1502948641497,\"text\":\"model\"},\"children\":[]},{\"data\":{\"id\":\"bf2mtv49leo0\",\"created\":1502948643496,\"text\":\"player\"},\"children\":[]},{\"data\":{\"id\":\"bf2mtz5kkso0\",\"created\":1502948652282,\"text\":\"swfplayer\"},\"children\":[]},{\"data\":{\"id\":\"bf2mu2mqh8o0\",\"created\":1502948659850,\"text\":\"view\"},\"children\":[]}]},{\"data\":{\"id\":\"bf2odg2j6gg0\",\"created\":1502952999132,\"text\":\"utils\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"7ae6949aa855856f228a5cea02507ef6","csrf_token":"4270afb0e978f12dd6d0bc10647fea05"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by zhangbobell** [comment]
503 错误是服务器压力过大造成的，已经通过扩容解决，如果仍然有 503 错误弹出，请反馈，谢谢。
