### ISSUE TITLE
反馈 503

### ISSUE THREAD

**Issue by sky-mxc** [fex-team/kityminder-editor#485]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/ls","data":{"dirGuid":"55c178e74c7c50c85139191ea53c4b40","csrf_token":"18c70ef33fedaff1bc1832adfa96a539"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by zhangbobell** [comment]
503 错误是服务器压力过大造成的，已经通过扩容解决，如果仍然有 503 错误弹出，请反馈，谢谢。
