### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by TonySmith1994** [fex-team/kityminder-editor#488]
错误
 
行号：0
错误信息：Script error.
列号：0

浏览器信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by zhangbobell** [comment]
目前在 Safari 下仍有一些兼容性的问题，我们已经知晓并正在解决。

**Comment by zhangbobell** [comment]
duplicate with #190
