### ISSUE TITLE
500报错，一会就来一下，我快崩溃了

### ISSUE THREAD

**Issue by unigloria** [fex-team/kityminder-editor#489]
一会儿就报一次500错误，我要崩溃了，只是在输入文字，没有导入导出大图片啊

错误
 {"data":"<html>\r\n<head>                                        <title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"2c7920a76927\",\"created\":1503314413,\"text\":\"财务分析与决策\"},\"children\":[{\"data\":{\"id\":\"bf68glldvkoc\",\"created\":1503314348317,\"text\":\"1、资金的运用——认识资产\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf68gsyitjc4\",\"created\":1503314364349,\"text\":\"1.2 认识资产负债表\\n（balance sheet)\",\"image\":\"\",\"imageTitle\":\"\",\"imageSize\":\"\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf68hpmz89c8\",\"created\":1503314435484,\"text\":\"会计眼中公司只做三件事：经营、投资、融资\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf68jxj9teok\",\"created\":1503314609403,\"text\":\"资产负债表用来描述本金变成了哪些东西，他们的价值如何\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf68kvqcriwc\",\"created\":1503314683842,\"text\":\"资产负债表分为左右两部分：左边是资产（assets）；右边是负债（liabilities）和股东权益（shareholder's equity）\",\"image\":\"\",\"imageTitle\":\"\",\"imageSize\":\"\",\"hyperlink\":\"https://www.duitang.com/blog/?id=810000066\",\"hyperlinkTitle\":\"真实的资产负债表\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf6bqperf34g\",\"created\":1503323603595,\"text\":\"资产负债表是一个时点的概念\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf696fuc00oc\",\"created\":1503316373265,\"text\":\"1.3 1.4 资产的概念和结构\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf68td6ugzcw\",\"created\":1503315348758,\"text\":\"流动资产（current assets）：一个循环就能变成现金的，以下排列就是按照变成现金的快慢排列的\\n货币资金（cash）、\\n应收帐款（account receivable）、\\n其它应收款（other receivables）、\\n预付帐款（prepaid accounts）、\\n存货（inventory）、\\n待摊费用（deferred expenses）（预付的租金、广告费等）\\n其它资产\\n\\n非流动资产（noncurrent assets）：\\n长期投资（long-term investment）\\n固定资产（fixed asset）\\n无形资产（intangible assets and other assets）\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf697k47yego\",\"created\":1503316460935,\"text\":\"1.5 资产的价值\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf699ebpf54o\",\"created\":1503316605055,\"text\":\"在多数国家，采用“当时购买资产的价格（历史成本historical cost）”的资产计价体系，同时，忽略升值，记录减值\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf69apdc5v4s\",\"created\":1503316707462,\"text\":\"对金融资产（financial asset） ，使用当前的市场价格（公允价格fair value）的资产计价\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf69b0o1m5ko\",\"created\":1503316732054,\"text\":\"对投资性房地产（investment property），也使用公允价格计算\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf69rm1zubs4\",\"created\":1503318032437,\"text\":\"2、资金的来源与利润的产生\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf69s2kpmtc0\",\"created\":1503318068397,\"text\":\"2.1 认识负债\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf69wr7w880g\",\"created\":1503318435498,\"text\":\"流动负债（current liabilities）：一年之内要支付的负债\\n短期借款（short-term borrowing）\\n应付帐款（accounts payable）\\n其它应付款（other payables）\\n预收账款（deposit received）\\n其它流动负债（other liablilities）\\n\\n非流动负债（noncurrent liabilities）：一年之后要支付的负债\\n长期借款（long-term loans payable）\\n应付债券（bond payable）\\n长期应付款（long term payable）\\n其它非流动负债（others）\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6a0d9hymwc\",\"created\":1503318718577,\"text\":\"2.2 股东的权益\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6a0gdb7ogk\",\"created\":1503318725338,\"text\":\"股本（capital stock）（等于注册资本，结构体现了股东之间权力的分配）\\n资本公积（additional paid-in capital）\\n盈余公积（surplus reserve）（法律不让分配的利润）\\n未分配利润（retained earnings）（公司自己不想分配的利润）\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6bb0mlo740\",\"created\":1503322374187,\"text\":\"2.4 了解利润表\\n（income statement）\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6bb57bqyo0\",\"created\":1503322384147,\"text\":\"营业收入（operating income）\\n-营业成本（operationg cost）\\n-营业税金及附加（business tax and surcharges）\\n-营业费用（operating expenses）\\n-管理费用（general and administrative expense）\\n-财务费用（financial expense）\\n-资产减值（impairment loss of assets impairment）\\n+公允价值变动收益或损失（gains on the changes in the fair value）\\n+投资收益（investment income）\\n=营业利润（operating profit）\\n+营业外收入（non-operating revenues）\\n-营业外费用（non-operating expenses）\\n=利润总额（total profit）\\n-所得税（income tax）\\n=净利润（net profit）\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf6bo7blmwow\",\"created\":1503323407493,\"text\":\"income - cost = gross profit\\ngross profit - expenses = pre-tax profits\\npre-tax profits - income tax = profit\",\"layout\":null,\"hyperlink\":\"https://b-ssl.duitang.com/uploads/item/201708/22/20170822213029_cFisQ.png\",\"hyperlinkTitle\":\"利润漏斗\"},\"children\":[]},{\"data\":{\"id\":\"bf6bqj6s2ds8\",\"created\":1503323590051,\"text\":\"利润表是一个时段的概念\",\"layout\":null,\"expandState\":\"expand\"},\"children\":[]},{\"data\":{\"id\":\"bf75f8naba8k\",\"created\":1503407338396,\"text\":\"利润表描述两件事：一个是现在赚了多少钱，还有一个是帮助你预测企业未来的盈利状况\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6bt4j1qx44\",\"created\":1503323793234,\"text\":\"资产负债表和利润表的关系\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6btile6ugo\",\"created\":1503323823852,\"text\":\"未分配利润连接了资产负债表和利润表\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf6vvh3gshs0\",\"created\":1503380399517,\"text\":\"3、财务报表是如何产生的\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6vvkm1pbks\",\"created\":1503380407170,\"text\":\"3.1 企业的13项经济活动与财务报表\",\"layout\":null,\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bf6vwcp6lr4g\",\"created\":1503380468310,\"text\":\"1  设立公司，股东投资3200万元现金。\\n2  向银行借款5100万元，借款期限为6个月。\\n3  购买生产设备，办公家具等，花费5700万元\\n-   （以银行存款支付，形成固定资产）\\n4  获取一块土地的使用权，花费150万元。\\n-   （形成无形资产）\\n5  采购原材料花费2400万元，\\n-   到12月31日为止支付1600万元现金，其余部分将在下一年度分期支付。\\n6  生产出一批产品。产品成本为3600万元\\n-   其中使用的原材料价值为2400万元；\\n-   发生了人工费和其他支出1200万元，以现金支付。\\n7  销售产品4300万元，\\n-   销售成本3100万元。\\n-   到12月31日为止收到3000万元现金，其余部分将在下一年度内收到。\\n8  为下一年采购原材料预付150万元。\\n-   （形成预付账款150万）\\n9  支付管理人员工资和行政开支150万元\\n-   支付销售人员工资和外地销售分公司开支250万元。\\n10  研发部门当期花费50万元，成功地研制出新技术。\\n11  支付银行利息130万元。\\n12  支付所得税100万元。\\n-    （企业纯利润为520万）\\n13  分配现金股利100万元。\\n-     (未分配利润合计420万）\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6vwwfpa8g8\",\"created\":1503380511272,\"text\":\"1  cash +3200   |  capital +3200\\n2  cash +5100   |  short term borrowing +5100\\n3  cash  -5700 \\n-   fixed asset +5700 \\n4  cash  -150\\n-   intangible asset +150\\n5  cash  -1600  \\n-   inventory +2400  |  account payable +800\\n6  cash  -1200\\n-   inventory -2400\\n-   inventory +3600\\n7  cash +3000                           |  sales revenue 4300\\n-   account receivable  +1300   |  sales cost 3100\\n-   inventory -3100\\n8  cash  -150  \\n-   prepaid account +150\\n9  cash  -400  |  sales expenses 250\\n-                        administration expenses 150\\n10  cash  -50  |  administration expenses 50\\n11  cash  -130  |  financial expenses 130\\n12  cash  -100  |  income tax 100\\n-                          net profit 520\\n13  cash  -100  |  cash divident 100\\n-                          retained earnings 420\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf6wj5w8zcw0\",\"created\":1503382255875,\"text\":\"生产成本、存货\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6wkb0v2z48\",\"created\":1503382345403,\"text\":\"生产成本（manufacturing cost）\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6wkj32k740\",\"created\":1503382362950,\"text\":\"原材料（raw material）\\n人工（labor）\\n制造费用（manufacturing overhead）（包括水电等车间开支，厂房设备折旧等）\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6wlqb7r9c0\",\"created\":1503382457044,\"text\":\"存货（inventory）\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6wlyu2p7so\",\"created\":1503382475599,\"text\":\"未使用的原材料（unused material）\\n在产品（work-in-process）\\n产成品（finished goods）\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf6wp4t4kbkk\",\"created\":1503382723695,\"text\":\"存货会转化为两个方向，\\n一部分（sold）成为营业成本（operating cost），\\n一部分（unsold）继续作为存货（inventory-ending balance）\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6wnqd15goo\",\"created\":1503382613883,\"text\":\"营业成本与营业费用\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6wnvk8byg4\",\"created\":1503382625202,\"text\":\"营业成本属于生产环节，属于生产成本的一部分\\n是销售出去的那部分产品的生产成本\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf6wowyluu8g\",\"created\":1503382706612,\"text\":\"营业费用（operating expenses）属于销售环节\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf6wrvd0w9sk\",\"created\":1503382938223,\"text\":\"3.3 产量、销量与毛利润\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6ws6m35tkw\",\"created\":1503382962715,\"text\":\"生产成本分为变动成本和固定成本\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf6wsc4pjs0g\",\"created\":1503382974725,\"text\":\"变动成本（variable cost）：随着生产量的增加，成本增加。如原材料\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf6wsngcmg8o\",\"created\":1503382999374,\"text\":\"固定成本（fixed cost）：一定范围内，无论生产多少产品，成本固定不变。如厂房折旧\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf6wt8rlz8ws\",\"created\":1503383045767,\"text\":\"一些企业的毛利水平随库存变动，固定成本高的企业（如重资产的企业）情况更为明显：\\n毛利的上升伴随库存的增加，并不是经营良好的表现\\n库存的减少带来毛利的下降，也并不是经营不好的表现\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf6wuyxa96gw\",\"created\":1503383181071,\"text\":\"4、财务报表的逻辑架构\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74homnkgg8\",\"created\":1503404708805,\"text\":\"4.2 认识现金流量表\\n(cash flow statement)\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74i5dewg00\",\"created\":1503404745252,\"text\":\"现金流量表按照3种类型的经济活动对现金流进行分类，描述现金的流入和流出\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf74kambp8o4\",\"created\":1503404913403,\"text\":\"operating activities\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74j6nnw2wo\",\"created\":1503404826412,\"text\":\"core business\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74kp2f0tss\",\"created\":1503404944851,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74j9bkem0w\",\"created\":1503404832211,\"text\":\"sale\\ntax\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74kuqt6vsc\",\"created\":1503404957210,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74jw7171cg\",\"created\":1503404882003,\"text\":\"procurement\\nsalary\\ntax\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf74jtt5rps8\",\"created\":1503404876811,\"text\":\"other business\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74l5r7oso4\",\"created\":1503404981179,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74la7u5ios\",\"created\":1503404990891,\"text\":\"rent\\ntax\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74l7kpuw0g\",\"created\":1503404985139,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74la7u5ios\",\"created\":1503404990891,\"text\":\"rent\\ntax\",\"layout\":null},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bf74lq6ah0oo\",\"created\":1503405025626,\"text\":\"investment activities\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74m1r7rc0k\",\"created\":1503405050836,\"text\":\"fixed assets\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74m6w0nfcc\",\"created\":1503405062010,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74mh50knk8\",\"created\":1503405084322,\"text\":\"disposal\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74matbmhsg\",\"created\":1503405070554,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74mmmt1dkw\",\"created\":1503405096282,\"text\":\"puchase or construct\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf74m4nvv5kw\",\"created\":1503405057165,\"text\":\"investment\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74m6w0nfcc\",\"created\":1503405062010,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74mpzvbfcc\",\"created\":1503405103602,\"text\":\"disposal\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74matbmhsg\",\"created\":1503405070554,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74mzyy32wc\",\"created\":1503405125314,\"text\":\"invest\",\"layout\":null},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bf74n3tlkh4o\",\"created\":1503405133698,\"text\":\"financing activities\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74n9hcv1ko\",\"created\":1503405146018,\"text\":\"debt\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74m6w0nfcc\",\"created\":1503405062010,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74ngbpc68g\",\"created\":1503405160914,\"text\":\"raise money\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74matbmhsg\",\"created\":1503405070554,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74nkbe9y8k\",\"created\":1503405169602,\"text\":\"interest principal\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf74nauoseg4\",\"created\":1503405149001,\"text\":\"equity\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74m6w0nfcc\",\"created\":1503405062010,\"text\":\"inflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74ngbpc68g\",\"created\":1503405160914,\"text\":\"raise money\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74matbmhsg\",\"created\":1503405070554,\"text\":\"outflow\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74noill4w0\",\"created\":1503405178745,\"text\":\"dividend\",\"layout\":null},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bf74o9kz7kwk\",\"created\":1503405224601,\"text\":\"4.3 现金流量表的作用\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74oi0mzyg4\",\"created\":1503405242962,\"text\":\"现金流量表描述了现金的来龙去脉，更确切的说，是描述了企业的风险状况\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf74p664w4ws\",\"created\":1503405295538,\"text\":\"4.4 现金流量表的产生\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74r6vitpcg\",\"created\":1503405453801,\"text\":\"13项经济活动与现金流量表\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74rbxben4k\",\"created\":1503405464793,\"text\":\"cash\\n1  +3200  | shareholders' investment\\n2  +5100  | bank loan\\n3     -150  | land\\n4   -1600  | procurement\\n6   -1200  | manufacturing\\n7  +7300  | sales\\n8     -150  | prepayment to supplier\\n9     -400  | expense\\n10     -50  | research and development\\n11   -130  | interest payment\\n12   -100  | income tax\\n13   -100  | ash dividend\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf74urboylss\",\"created\":1503405733407,\"text\":\"现金流分类\\n1   financing+\\n2   financing+\\n3   investment-\\n4   investment-\\n5   operation-\\n6   operation-\\n7   operation+\\n8   operation-\\n9   operation-\\n10 operation-\\n11 financing-\\n12 operation-\\n13 financing-\",\"layout\":null},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bf751wfzq0ow\",\"created\":1503406293100,\"text\":\"4.5 三张报表的逻辑关系\",\"layout\":null,\"hyperlink\":\"https://b-ssl.duitang.com/uploads/item/201708/22/20170822210436_vK5dQ.png\",\"hyperlinkTitle\":\"三张报表的逻辑关系\",\"image\":\"\",\"imageTitle\":\"\",\"imageSize\":\"\"},\"children\":[{\"data\":{\"id\":\"bf755ftt128g\",\"created\":1503406570386,\"text\":\"利润表有三个要素：收入-成本费用=利润   描述了企业的经营活动情况\\n资产负债表有三个要素：资产=负债+股东权益    描述了企业投融资情况\\n现金流量表从风险的角度重新描述了经营、投资和融资活动\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf758iz2tn48\",\"created\":1503406812328,\"text\":\"风险的视角：现金流量表\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf758mqp5mo0\",\"created\":1503406820528,\"text\":\"收益的视角：资产负债表+利润表\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf75cscyexsk\",\"created\":1503407146215,\"text\":\"4.6 三张报表的作用\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf75cwdyia04\",\"created\":1503407154983,\"text\":\"银行最关心的是现金流量表（还款风险）\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf75e0osicws\",\"created\":1503407242709,\"text\":\"投资者最关心的是利润表（未来的收益）\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf75g50r0tck\",\"created\":1503407408868,\"text\":\"兼合收购者最关心的是资产负债表（所有者权益，高估资产的风险和低估负债的风险）\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf75rpdelh4w\",\"created\":1503408315174,\"text\":\"5、财务分析的基本方法\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf75rtjayygw\",\"created\":1503408324238,\"text\":\"5.1 同型分析\\n（common-size analysis）\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf75tw6f1g08\",\"created\":1503408486717,\"text\":\"利润表：每个项目占收入的比重，即从收入到利润过程中每个步骤的损耗是多少\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf75xkiaiiw4\",\"created\":1503408774771,\"text\":\"13项经济活动后的利润表同型分析\\noperating income                             4300  |  100%\\n-operating cost                                 3100  |  72%     毛利润28%\\n-business tax and surcharges                 0  |  0%\\n-operating expenses                           250  |  6%\\n-administration expenses                    200  |  5%\\n-financial expenses                              130  |  3%       费用14%\\n-impairment loss of asset                        0  |  0%\\n-gains on the changes in the fair value   0  |  0%\\n+investment income                               0  |  0%\\n=operating profit                                 620  |  14%\\n+net non-operating income                    0  |  0%\\n=total profit                                         620  |  14%\\n-income tax                                          100  |  2%       税负2%\\nnet profit                                              520  |  12%\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf75wg9y714c\",\"created\":1503408687195,\"text\":\"资产负债表：资金总量中各资产占的比重，资金来源状况\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf764sr13w8w\",\"created\":1503409341263,\"text\":\"13项经济活动后的资产负债表同型分析\\nASSETS\\ncurrent assets\\ncash                                             1720  |  18%\\naccount receivale                        1300  |  14%     应收帐款比重显示行业是买方市场还是卖方市场\\nprepaid account                            150  |  2%\\ninventory                                       500  |  5%\\ntotal current assets                      2670  |  39%\\nnoncurrent assets\\nlong-term investment                       0  |  0%\\nfixed asset                                    5700  |  60%     固定资产比重大，显示是重资产企业\\nintangile assets and other assets  150  |  2%\\n\\nLIABILITIES\\ncurrent liabilities\\nshort-term borrowing                  5100  |  54%\\naccount payable                             800  |  8%\\nwages payable                                    0  |  0%\\ntotal current liabilities                  5900  |  62%\\nnoncurrent liabilities\\nlong-term loans payable                    0  |  0%\\nbond payable                                      0  |  0%\\ntotal liabilities                               5900  |  62%\\n\\nSHAREHOLDER'S EQUITY             3620  |  38%\\ncapital stock                                  3200  |  34%\\nadditional paid-in capital                    0  |  0%\\nsurplus reserve                                    0  |  0%\\nretained earnings                            420  |  4%\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf76f3ggpfcw\",\"created\":1503410148210,\"text\":\"5.2 盈利能力分析\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf76fc4k12go\",\"created\":1503410167081,\"text\":\"比率分析\\nratio analysis\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf76fghhjn4s\",\"created\":1503410176570,\"text\":\"毛利润率=毛利润/收入\\ngross margin=gross profit/income\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf76gwz27xko\",\"created\":1503410290825,\"text\":\"净利润率=净利润/收入    \\nnet profit margin=net profit/income\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf7744g9sbkk\",\"created\":1503412109479,\"text\":\"代表效益\\neffectiveness\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf76iqybw6go\",\"created\":1503410434449,\"text\":\"总资产报酬率=净利润/总资产\\nreturn on total asset=net profit/total assets\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf774x7nqa04\",\"created\":1503412172085,\"text\":\"代表即投资回报\\nreturn on investment\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf76nzxashs0\",\"created\":1503410845798,\"text\":\"总资产周转率=总收入/总资产\\ntotal assets turnover = income/total assets\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf774cdn2dk4\",\"created\":1503412126734,\"text\":\"代表效率\\nefficiency\",\"layout\":null},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bf8kjn2n6gow\",\"created\":1503551559862,\"text\":\"营运能力分析\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf8kkeh9ig8o\",\"created\":1503551619519,\"text\":\"以周转率为核心\\n可以算出每一项资产的周转率\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf8kllw5nhck\",\"created\":1503551714021,\"text\":\"一般的\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf8km0w8pnkk\",\"created\":1503551746678,\"text\":\"某项资产的周转率=收入/某项资产\\nthe turnover ratio of an asset = incom/a specific asset item\\n如：\\n应收账款周转率 = 收入/应收账款\\naccounts receivables turnover = incom/accounts receivable\\n流动资产周转率 = 收入/流动资产\\ncrrent asset turnover = income/current asset\\n固定资产周转率 = 收入/固定资产\\nfixed asset turnover = income/fixed asset\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf8kqaxdta80\",\"created\":1503552081972,\"text\":\"存货\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf8kqbzsbw8w\",\"created\":1503552084294,\"text\":\"存货周转率 = 成本/存货\\ninventory turnover ratio = cost/inventory\",\"layout\":null},\"children\":[]}]}]},{\"data\":{\"id\":\"bf8krhazfyo8\",\"created\":1503552174219,\"text\":\"周转率的计算是以利润表中的元素/资产负债表的中元素\\n\\nincome         cost          ------来自利润表\\n--------  or  --------\\n  asset        inventory     ------来自资产负债表\\n\\n其中利润表中的是时段的概念，资产负债表中的是时点的概念\",\"layout\":null},\"children\":[{\"data\":{\"id\":\"bf8l6x87xw08\",\"created\":1503553384343,\"text\":\"所以计算周转率更合理的方式是，使用资本平均水平：\\n某项资产的周转率 = 收入（成本）/某项资产在一年中的平均水平\\n但是讨论资本回报（效益*效率）时，一般使用期末的资本水平计算\",\"layout\":null},\"children\":[]},{\"data\":{\"id\":\"bf8l7ygo7pc0\",\"created\":1503553465395,\"text\":\"资本平均水平:\\n（期初的资本+期末的资本）/2\\n（assets at the beginning of period + assets at the end of period)/2\",\"layout\":null},\"children\":[]}]},{\"data\":{\"id\":\"bf8lct3f4mww\",\"created\":1503553845530,\"text\":\"另一个投资回报的概念：股东投资的回报率\\n净资产报酬率 = 净利润/股东权益（即净资产）\\nreturn on net assets = net income/shareholders' equity\"},\"children\":[]}]},{\"data\":{\"id\":\"bf8lesgvdj40\",\"created\":1503554000895,\"text\":\"短期偿债能力分析\"},\"children\":[{\"data\":{\"id\":\"bf8lf10qqsgg\",\"created\":1503554019511,\"text\":\"流动负债能力：如给供应商付款，资金正常的来源是使用流动资产（现金，存货等）\"},\"children\":[]},{\"data\":{\"id\":\"bf8lfaoige0w\",\"created\":1503554040539,\"text\":\"流动比率 = 流动资产/流动负债 （假设所有的流动资产都可以立即变现）\"},\"children\":[]},{\"data\":{\"id\":\"bf8ljh1o45k4\",\"created\":1503554367852,\"text\":\"速动比率 = （流动资产-存货）/流动负债（扣除了最不容易变现的存货）\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bf8kfppfq74k\",\"created\":1503551252137,\"text\":\"6、业务、战略与财务数据\",\"layout\":null},\"children\":[]}]},\"template\":\"right\",\"theme\":\"classic\",\"version\":\"1.4.43\"}","fileGuid":"0fa0e4841ba494f59098a2a46fd9f7f9","csrf_token":"6b8ea1965a3b25c20375789479abb37c"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by zhangbobell** [comment]
50x 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
