### ISSUE TITLE
反馈 错误500

### ISSUE THREAD

**Issue by sky-mxc** [fex-team/kityminder-editor#490]
错误
 {"data":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"ddbf858a3ceb\",\"created\":1503039283,\"text\":\"线程\",\"hyperlink\":null,\"hyperlinkTitle\":null,\"note\":\"线程是一个程序的多个执行路径，执行调度的单位，依托于进程存在。 线程不仅可以共享进程的内存，而且还拥有一个属于自己的内存空间，这段内存空间也叫做线程栈，是在建立线程时由系统分配的，主要用来保存线程内部所使用的数据，如线程执行函数中所定义的变量。\\n\\n注意：Java中的多线程是一种抢占机制而不是分时机制。抢占机制指的是有多个线程处于可运行状态，但是只允许一个线程在运行，他们通过竞争的方式抢占CPU。\\n\\n多线程\\nhttp://ifeve.com/java-concurrency-thread-directory/\"},\"children\":[{\"data\":{\"id\":\"bf63h7vlkhc0\",\"created\":1503300291274,\"text\":\"实现线程\",\"layout_mind_offset\":{\"x\":0,\"y\":267}},\"children\":[{\"data\":{\"id\":\"bf63o4ue5940\",\"created\":1503300833220,\"text\":\"创建线程\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bf63o9y4ikw0\",\"created\":1503300844330,\"text\":\"继承Thread\",\"progress\":9},\"children\":[]},{\"data\":{\"id\":\"bf63ogv9zhs0\",\"created\":1503300859395,\"text\":\"实现Runnable\",\"progress\":9},\"children\":[]},{\"data\":{\"id\":\"bf65j3wg6bs0\",\"created\":1503306081566,\"text\":\"两中方式的区别及联系\",\"progress\":9,\"note\":\"参考\\nhttps://www.linkedin.com/pulse/20140917120728-90925576-difference-between-implements-runnable-and-extends-thread-in-java\\n\\n\"},\"children\":[]}]},{\"data\":{\"id\":\"bf63pqsysyo0\",\"created\":1503300959387,\"text\":\"资源共享及同步问题\",\"progress\":9,\"note\":\"同步块\\nhttp://ifeve.com/java-concurrency-thread-directory/\\n\\nOracle\\nhttp://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html\\n\\n同步\\nhttp://student-lp.iteye.com/blog/2083170\\n\\n\"},\"children\":[{\"data\":{\"id\":\"bf7v7udgifc0\",\"created\":1503480107636,\"text\":\"同步块\",\"note\":\"Synchronizing Block\\n Synchronized Block/方法控制对类成员变量的访问；Java中的每一个对象都有唯一的一个内置的锁，每个Synchronized Block/方法只有持有调用该方法被锁定对象的锁才可以访问，否则所属线程阻塞；机锁具有独占性、一旦被一个Thread持有，其他的Thread就不能再拥有（不能访问其他同步方法），方法一旦执行，就独占该锁，直到从该方法返回时才将锁释放，此后被阻塞的线程方能获得该锁，重新进入可执行状态。\"},\"children\":[]}]},{\"data\":{\"id\":\"bf63oxpjkv40\",\"created\":1503300896053,\"text\":\"线程状态\",\"progress\":9,\"note\":\"http://www.cnblogs.com/DreamSea/archive/2012/01/11/JavaThread.html\\n\",\"image\":\"http://kityminder-img.gz.bcebos.com/6ebd4466e921436a6512e43111f4d451f4b82119\",\"imageTitle\":\"线程状态\",\"imageSize\":{\"width\":200,\"height\":158},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bf708nwdwio0\",\"created\":1503392717500,\"text\":\"新生状态（New）\",\"note\":\"当一个线程的实例被创建即使用new关键字和Thread类或其子类创建一个线程对象后，此时该线程处于新生(new)状态，处于新生状态的线程有自己的内存空间，但该线程并没有运行，此时线程还不是活着的（not alive）；\\n\\n\"},\"children\":[]},{\"data\":{\"id\":\"bf709ap4p3k0\",\"created\":1503392767127,\"text\":\"就绪状态（Runnable）\",\"note\":\"通过调用线程实例的start()方法来启动线程使线程进入就绪状态(runnable)；处于就绪状态的线程已经具备了运行条件，但还没有被分配到CPU即不一定会被立即执行，此时处于线程就绪队列，等待系统为其分配CPCU，等待状态并不是执行状态； 此时线程是活着的（alive）；\"},\"children\":[]},{\"data\":{\"id\":\"bf70ahq3kts0\",\"created\":1503392860787,\"text\":\"运行状态（Running）\",\"note\":\" 一旦获取CPU(被JVM选中)，线程就进入运行(running)状态，线程的run()方法才开始被执行；在运行状态的线程执行自己的run()方法中的操作，直到调用其他的方法而终止、或者等待某种资源而阻塞、或者完成任务而死亡；如果在给定的时间片内没有执行结束，就会被系统给换下来回到线程的等待状态；此时线程是活着的（alive）；\"},\"children\":[]},{\"data\":{\"id\":\"bf70b56bkh40\",\"created\":1503392911834,\"text\":\"阻塞状态（Blocked）\",\"note\":\"通过调用join()、sleep()、wait()或者资源被暂用使线程处于阻塞(blocked)状态；处于Blocking状态的线程仍然是活着的（alive）\"},\"children\":[]},{\"data\":{\"id\":\"bf70bl6rgag0\",\"created\":1503392946689,\"text\":\"死亡状态（Dead）\",\"note\":\"当一个线程的run()方法运行完毕或被中断或被异常退出，该线程到达死亡(dead)状态。此时可能仍然存在一个该Thread的实例对象，当该Thready已经不可能在被作为一个可被独立执行的线程对待了，线程的独立的call stack已经被dissolved。一旦某一线程进入Dead状态，他就再也不能进入一个独立线程的生命周期了。对于一个处于Dead状态的线程调用start()方法，会出现一个运行期(runtime exception)的异常；处于Dead状态的线程不是活着的（not alive）。\"},\"children\":[]}]},{\"data\":{\"id\":\"bf63pgifqps0\",\"created\":1503300936983,\"text\":\"优先级\",\"note\":\"每个类都有自己的优先级，一般property用1-10的整数表示，默认优先级是5，优先级最高是10；优先级高的线程并不一定比优先级低的线程执行的机会高，只是执行的机率高；默认一个线程的优先级和创建他的线程优先级相同\",\"progress\":9},\"children\":[]},{\"data\":{\"id\":\"bf63pj8rrbs0\",\"created\":1503300942928,\"text\":\"Thread常用方法\",\"progress\":2,\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bf70kdlo0dk0\",\"created\":1503393635455,\"text\":\"run()\",\"note\":\"//包含线程运行时所执行的代码 \"},\"children\":[]},{\"data\":{\"id\":\"bf7v0s4r8uo0\",\"created\":1503479554207,\"text\":\"Thread.sleep()/sleep(long millis)\",\"note\":\"当前线程睡眠/millis的时间（millis指定睡眠时间是其最小的不执行时间，因为sleep(millis)休眠到达后，无法保证会被JVM立即调度）；sleep()是一个静态方法(static method) ，所以他不会停止其他的线程也处于休眠状态；线程sleep()时不会失去拥有的对象锁。 作用：保持对象锁，让出CPU，调用目的是不让当前线程独自霸占该进程所获取的CPU资源，以留一定的时间给其他线程执行的机会；\"},\"children\":[]},{\"data\":{\"id\":\"bf7v1kaan2o0\",\"created\":1503479615492,\"text\":\"Thread.yield()\",\"note\":\"使当前线程交出CPU，让CPU去执行其他的任务，但不会是线程进入阻塞状态，而是重置为就绪状态，yield方法不会释放锁\"},\"children\":[]},{\"data\":{\"id\":\"bf7v2a8rnvk0\",\"created\":1503479671996,\"text\":\"join()/join(long millis)/join(long millis,int nanoseconds)\",\"note\":\"等待线程终止，直白的说 就是发起该子线程的线程 只有等待该子线程运行结束才能继续往下运行\"},\"children\":[]},{\"data\":{\"id\":\"bf7v6ecxy680\",\"created\":1503479994412,\"text\":\"wait()\",\"note\":\" 当一个线程执行到wait()方法时，他就进入到一个和该对象相关的等待池(Waiting Pool)中，同时失去了对象的机锁—暂时的，wait后还要返还对象锁。当前线程必须拥有当前对象的锁，如果当前线程不是此锁的拥有者，会抛出IllegalMonitorStateException异常,所以wait()必须在synchronized block中调用。\"},\"children\":[]},{\"data\":{\"id\":\"bf7v740ywjk0\",\"created\":1503480050284,\"text\":\"object.notify()/notifyAll()\",\"note\":\" 唤醒在当前对象等待池中等待的第一个线程/所有线程。notify()/notifyAll()也必须拥有相同对象锁，否则也会抛出IllegalMonitorStateException异常。\"},\"children\":[]},{\"data\":{\"id\":\"bf7v8a72ccw0\",\"created\":1503480142078,\"text\":\"interrupt()\",\"note\":\"中断线程，自stop函数过时之后，我们通过interrupt方法和isInterrupted()方法来停止正在运行的线程，注意只能中断已经处于阻塞的线程\"},\"children\":[]},{\"data\":{\"id\":\"bf7v8xb4j280\",\"created\":1503480192389,\"text\":\"getId()\",\"note\":\"获取当前线程的ID\"},\"children\":[]},{\"data\":{\"id\":\"bf7v947r9iw0\",\"created\":1503480207423,\"text\":\"getName()/setName()\",\"note\":\"/获取和设置线程的名字\"},\"children\":[]},{\"data\":{\"id\":\"bf7v9ddyncg0\",\"created\":1503480227389,\"text\":\"getPriority()/setPriority()\",\"note\":\"获取和这是线程的优先级 一般property用1-10的整数表示，默认优先级是5，优先级最高是10，优先级高的线程被执行的机率高\"},\"children\":[]},{\"data\":{\"id\":\"bf7v9ouvkpc0\",\"created\":1503480252356,\"text\":\"setDaemon()/isDaemo()\",\"note\":\"设置和判断是否是守护线程\"},\"children\":[]},{\"data\":{\"id\":\"bf7v9w4pu5c0\",\"created\":1503480268189,\"text\":\"currentThread()\",\"note\":\"静态函数获取当前线程\"},\"children\":[]}]},{\"data\":{\"id\":\"bf701xhp8h40\",\"created\":1503392189830,\"text\":\"线程通信\",\"progress\":5,\"note\":\"参考 handler Message MessageQuenue Looper\\nhttp://www.cnblogs.com/younghao/p/5116819.html\\n\\nhttp://www.jianshu.com/p/7657f541c461\\n\\nJava线程通信\\n\\nhttp://ifeve.com/thread-signaling/\\n\"},\"children\":[{\"data\":{\"id\":\"bf7mzful8800\",\"created\":1503456880227,\"text\":\"Java中的通信方式\",\"note\":\"http://ifeve.com/thread-signaling/\\n\",\"progress\":2},\"children\":[]},{\"data\":{\"id\":\"bf7mzrfl6iw0\",\"created\":1503456905441,\"text\":\"Android中的消息机制\",\"progress\":9},\"children\":[]}]}]},{\"data\":{\"id\":\"bf3izl904y00\",\"created\":1503039367716,\"text\":\"线程池\",\"layout_mind_offset\":{\"x\":-52,\"y\":292},\"note\":\"Android开发艺术探索\\nhttps://tom510230.gitbooks.io/android_ka_fa_yi_shu_tan_suo/content/chapter11.html\\n\\nhttp://www.cnblogs.com/whoislcj/p/5607734.html\\n\\nhttp://blog.csdn.net/u010687392/article/details/49850803\\n\\nhttp://www.cnblogs.com/RGogoing/p/4766971.html\"},\"children\":[{\"data\":{\"id\":\"bf63lxl9s200\",\"created\":1503300660703,\"text\":\"ThreadPoolExecutor\"},\"children\":[]},{\"data\":{\"id\":\"bf63mhsktyo0\",\"created\":1503300704680,\"text\":\"newCachedThreadPool \"},\"children\":[]},{\"data\":{\"id\":\"bf63mqruzqo0\",\"created\":1503300724228,\"text\":\"newSingleThreadExecutor \"},\"children\":[]},{\"data\":{\"id\":\"bf63n034oyw0\",\"created\":1503300744500,\"text\":\"newFixedThreadPool \"},\"children\":[]},{\"data\":{\"id\":\"bf63n418lzs0\",\"created\":1503300753093,\"text\":\"newScheduledThreadPool \"},\"children\":[]},{\"data\":{\"id\":\"bf63ndj4enc0\",\"created\":1503300773765,\"text\":\"ExecutorService\"},\"children\":[]}]},{\"data\":{\"id\":\"bf63hi911xc0\",\"created\":1503300313854,\"text\":\"相关API\",\"expandState\":\"expand\",\"layout_mind_offset\":{\"x\":-746,\"y\":-615}},\"children\":[{\"data\":{\"id\":\"bf3izja340o0\",\"created\":1503039363428,\"text\":\"FutureTask\"},\"children\":[]},{\"data\":{\"id\":\"bf3iysyyrw00\",\"created\":1503039306159,\"text\":\"Thread\",\"hyperlink\":\"https://developer.android.com/reference/java/lang/Thread.html\",\"hyperlinkTitle\":\"doc\"},\"children\":[]},{\"data\":{\"id\":\"bf3iyv5dvnk0\",\"created\":1503039310901,\"text\":\"Runnable\"},\"children\":[]},{\"data\":{\"id\":\"bf3izatij880\",\"created\":1503039345012,\"text\":\"Callable\"},\"children\":[]},{\"data\":{\"id\":\"bf3izexpdjc0\",\"created\":1503039353972,\"text\":\"Future\"},\"children\":[]},{\"data\":{\"id\":\"bf63hsuocmw0\",\"created\":1503300336931,\"text\":\"Executors\"},\"children\":[]},{\"data\":{\"id\":\"bf63i5zf6oo0\",\"created\":1503300365516,\"text\":\"ExecutorService\"},\"children\":[]},{\"data\":{\"id\":\"bf63ias0sq00\",\"created\":1503300375952,\"text\":\"ThreadPoolExecutor\"},\"children\":[]},{\"data\":{\"id\":\"bf63ietrm5c0\",\"created\":1503300384765,\"text\":\"Executor\"},\"children\":[]}]},{\"data\":{\"id\":\"bf63jhqyht40\",\"created\":1503300469490,\"text\":\"Android线程\",\"hyperlink\":\"https://developer.android.com/guide/components/processes-and-threads.html?hl=zh-cn#Threads\",\"hyperlinkTitle\":\"doc\",\"layout_mind_offset\":{\"x\":44,\"y\":-325}},\"children\":[{\"data\":{\"id\":\"bf63nr9f13c0\",\"created\":1503300803653,\"text\":\"UI线程\",\"progress\":9},\"children\":[]},{\"data\":{\"id\":\"bf63ntmr2280\",\"created\":1503300808813,\"text\":\"工作线程\",\"progress\":9},\"children\":[]},{\"data\":{\"id\":\"bf63r68d4kw0\",\"created\":1503301071334,\"text\":\"异步任务\",\"progress\":9},\"children\":[]}]},{\"data\":{\"id\":\"bf646ejxpko0\",\"created\":1503302264910,\"text\":\"参考资料\",\"note\":\"1.https://developer.android.com/reference/java/lang/Thread.html\\n\\n2.http://www.cnblogs.com/DreamSea/archive/2012/01/11/JavaThread.html#navigation\\n\\n3.http://www.cnblogs.com/whoislcj/p/5603277.html\\n\\n4.https://developer.android.com/guide/components/processes-and-threads.html?hl=zh-cn\\n\\n5.http://www.cnblogs.com/younghao/p/5141295.html\\n\\n6.http://www.jianshu.com/p/b8197dd2934c\\n\\n7.Runnable和Thread 创建的区别\\nhttp://www.importnew.com/20584.html\\n\\n8.Runnable 和Thread 区别和联系\\nhttps://my.oschina.net/leejun2005/blog/483999\\n\\n9. Runnable和Thread的区别\\nhttps://www.linkedin.com/pulse/20140917120728-90925576-difference-between-implements-runnable-and-extends-thread-in-java\",\"layout_mind_offset\":{\"x\":18,\"y\":-259}},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"dfa6d1cc01f4cb495d495c0b5df273bc","csrf_token":"e85b4647615b97825f9c0399ae64652c"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by zhangbobell** [comment]
50x问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
