### ISSUE TITLE
503

### ISSUE THREAD

**Issue by buerq** [fex-team/kityminder-editor#498]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"5fce4e8a85f7\",\"created\":1504489857,\"text\":\"人员管理\"},\"children\":[{\"data\":{\"id\":\"bfhtasadsvco\",\"created\":1504490295535,\"text\":\"入口\"},\"children\":[{\"data\":{\"id\":\"bfhtcb6pi5ck\",\"created\":1504490415036,\"text\":\"首页-人员管理\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtcgwplnkk\",\"created\":1504490427492,\"text\":\"人员管理\"},\"children\":[{\"data\":{\"id\":\"bfhtd55joe0w\",\"created\":1504490480269,\"text\":\"数据来源\"},\"children\":[{\"data\":{\"id\":\"bfhtflhm434s\",\"created\":1504490672556,\"text\":\"人员信息\"},\"children\":[{\"data\":{\"id\":\"bfhtfzxz5s00\",\"created\":1504490704020,\"text\":\"新增创建\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtfmdw0tss\",\"created\":1504490674508,\"text\":\"部门\"},\"children\":[{\"data\":{\"id\":\"bfhtfs9xkfco\",\"created\":1504490687329,\"text\":\"调取剧组管理的部门数据\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bfhtd7wmcu0w\",\"created\":1504490486260,\"text\":\"筛选\"},\"children\":[{\"data\":{\"id\":\"bfhtg934m9s0\",\"created\":1504490723923,\"text\":\"默认：部门-全部；状态-驻组；姓名-空着\"},\"children\":[]},{\"data\":{\"id\":\"bfhtk6pf394w\",\"created\":1504491032197,\"text\":\"部门\"},\"children\":[{\"data\":{\"id\":\"bfhtkqow34wg\",\"created\":1504491075701,\"text\":\"调取剧组管理的部门数据\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtkbtuxy8g\",\"created\":1504491043349,\"text\":\"状态\"},\"children\":[{\"data\":{\"id\":\"bfhtksuaigw0\",\"created\":1504491080381,\"text\":\"全部\"},\"children\":[]},{\"data\":{\"id\":\"bfhtktogth4w\",\"created\":1504491082205,\"text\":\"驻组\"},\"children\":[]},{\"data\":{\"id\":\"bfhtkujteps0\",\"created\":1504491084101,\"text\":\"离组\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtkkex4r48\",\"created\":1504491062037,\"text\":\"姓名\"},\"children\":[{\"data\":{\"id\":\"bfhtl4c0hh4w\",\"created\":1504491105397,\"text\":\"可为空\"},\"children\":[]},{\"data\":{\"id\":\"bfhtl6sx0l4w\",\"created\":1504491110773,\"text\":\"用户填写\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtjvijfsgs\",\"created\":1504491007837,\"text\":\"确定\"},\"children\":[]},{\"data\":{\"id\":\"bfhtjwfh6t4w\",\"created\":1504491009828,\"text\":\"取消\"},\"children\":[]},{\"data\":{\"id\":\"bfhtlo0voxs0\",\"created\":1504491148260,\"text\":\"筛选数据\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtdco7nl4o\",\"created\":1504490496636,\"text\":\"增加\"},\"children\":[]},{\"data\":{\"id\":\"bfhtdzd2sg00\",\"created\":1504490546028,\"text\":\"人员设置\"},\"children\":[]},{\"data\":{\"id\":\"bfhte1ooq9cs\",\"created\":1504490551084,\"text\":\"组别设置\"},\"children\":[]},{\"data\":{\"id\":\"bfhte68lv6wo\",\"created\":1504490560996,\"text\":\"状态设置\"},\"children\":[]}]},{\"data\":{\"id\":\"bfhtcm4yskws\",\"created\":1504490438876,\"text\":\"剧组管理\"},\"children\":[]},{\"data\":{\"id\":\"bfhtcq5uswg8\",\"created\":1504490447636,\"text\":\"签到管理\"},\"children\":[]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"179788190be43e5f031129e0855dd64c","csrf_token":"5dfe77cc03849d3c5e9dd31c58edef5a"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3387.400 QQBrowser/9.6.11984.400

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
