### ISSUE TITLE
脑图503

### ISSUE THREAD

**Issue by yangsongbao** [fex-team/kityminder-editor#509]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"cb06682011b6\",\"created\":1505656794,\"text\":\"新建脑图\"},\"children\":[{\"data\":{\"id\":\"bftasz7hpoo4\",\"created\":1505656839545,\"text\":\"提升多程票量\"},\"children\":[{\"data\":{\"id\":\"bftavtsxehc8\",\"created\":1505657062873,\"text\":\"基础数据\"},\"children\":[{\"data\":{\"id\":\"bftbclqm0mgo\",\"created\":1505658377509,\"text\":\"用户行为分析\"},\"children\":[{\"data\":{\"id\":\"bftbekn33egw\",\"created\":1505658531848,\"text\":\"搜索\"},\"children\":[{\"data\":{\"id\":\"bftbelofbyo8\",\"created\":1505658534105,\"text\":\"多程搜索中航段分步\"},\"children\":[{\"data\":{\"id\":\"bftbfkvzeq04\",\"created\":1505658610750,\"text\":\"程数分布\"},\"children\":[]},{\"data\":{\"id\":\"bftbf6max4ow\",\"created\":1505658579690,\"text\":\"出发地和目的地分布\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bftbfeh6g9kc\",\"created\":1505658596794,\"text\":\"生单\"},\"children\":[{\"data\":{\"id\":\"bftbfhprte04\",\"created\":1505658603844,\"text\":\"多程生单中航段分步\"},\"children\":[{\"data\":{\"id\":\"bftbfkvzeq04\",\"created\":1505658610750,\"text\":\"程数分布\"},\"children\":[]},{\"data\":{\"id\":\"bftbf6max4ow\",\"created\":1505658579690,\"text\":\"出发地和目的地分布\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bftbgodsbm88\",\"created\":1505658696721,\"text\":\"多程航段特点分布\"},\"children\":[{\"data\":{\"id\":\"bftbh8od7bc4\",\"created\":1505658740896,\"text\":\"A-B,C-A\"},\"children\":[]},{\"data\":{\"id\":\"bftbh4j8uwgs\",\"created\":1505658731879,\"text\":\"A-B,B-C\"},\"children\":[]},{\"data\":{\"id\":\"bftbhg0w4dko\",\"created\":1505658756891,\"text\":\"A-B,C-D\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bftauvp1e8g8\",\"created\":1505656988627,\"text\":\"推荐\"},\"children\":[{\"data\":{\"id\":\"bftav4j3xiww\",\"created\":1505657007860,\"text\":\"场景\"},\"children\":[{\"data\":{\"id\":\"bftax573exkc\",\"created\":1505657166038,\"text\":\"地点不确定时间确定\"},\"children\":[{\"data\":{\"id\":\"bftay43t5i0c\",\"created\":1505657242027,\"text\":\"建航线库\"},\"children\":[]}]},{\"data\":{\"id\":\"bftaxca11m0o\",\"created\":1505657181453,\"text\":\"时间不确定地点确定\"},\"children\":[{\"data\":{\"id\":\"bftaxyhekjk0\",\"created\":1505657229788,\"text\":\"新加一种机票产品类型\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bftat2yit4ow\",\"created\":1505656847710,\"text\":\"优化内转\"},\"children\":[{\"data\":{\"id\":\"bftb09062ds8\",\"created\":1505657409419,\"text\":\"数据\"},\"children\":[{\"data\":{\"id\":\"bftb0fwvn3co\",\"created\":1505657424458,\"text\":\"航程类型维度\"},\"children\":[{\"data\":{\"id\":\"bftb134hrpc0\",\"created\":1505657474984,\"text\":\"单程，多程search,order,booking,pay各环节转化率\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bftat7i4p28g\",\"created\":1505656857602,\"text\":\"提升报价覆盖\"},\"children\":[{\"data\":{\"id\":\"bftb2c2vqfsc\",\"created\":1505657572842,\"text\":\"缺口程需求\"},\"children\":[{\"data\":{\"id\":\"bftb2k6srnk0\",\"created\":1505657590493,\"text\":\"调研代理商手中有哪些缺口程政策\"},\"children\":[]},{\"data\":{\"id\":\"bftb2rccja0c\",\"created\":1505657606066,\"text\":\"如何录政策\"},\"children\":[]}]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"174c8c9a55f3c2aac5cb3da0e3345038","csrf_token":"067ba39a9e6f93bed7116f643608194d"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
