### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by foxbaby213** [fex-team/kityminder-editor#517]
错误
 {"data":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":504,"config":{"method":"POST","transformResponse":[null],"url":"bos/get_root_dir","data":{"csrf_token":"1c9f02687fe25f601aab722b0182ebc2"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Gateway Time-out"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
