### ISSUE TITLE
哎呀，脑图出错了

### ISSUE THREAD

**Issue by duyishuaixue** [fex-team/kityminder-editor#518]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"ed3c82e7ee8e\",\"created\":1498563055,\"text\":\"互联速递V2.0\"},\"children\":[{\"data\":{\"id\":\"bdvgbsvyqgg0\",\"created\":1498563223289,\"text\":\"互联速递(商户/用户)\",\"font-size\":24},\"children\":[{\"data\":{\"id\":\"bgbn2t3avrs0\",\"created\":1507519542411,\"text\":\"登录/注册\",\"font-size\":18,\"layout_bottom_offset\":{\"x\":18,\"y\":0},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnpwzdlps0\",\"created\":1507521353257,\"text\":\"上传实名认证\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnqmjzcuo0\",\"created\":1507521408922,\"text\":\"验证码和密码2种登录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbn8dugt340\",\"created\":1507519979410,\"text\":\"支付方式\",\"font-size\":18,\"layout_bottom_offset\":{\"x\":-61,\"y\":9},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbn8ljpsfs0\",\"created\":1507519996175,\"text\":\"支付宝\",\"layout_bottom_offset\":{\"x\":12,\"y\":20},\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbn8sb89mw0\",\"created\":1507520010899,\"text\":\"微信\",\"layout_bottom_offset\":{\"x\":0,\"y\":20},\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbn8t21vs80\",\"created\":1507520012521,\"text\":\"余额\",\"layout_bottom_offset\":{\"x\":-15,\"y\":20},\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbna492g8g0\",\"created\":1507520115254,\"text\":\"订单管理\",\"font-size\":18,\"layout_bottom_offset\":{\"x\":-81,\"y\":-2},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbn5fg14zc0\",\"created\":1507519747799,\"text\":\"下单管理\",\"font-size\":18,\"layout_bottom_offset\":{\"x\":-52,\"y\":11},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbn5ngapeo0\",\"created\":1507519765229,\"text\":\"同城骑手单(1~3单)\",\"font-size\":16,\"layout_bottom_offset\":{\"x\":0,\"y\":18}},\"children\":[]},{\"data\":{\"id\":\"bgbn5s513680\",\"created\":1507519775433,\"text\":\"同城车主单(1~3单)\",\"font-size\":16,\"layout_bottom_offset\":{\"x\":0,\"y\":18}},\"children\":[]}]},{\"data\":{\"id\":\"bgbnad1973k0\",\"created\":1507520134372,\"text\":\"我的订单\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnau1ibo80\",\"created\":1507520171393,\"text\":\"订单状态\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnaxj73ko0\",\"created\":1507520178993,\"text\":\"订单查看\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnbo1izps0\",\"created\":1507520236698,\"text\":\"订单类型\",\"font-size\":16},\"children\":[]}]}]},{\"data\":{\"id\":\"bgbne6ztnc80\",\"created\":1507520434682,\"text\":\"我的钱包\",\"font-size\":18,\"layout_bottom_offset\":{\"x\":-67,\"y\":5},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnfwm0g5k0\",\"created\":1507520568807,\"text\":\"余额\",\"font-size\":16,\"layout_bottom_offset\":{\"x\":0,\"y\":3}},\"children\":[]},{\"data\":{\"id\":\"bgbngbctffc0\",\"created\":1507520600903,\"text\":\"充值\",\"font-size\":16,\"layout_bottom_offset\":{\"x\":0,\"y\":3}},\"children\":[]},{\"data\":{\"id\":\"bgbno442v1c0\",\"created\":1507521212050,\"text\":\"交易记录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnn6g90c80\",\"created\":1507521138776,\"text\":\"活动\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnnhqs5uo0\",\"created\":1507521163357,\"text\":\"优惠券\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnninxqm00\",\"created\":1507521165362,\"text\":\"其他后续动态活动\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnh9keaw00\",\"created\":1507520675372,\"text\":\"设置\",\"font-size\":18,\"expandState\":\"collapse\",\"layout_bottom_offset\":{\"x\":-86,\"y\":4}},\"children\":[{\"data\":{\"id\":\"bgbnd4vxjds0\",\"created\":1507520351729,\"text\":\"个人/商户资料\",\"layout_bottom_offset\":{\"x\":0,\"y\":3},\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwebtxsg0\",\"created\":1507530324530,\"text\":\"版本升级\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqw915o800\",\"created\":1507530313001,\"text\":\"意见反馈\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbre6otqio0\",\"created\":1507531718456,\"text\":\"客服中心\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwebtxsg0\",\"created\":1507530324530,\"text\":\"关于我们\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbndak3zvc0\",\"created\":1507520364075,\"text\":\"退出\",\"layout_bottom_offset\":{\"x\":0,\"y\":1},\"font-size\":16},\"children\":[]}]}]},{\"data\":{\"id\":\"bdvgblgwqsg0\",\"created\":1498563207141,\"text\":\"互联骑手\",\"font-size\":24,\"layout_bottom_offset\":{\"x\":-9,\"y\":0}},\"children\":[{\"data\":{\"id\":\"bgbnu7e415s0\",\"created\":1507521689372,\"text\":\"登录/注册\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnunnb6200\",\"created\":1507521724757,\"text\":\"上传实名认证\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnqmjzcuo0\",\"created\":1507521408922,\"text\":\"验证码和密码2种登录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnx53079c0\",\"created\":1507521919440,\"text\":\"在线考试\",\"font-size\":18},\"children\":[]},{\"data\":{\"id\":\"bgbnxi1o3i80\",\"created\":1507521947657,\"text\":\"任务大厅\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnxpghl600\",\"created\":1507521963791,\"text\":\"语音播报\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnxu80j8w0\",\"created\":1507521974162,\"text\":\"大厅抢单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnxy3dv4w0\",\"created\":1507521982589,\"text\":\"订单详情抢单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnyugwdbs0\",\"created\":1507522053064,\"text\":\"导航送单\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo1tccn1k0\",\"created\":1507522285704,\"text\":\"订单管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo2hkhap40\",\"created\":1507522338439,\"text\":\"已接订单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqm9ylmcg0\",\"created\":1507529531381,\"text\":\"订单分类查询\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo3erln1s0\",\"created\":1507522410703,\"text\":\"我的钱包\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo3qarv3s0\",\"created\":1507522435807,\"text\":\"押金\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo3s5lhgw0\",\"created\":1507522439847,\"text\":\"绑定(支付宝、微信)\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo40ovqe80\",\"created\":1507522458428,\"text\":\"提现\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo42lgdh40\",\"created\":1507522462574,\"text\":\"交易记录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo4dcm5uw0\",\"created\":1507522485984,\"text\":\"邀请分享\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo4jwi1sg0\",\"created\":1507522500247,\"text\":\"骑手\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo4kp1j200\",\"created\":1507522501973,\"text\":\"司机\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo4m1yjvc0\",\"created\":1507522504931,\"text\":\"商户\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnh9keaw00\",\"created\":1507520675372,\"text\":\"设置\",\"font-size\":18,\"expandState\":\"collapse\",\"layout_bottom_offset\":{\"x\":-86,\"y\":4}},\"children\":[{\"data\":{\"id\":\"bgbnd4vxjds0\",\"created\":1507520351729,\"text\":\"个人资料\",\"layout_bottom_offset\":{\"x\":0,\"y\":3},\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbrjmvmq000\",\"created\":1507532145517,\"text\":\"版本升级\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqw915o800\",\"created\":1507530313001,\"text\":\"意见反馈\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwbr7v8g0\",\"created\":1507530318930,\"text\":\"联系我们\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwebtxsg0\",\"created\":1507530324530,\"text\":\"关于我们\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbndak3zvc0\",\"created\":1507520364075,\"text\":\"退出\",\"font-size\":16,\"layout_bottom_offset\":{\"x\":0,\"y\":1}},\"children\":[]}]}]},{\"data\":{\"id\":\"bgbn1m21z140\",\"created\":1507519448734,\"text\":\"互联车主\",\"font-size\":24},\"children\":[{\"data\":{\"id\":\"bgbnu7e415s0\",\"created\":1507521689372,\"text\":\"登录/注册\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnunnb6200\",\"created\":1507521724757,\"text\":\"上传实名/证件认证\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnqmjzcuo0\",\"created\":1507521408922,\"text\":\"验证码和密码2种登录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnxi1o3i80\",\"created\":1507521947657,\"text\":\"任务大厅\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbnxpghl600\",\"created\":1507521963791,\"text\":\"语音播报\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnxu80j8w0\",\"created\":1507521974162,\"text\":\"大厅抢单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnxy3dv4w0\",\"created\":1507521982589,\"text\":\"订单详情抢单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbnyugwdbs0\",\"created\":1507522053064,\"text\":\"导航送单\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo1tccn1k0\",\"created\":1507522285704,\"text\":\"订单管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo2hkhap40\",\"created\":1507522338439,\"text\":\"已接订单\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqm9ylmcg0\",\"created\":1507529531381,\"text\":\"订单分类查询\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo3erln1s0\",\"created\":1507522410703,\"text\":\"我的钱包\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo3qarv3s0\",\"created\":1507522435807,\"text\":\"押金\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo3s5lhgw0\",\"created\":1507522439847,\"text\":\"绑定(支付宝、微信)\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo40ovqe80\",\"created\":1507522458428,\"text\":\"提现\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo42lgdh40\",\"created\":1507522462574,\"text\":\"交易记录\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbqu3q4a200\",\"created\":1507530144721,\"text\":\"我的车辆\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbqvdjn0oo0\",\"created\":1507530244461,\"text\":\"车辆的新增\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqvnxqdbk0\",\"created\":1507530267081,\"text\":\"默认车辆设置\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbo4dcm5uw0\",\"created\":1507522485984,\"text\":\"邀请分享\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbo4jwi1sg0\",\"created\":1507522500247,\"text\":\"骑手\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo4kp1j200\",\"created\":1507522501973,\"text\":\"司机\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbo4m1yjvc0\",\"created\":1507522504931,\"text\":\"商户\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbnh9keaw00\",\"created\":1507520675372,\"text\":\"设置\",\"font-size\":18,\"expandState\":\"collapse\",\"layout_bottom_offset\":{\"x\":-86,\"y\":4}},\"children\":[{\"data\":{\"id\":\"bgbnd4vxjds0\",\"created\":1507520351729,\"text\":\"个人资料\",\"layout_bottom_offset\":{\"x\":0,\"y\":3},\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbrjmvmq000\",\"created\":1507532145517,\"text\":\"版本升级\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqw915o800\",\"created\":1507530313001,\"text\":\"意见反馈\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwbr7v8g0\",\"created\":1507530318930,\"text\":\"联系我们\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbqwebtxsg0\",\"created\":1507530324530,\"text\":\"关于我们\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbndak3zvc0\",\"created\":1507520364075,\"text\":\"退出\",\"layout_bottom_offset\":{\"x\":0,\"y\":1},\"font-size\":16},\"children\":[]}]}]},{\"data\":{\"id\":\"bgbn29r75z40\",\"created\":1507519500321,\"text\":\"管理后台\",\"font-size\":24},\"children\":[{\"data\":{\"id\":\"bgbt0ea3pzs0\",\"created\":1507536280102,\"text\":\"系统管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt3bvyvx40\",\"created\":1507536509986,\"text\":\"权限管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt3u1o0sg0\",\"created\":1507536549513,\"text\":\"菜单管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt4ag50ag0\",\"created\":1507536585216,\"text\":\"数据字典管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt4j59ehc0\",\"created\":1507536604150,\"text\":\"日志管理\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt0hcedmg0\",\"created\":1507536286771,\"text\":\"用户管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt52nn9o00\",\"created\":1507536646620,\"text\":\"系统用户管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt22iro4o0\",\"created\":1507536411233,\"text\":\"代理商管理\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt0r113340\",\"created\":1507536307852,\"text\":\"财务管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt5gso3uw0\",\"created\":1507536677399,\"text\":\"订单统计、导出\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt60c3kkg0\",\"created\":1507536719933,\"text\":\"支出统计\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt64zu0fk0\",\"created\":1507536730075,\"text\":\"结算管理\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt0yz0qrk0\",\"created\":1507536325144,\"text\":\"订单管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt6t2z07s0\",\"created\":1507536782508,\"text\":\"订单查询导出\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt6xmzly80\",\"created\":1507536792425,\"text\":\"订单分类查询\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt1dxd5kg0\",\"created\":1507536357696,\"text\":\"商户/用户管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt7b94s140\",\"created\":1507536822062,\"text\":\"信息管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt7wnpnjs0\",\"created\":1507536868656,\"text\":\"认证审核\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt1jsjjxc0\",\"created\":1507536370465,\"text\":\"骑手管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt7b94s140\",\"created\":1507536822062,\"text\":\"信息管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt7wnpnjs0\",\"created\":1507536868656,\"text\":\"认证审核\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt8jd6g8w0\",\"created\":1507536918085,\"text\":\"在线考试管理\",\"font-size\":16,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbte716gh40\",\"created\":1507537361423,\"text\":\"考试审核\"},\"children\":[]},{\"data\":{\"id\":\"bgbtecmpprk0\",\"created\":1507537373609,\"text\":\"考试题库管理\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgbt1nm70nc0\",\"created\":1507536378788,\"text\":\"司机管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbt7b94s140\",\"created\":1507536822062,\"text\":\"信息管理\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbt7wnpnjs0\",\"created\":1507536868656,\"text\":\"车辆、个人认证审核\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt1vgaqrk0\",\"created\":1507536395846,\"text\":\"活动管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbtan819gw0\",\"created\":1507537083210,\"text\":\"活动内容维护\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt1xkfzpk0\",\"created\":1507536400450,\"text\":\"收支管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbtbbzdw0g0\",\"created\":1507537137106,\"text\":\"收支交易查询\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbtbvm03fk0\",\"created\":1507537179833,\"text\":\"明细查询\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbt268it7k0\",\"created\":1507536419320,\"text\":\"统计分析管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbtc6opj9s0\",\"created\":1507537203941,\"text\":\"订单量图表统计\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbtcjsu9yw0\",\"created\":1507537232489,\"text\":\"订单金额统计\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbtcmcm8680\",\"created\":1507537238038,\"text\":\"省市订单统计\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbtcr49d5c0\",\"created\":1507537248417,\"text\":\"省市订单金额统计\",\"font-size\":16},\"children\":[]}]}]},{\"data\":{\"id\":\"bgbn1xlqlsw0\",\"created\":1507519473869,\"text\":\"PC官网\",\"font-size\":24},\"children\":[{\"data\":{\"id\":\"bgbtgvo2l7s0\",\"created\":1507537571779,\"text\":\"下单管理\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbthg7glj40\",\"created\":1507537616487,\"text\":\"订单价格计算\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbti6ket7c0\",\"created\":1507537673866,\"text\":\"下单\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbtgzrz8l40\",\"created\":1507537580722,\"text\":\"支付\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbtn8jwuns0\",\"created\":1507538070010,\"text\":\"扫码支付\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbth6lhgrc0\",\"created\":1507537595567,\"text\":\"订单查询\",\"font-size\":18,\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgbtnld225c0\",\"created\":1507538097894,\"text\":\"订单查询\",\"font-size\":16},\"children\":[]},{\"data\":{\"id\":\"bgbtnnhem880\",\"created\":1507538102510,\"text\":\"订单状态查询\",\"font-size\":16},\"children\":[]}]},{\"data\":{\"id\":\"bgbtw9wyvjc0\",\"created\":1507538778254,\"text\":\"常用地址管理\",\"font-size\":16},\"children\":[]}]}]},\"template\":\"filetree\",\"theme\":\"snow\",\"version\":\"1.4.43\"}","fileGuid":"90fb5b3c9801193a5a6b592927cfbfb7","csrf_token":"f6d00f36fa9cb7397fafd839e8ef6d73"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
