### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ZGC-demo** [fex-team/kityminder-editor#519]
错误
 {"data":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":504,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"dcd70fbd56a5\",\"created\":1507732077,\"text\":\"概论①\"},\"children\":[{\"data\":{\"id\":\"bge2pzmifbs0\",\"created\":1507766795571,\"text\":\"电子计算机：一种能够高效、快速、精确地对数字信息进行存储、运算、输出的电子设备\",\"expandState\":\"expand\",\"layout_mind_offset\":{\"x\":1.9999999403955258,\"y\":-159.99999523162853},\"priority\":1},\"children\":[{\"data\":{\"id\":\"bge2r908tn40\",\"created\":1507766894357,\"text\":\"1、信息的数字化表示\",\"priority\":null},\"children\":[{\"data\":{\"id\":\"bge2rknqrlc0\",\"created\":1507766919722,\"text\":\"在计算机中用数字代码（二进制）表示各种信息\"},\"children\":[]},{\"data\":{\"id\":\"bge2rwqpt5k0\",\"created\":1507766946024,\"text\":\"在物理机制上用数字信号表示数字代码\"},\"children\":[]},{\"data\":{\"id\":\"bge2s8k4j680\",\"created\":1507766971746,\"text\":\"优点\"},\"children\":[{\"data\":{\"id\":\"bge2sz4e6140\",\"created\":1507767029568,\"text\":\"1）物理上易实现信息的表示与存储\"},\"children\":[]},{\"data\":{\"id\":\"bge2tdqzzps0\",\"created\":1507767061410,\"text\":\"2）抗干扰能力强，可靠性高\"},\"children\":[]},{\"data\":{\"id\":\"bge2tpai5fs0\",\"created\":1507767086534,\"text\":\"3）数值的表示范围大，精度高\"},\"children\":[]},{\"data\":{\"id\":\"bge2tychalc0\",\"created\":1507767106245,\"text\":\"4）可表示的信息类型广泛\"},\"children\":[]},{\"data\":{\"id\":\"bge2u4c4lb40\",\"created\":1507767119284,\"text\":\"5）能用数字逻辑技术进行处理\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bge2udcdqcg0\",\"created\":1507767138890,\"text\":\"2、存储程序的工作方式\",\"priority\":null},\"children\":[{\"data\":{\"id\":\"bge2umkyfpk0\",\"created\":1507767159000,\"text\":\"1）事先编制程序\"},\"children\":[]},{\"data\":{\"id\":\"bge2vx393og0\",\"created\":1507767260238,\"text\":\"2）事先存储程序\"},\"children\":[]},{\"data\":{\"id\":\"bge2w0t48yw0\",\"created\":1507767268333,\"text\":\"3）自动连续的执行程序\"},\"children\":[]},{\"data\":{\"id\":\"bge2w73xllc0\",\"created\":1507767282047,\"text\":\"4）输出结果\"},\"children\":[]}]},{\"data\":{\"id\":\"bge2wczeymw0\",\"created\":1507767294835,\"text\":\"3、计算机的分类\",\"priority\":null},\"children\":[{\"data\":{\"id\":\"bge2wj3bg540\",\"created\":1507767308131,\"text\":\"模拟计算机\"},\"children\":[{\"data\":{\"id\":\"bge2wpc8y1s0\",\"created\":1507767321732,\"text\":\"由模拟运算器件组成，处理在时间和数值上连续的模拟量（电流、电压）\"},\"children\":[]}]},{\"data\":{\"id\":\"bge2xfpigog0\",\"created\":1507767379130,\"text\":\"数字计算机\"},\"children\":[{\"data\":{\"id\":\"bge2xjb15tc0\",\"created\":1507767386962,\"text\":\"由逻辑器件组成，处理离散的数字量\"},\"children\":[{\"data\":{\"id\":\"bge2yr7naw80\",\"created\":1507767482536,\"text\":\"专用计算机\"},\"children\":[{\"data\":{\"id\":\"bge2yznktm80\",\"created\":1507767500913,\"text\":\"ATM\"},\"children\":[]}]},{\"data\":{\"id\":\"bge2yvbst9c0\",\"created\":1507767491494,\"text\":\"通用计算机\"},\"children\":[{\"data\":{\"id\":\"bge2z6sqv2o0\",\"created\":1507767516463,\"text\":\"个人计算机\"},\"children\":[]}]},{\"data\":{\"id\":\"bge2zn07s0g0\",\"created\":1507767551743,\"text\":\"根据结构规模、性能指标依次递减分为：巨型机（超算）、大型机、中型机、小型机、微型机。随着集成电路的发展，类型也在变化\"},\"children\":[]}]}]}]}]},{\"data\":{\"id\":\"bge3290v0oo0\",\"created\":1507767756400,\"text\":\"冯诺依曼体系\",\"priority\":2},\"children\":[{\"data\":{\"id\":\"bge32e5ze5k0\",\"created\":1507767767594,\"text\":\"1、用二进制代码表示程序和数据\"},\"children\":[]},{\"data\":{\"id\":\"bge32liim140\",\"created\":1507767783589,\"text\":\"2、计算机采用存储程序的工作方式\"},\"children\":[]},{\"data\":{\"id\":\"bge32tqn4vc0\",\"created\":1507767801495,\"text\":\"3、计算机硬件由存储器、控制器、运算器、输入设备、输出设备组成\"},\"children\":[]},{\"data\":{\"id\":\"bge33hjews80\",\"created\":1507767853300,\"text\":\"计算机发展趋势\"},\"children\":[{\"data\":{\"id\":\"bge33l79vhk0\",\"created\":1507767861273,\"text\":\"巨型化\"},\"children\":[]},{\"data\":{\"id\":\"bge33tq2gw00\",\"created\":1507767879825,\"text\":\"微型化\"},\"children\":[]},{\"data\":{\"id\":\"bge33zhvcls0\",\"created\":1507767892389,\"text\":\"多媒体化\"},\"children\":[]},{\"data\":{\"id\":\"bge342o30uo0\",\"created\":1507767899295,\"text\":\"网络化\"},\"children\":[]},{\"data\":{\"id\":\"bge344s9ka00\",\"created\":1507767903901,\"text\":\"智能化\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bge3492kbmo0\",\"created\":1507767913231,\"text\":\"计算机系统的组织\",\"priority\":3},\"children\":[{\"data\":{\"id\":\"bge34jcuzdc0\",\"created\":1507767935622,\"text\":\"硬件：构成计算机系统的实体和装置之类的有形设备，是组成计算机系统的物质基础\"},\"children\":[{\"data\":{\"id\":\"bge36hmqu1k0\",\"created\":1507768088594,\"text\":\"1）主要功能部件\"},\"children\":[{\"data\":{\"id\":\"bge36tst9r40\",\"created\":1507768115082,\"text\":\"①CPU：由运算器和控制器组成\"},\"children\":[{\"data\":{\"id\":\"bge37e68qhk0\",\"created\":1507768159430,\"text\":\"运算器\"},\"children\":[{\"data\":{\"id\":\"bge37j4mcgo0\",\"created\":1507768170216,\"text\":\"功能：两类（算术和逻辑）数据的运算\"},\"children\":[]},{\"data\":{\"id\":\"bge380n5ubc0\",\"created\":1507768208342,\"text\":\"组成\"},\"children\":[{\"data\":{\"id\":\"bge388qofg00\",\"created\":1507768225969,\"text\":\"ALU（算术逻辑单元），用来进行算术和逻辑运算以及各种位移、循环等操作，是CPU的执行部件\"},\"children\":[]},{\"data\":{\"id\":\"bge396pxbcw0\",\"created\":1507768299934,\"text\":\"单次运算位数越多，计算精度越高，电子器件也越多（8位、16位、32位、64位）\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bge3a57wvhc0\",\"created\":1507768375033,\"text\":\"控制器\"},\"children\":[{\"data\":{\"id\":\"bge3a90exjk0\",\"created\":1507768383286,\"text\":\"功能：产生控制命令（微命令）。控制全机操作\"},\"children\":[]},{\"data\":{\"id\":\"bge3b6dpn4w0\",\"created\":1507768455924,\"text\":\"组成\"},\"children\":[{\"data\":{\"id\":\"bge3e2iyjts0\",\"created\":1507768682627,\"text\":\"指令信息、状态信息、时序信息——》微命令发生器——》微命令序列\"},\"children\":[]}]}]}]},{\"data\":{\"id\":\"bge3es9yd400\",\"created\":1507768738679,\"text\":\"②存储器\"},\"children\":[{\"data\":{\"id\":\"bge3exiaxvk0\",\"created\":1507768750067,\"text\":\"功能：以二进制代码形式存储数据和数字化后的程序\"},\"children\":[]},{\"data\":{\"id\":\"bge3fflhcrk0\",\"created\":1507768789442,\"text\":\"存储单元：在存储器中保存一个n位二进制的n个触发器，组成一个存储单元\"},\"children\":[]},{\"data\":{\"id\":\"bge3g2o5g6g0\",\"created\":1507768839669,\"text\":\"组成的\"},\"children\":[]}]},{\"data\":{\"id\":\"bge3ew2f7yo0\",\"created\":1507768746930,\"text\":\"分支主题\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bge35frol9k0\",\"created\":1507768006175,\"text\":\"软件：由硬件表达的各种内在信息，包括数据与控制程序。因为它们是无形的东西，所以称为软件或软设备\"},\"children\":[]}]}]},\"template\":\"default\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"bcee657462932c6658061c23136fc5fd","csrf_token":"a463cef65e877bff1d0386aaeea04729"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Gateway Timeout"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
