### ISSUE TITLE
503错误

### ISSUE THREAD

**Issue by 312Aroha** [fex-team/kityminder-editor#522]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"40a9a053d79a\",\"created\":1507858076,\"text\":\"史纲\"},\"children\":[{\"data\":{\"id\":\"bgez3fi6hygo\",\"created\":1507858124389,\"text\":\"第一章 外国侵略\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgez3zebux44\",\"created\":1507858167692,\"text\":\"一、外国侵略、半殖半封\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgez85glqw0k\",\"created\":1507858494347,\"text\":\"（二）外国侵略\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgezbobgua04\",\"created\":1507858770488,\"text\":\"1.不平等条约\\n——第一个：中英《南京条约》\\n——中英《虎门》、中美《望厦》、中法《黄埔》\"},\"children\":[]},{\"data\":{\"id\":\"bgezctb9xvs4\",\"created\":1507858859724,\"text\":\"2.近代史起点\\n——沦为半殖半封\\n——开始反帝反封的资产阶级民主革命\"},\"children\":[]}]},{\"data\":{\"id\":\"bgezatyp87sc\",\"created\":1507858704412,\"text\":\"（三）半殖半封\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgezerr04cg0\",\"created\":1507859013050,\"text\":\"1.半殖的原因\\n——被殖民：主权沦丧\\n——半殖民：有一定主权（长期统一大国、人们顽强持久反抗、列强间矛盾）\"},\"children\":[]},{\"data\":{\"id\":\"bgezg7ttfhcg\",\"created\":1507859126413,\"text\":\"2.半封的原因\\n——出现资本主义生产关系\\n——列强不愿中国成为独立的资本主义国家\"},\"children\":[]},{\"data\":{\"id\":\"bgezkcyp0408\",\"created\":1507859451048,\"text\":\"3.基本特征\\n——被列强支配、封建势力衰弱、自然经济残存、\\n\\t   新兴民族资本弱小、发展不平衡、农民破产\"},\"children\":[]},{\"data\":{\"id\":\"bgezmro92sgk\",\"created\":1507859639797,\"text\":\"4.阶级变动\\n——地主：官僚地主&城居地主+资本家\\n——农民：贫农+雇农（工人后备军、革命主力军）\\n——工人：新生产力代表&最革命阶级（3重压迫+剥削最深+革命性最强、组织纪律性强+天然联系农民）\\n——资产阶级：官僚买办（打击）+民族资本（联合）\"},\"children\":[]}]},{\"data\":{\"id\":\"bgezmfl5g204\",\"created\":1507859613488,\"text\":\"（四）主要矛盾&历史任务\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgezr7pqdeog\",\"created\":1507859988171,\"text\":\"1.主要矛盾\\n——帝国主义和中华民族的矛盾（最主要）\\n——封建主义和人民大众的矛盾\"},\"children\":[]},{\"data\":{\"id\":\"bgezrt505ow8\",\"created\":1507860034807,\"text\":\"2.历史任务\\n——民族独立、人民解放（扫除障碍、创造前提）\\n——国家富强、人民富裕（最终目的、必然要求）\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgeztbo3r08w\",\"created\":1507860153508,\"text\":\"二、武装反抗、民族独立\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgeztmg3j2wc\",\"created\":1507860176969,\"text\":\"（一）反抗\\n——近代史上第一次大规模的反侵略武装斗争：三元里\"},\"children\":[]},{\"data\":{\"id\":\"bgezufknpxs8\",\"created\":1507860240371,\"text\":\"（二）粉碎瓜分中国的阴谋\\n——列强侵略的最终目的：瓜分中国、灭亡中国\\n——未能瓜分的原因：1.列强间的矛盾（重要原因）2.中华民族反抗（根本原因）\"},\"children\":[]}]},{\"data\":{\"id\":\"bgezw74ndp4c\",\"created\":1507860378717,\"text\":\"三、反抗失败、民族觉醒\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgezwgo3lswg\",\"created\":1507860399485,\"text\":\"（一）失败原因\\n——社会制度腐败（根本原因）\\n——经济技术落后\"},\"children\":[]},{\"data\":{\"id\":\"bgezx432f8gk\",\"created\":1507860450456,\"text\":\"（二）民族觉醒\\n——鸦片战争，开始觉醒\\n（林则徐-睁眼看世界的第一人、魏源-《海国图志》-师夷长技以制夷）\\n——甲午战争，普遍觉醒\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgez3x8wrq0c\",\"created\":1507858163011,\"text\":\"第二章 早期探索\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf064rcujso\",\"created\":1507861157202,\"text\":\"一、太平天国-农民阶级\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf08i8h5z40\",\"created\":1507861343263,\"text\":\"（一）太平天国\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf08ul3fwo4\",\"created\":1507861370148,\"text\":\"1.军事的全盛时期：1856年上半年\\n由盛转衰的分水岭：1856.9天京事变\"},\"children\":[]},{\"data\":{\"id\":\"bgf0a36q40wg\",\"created\":1507861467234,\"text\":\"2.前期《天朝田亩》：a.最能体现特色b.以解决土地问题为中心c.根本上否定了土地所有制d.未实施\\n  后期《资政新篇》：a.资本主义色彩b.未实施\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf0dultvy80\",\"created\":1507861762013,\"text\":\"（二）农民战争的最高峰原因\\n——《天朝田亩》较完整表达了农民对土地的渴望\\n——《资政新篇》第一个较系统的发展资本主义的方案（不同于以往农民战争的新历史特点）\"},\"children\":[]},{\"data\":{\"id\":\"bgf0gsm61xc0\",\"created\":1507861992772,\"text\":\"（三）失败的根本原因\\n——农民阶级不是新生产力和生产关系的代表\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf06er8ldcs\",\"created\":1507861178962,\"text\":\"二、洋务运动-地主阶级\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf0hqmhxggk\",\"created\":1507862066803,\"text\":\"（一）洋务运动\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf0i7ubmnco\",\"created\":1507862104281,\"text\":\"1.目的\\n——首要：挽救满清政府（自强）\\n——乘机：发展汉人政治、经济、军事（求富）\"},\"children\":[]},{\"data\":{\"id\":\"bgf0jgmg5r4g\",\"created\":1507862201761,\"text\":\"2.指导思想（冯桂芬）\\n——中学为体-封建统治\\n——西学为用-西方工业&技术（工业支配技术）\"},\"children\":[]},{\"data\":{\"id\":\"bgf0lydikm8g\",\"created\":1507862397131,\"text\":\"3.兴办事业\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf0ma1h3qos\",\"created\":1507862422524,\"text\":\"A.近代企业\\n——首办：军用工业（福船、上兵、金天湖）\\n——民用企业：资本主义性质的近代企业（官督商办：开船上天）\",\"note\":\"福船，上兵，金天湖\\n————福州最大造船厂、上海最大兵工厂\\n————南京金陵机器局、天津机器局、湖北枪炮厂\\n开船上天\\n————开平矿务局、轮船招商局、上海机器织布局、天津电报局\"},\"children\":[]},{\"data\":{\"id\":\"bgf0t60hp0ws\",\"created\":1507862962307,\"text\":\"B.新式海陆军\\n——福建、广东、南洋、北洋（主力）\"},\"children\":[]},{\"data\":{\"id\":\"bgf0ufxq120c\",\"created\":1507863062271,\"text\":\"C.新学堂&留学生\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgf0v03ejzsw\",\"created\":1507863106150,\"text\":\"（二）失败\\n——标志：甲午战争-北洋海军全军覆没\\n——原因：封建、依附、腐朽\\n——根本原因：中学为体，西学为用\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf06j8dk3cw\",\"created\":1507861188706,\"text\":\"三、维新运动-资产阶级\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf0wnssu5ko\",\"created\":1507863236116,\"text\":\"（一）维新运动\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf0xl06oywo\",\"created\":1507863308397,\"text\":\"1.历史条件\\n——民族资本主义初步发展、民族觉醒、救国共识\"},\"children\":[]},{\"data\":{\"id\":\"bgf0y2mojcow\",\"created\":1507863346762,\"text\":\"2.新旧论战的实质\\n——资产阶级与封建主义思想第一次正面交锋\"},\"children\":[]},{\"data\":{\"id\":\"bgf0zqpfa4g0\",\"created\":1507863477535,\"text\":\"3.失败\\n——持续103天\\n——仅存京师大学堂（北大前身，高等教育的发端）\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf10lj2ci88\",\"created\":1507863544631,\"text\":\"（二）失败原因（新派局限+守派反对）\\n——民族资产阶级的弱小 \\n——维派局限：不敢否定封建主义、对列强抱有幻想、惧怕人民群众\",\"layout_filetree-up_offset\":{\"x\":2,\"y\":1}},\"children\":[]},{\"data\":{\"id\":\"bgf13m9delko\",\"created\":1507863781314,\"text\":\"（三）失败启示\\n——自上而下的改良行不通\\n——必须革命\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgez4q120xs0\",\"created\":1507858225662,\"text\":\"第三章 辛亥革命\",\"layout_fish-bone-master_offset\":{\"x\":16,\"y\":-2},\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf15qo72yo0\",\"created\":1507863947646,\"text\":\"一、辛亥革命的前期\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf16gih43k0\",\"created\":1507864003896,\"text\":\"（一）辛亥革命爆发的意义\\n——必然产物：社会矛盾\\n——集中反映：民族独立、振兴中华\\n——集中体现：人民顽强斗争\"},\"children\":[]},{\"data\":{\"id\":\"bgf18a3wan4k\",\"created\":1507864146682,\"text\":\"（二）革命派的活动\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1bxayub4s\",\"created\":1507864432268,\"text\":\"1.兴中会\\n——第一个革命团体\\n——高举民主革命的旗帜《中国问题的真解决》\\n——武装起义（不同于改良派的根本）\"},\"children\":[]},{\"data\":{\"id\":\"bgf1d295vmgc\",\"created\":1507864521407,\"text\":\"2.中国同盟会\\n——第一个领导资产阶级革命的全国性政党\\n——标志：民主革命进入新阶段\\n——机关报《民报》\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf1ephuo80g\",\"created\":1507864650363,\"text\":\"（三）三民主义\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1f62fle88\",\"created\":1507864686436,\"text\":\"1.民族（驱除鞑虏，恢复中华）\\n——局限1.没有明确的反帝纲领，放走了最大敌人\\n——局限2.重视满族封建，放松汉族封建\"},\"children\":[]},{\"data\":{\"id\":\"bgf1ha4x6qgc\",\"created\":1507864852022,\"text\":\"2.民权（创立民国）\\n——局限：建立资产阶级专政的国家，远离了群众\"},\"children\":[]},{\"data\":{\"id\":\"bgf1hxk25z40\",\"created\":1507864903003,\"text\":\"3.民生（平均地权）\\n——局限：未分给农民土地、未满足农民要求、未正面触及封建土地所有制\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf1imyeijkk\",\"created\":1507864958290,\"text\":\"（四）革命与改良的论战\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1j2glicgg\",\"created\":1507864992042,\"text\":\"1.论战问题\\n——要不要使用革命手段（焦点）\\n——要不要推翻帝制，实行共和\\n——要不要社会革命\"},\"children\":[]},{\"data\":{\"id\":\"bgf1k5n5hswk\",\"created\":1507865077333,\"text\":\"2.论战局限\\n——反帝反封不彻底、群众不重视\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgf1l9mn79c0\",\"created\":1507865164373,\"text\":\"二、辛亥革命的高潮\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1lhq3tk8o\",\"created\":1507865181997,\"text\":\"（一）武昌起义\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1lqud5wgk\",\"created\":1507865201845,\"text\":\"1.武装起义\\n——同盟会第一次：萍浏醴起义\\n——同盟会两著名：广州新军起义、黄花岗起义（影响最大）\\n——全川暴动：保路风潮-成都血案\"},\"children\":[]},{\"data\":{\"id\":\"bgf1o87bw5c0\",\"created\":1507865396363,\"text\":\"2.武昌起义\\n——武昌起义：打开了清王朝统治的缺口\\n——武昌起义后：封建帝制覆灭\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf1pf5cwbkg\",\"created\":1507865489845,\"text\":\"（二）中华民国\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1pk8kew0k\",\"created\":1507865500923,\"text\":\"1.南京临时政府\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1sa5wn9s8\",\"created\":1507865714087,\"text\":\"A.资产阶级共和国\\n——成员：资产阶级革命派居于领导和主体地位\\n——政策：反映资产阶级愿望，一定程度反映群众\"},\"children\":[]},{\"data\":{\"id\":\"bgf1ss4sjbsc\",\"created\":1507865753202,\"text\":\"B.局限\\n——承认不平等条约，以换取列强承认\\n——保护官僚、地主\\n——未满足农民对土地的要求\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf1uaq9bsow\",\"created\":1507865872046,\"text\":\"2.中华民国临时约法\\n——第一部具有资产阶级共和国宪法性质的法典\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgf1v2bjot4c\",\"created\":1507865932106,\"text\":\"三、辛亥革命的失败\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgf1vcauo0wg\",\"created\":1507865953832,\"text\":\"（一）辛亥革命失败的标志\\n——袁世凯建立北洋军阀（大地主+买办资产阶级）\"},\"children\":[]},{\"data\":{\"id\":\"bgf1w627o9sg\",\"created\":1507866018613,\"text\":\"（二）旧民主主义革命失败的标志\\n——护法运动的失败\"},\"children\":[]},{\"data\":{\"id\":\"bgf1x6mvcogs\",\"created\":1507866098226,\"text\":\"（三）失败原因\\n——根本原因：资本主义行不通\\n——主观原因：反帝反封不彻底、群众不重视、革命政党不坚强\"},\"children\":[]}]},{\"data\":{\"id\":\"bgf1zoc5o34s\",\"created\":1507866293489,\"text\":\"四、辛亥革命的评价\\n——准备了党的阶级基础、理论基础、干部条件\"},\"children\":[]}]},{\"data\":{\"id\":\"bgez57qtpj40\",\"created\":1507858264226,\"text\":\"第四章 开天辟地的大事变\"},\"children\":[{\"data\":{\"id\":\"bgfuaqngpk8o\",\"created\":1507946151609,\"text\":\"一、新文化运动与五四运动\"},\"children\":[{\"data\":{\"id\":\"bgfubo5f47c4\",\"created\":1507946224529,\"text\":\"（一）新文化运动\",\"expandState\":\"collapse\"},\"children\":[{\"data\":{\"id\":\"bgfucow97ww8\",\"created\":1507946304516,\"text\":\"1.兴起\\n——开始：陈独秀，在上海创办《青年》（后改为《新青年》）\\n——主要阵地：《新青年》杂志+北京大学\"},\"children\":[]},{\"data\":{\"id\":\"bgfudwthz00s\",\"created\":1507946400128,\"text\":\"2.内容\\n——口号：民主科学\\n——攻击封建文化：打倒孔家店\\n——原因：提倡民主科学+为发展资本主义扫清障碍\"},\"children\":[]},{\"data\":{\"id\":\"bgfufm8nf484\",\"created\":1507946533827,\"text\":\"3.局限\\n——a.倡导资本主义\\n——b.优先改造国民性\\n——c.没有马克思主义的批判精神\"},\"children\":[]}]},{\"data\":{\"id\":\"bgfuby5y7y80\",\"created\":1507946246329,\"text\":\"（二）十月革命\\n——重要启示：落后国家也可以用社会主义思想解放\\n——有力推动：社会主义思想在中国传播\\n——革命方法的启示\"},\"children\":[]},{\"data\":{\"id\":\"bgfuc5hijqos\",\"created\":1507946262266,\"text\":\"（三）五四运动——新民主主义革命的开端\",\"expandState\":\"expand\"},\"children\":[{\"data\":{\"id\":\"bgfuj0w4kgwg\",\"created\":1507946800814,\"text\":\"1.爆发条件\\n——新阶级：资产阶级+工人阶级\\n——新文化运动：思想解放的潮流\\n——十月革命\\n——直接导火线：巴黎和会上中国外交失败\"},\"children\":[]},{\"data\":{\"id\":\"bgfuldgxx28g\",\"created\":1507946984923,\"text\":\"2.特点\\n——彻底的反帝反封\\n——真正的群众运动\\n——促进马克思主义在中国的传播+与中国工人运动的结合\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bgfuavq29z40\",\"created\":1507946162651,\"text\":\"二、马克思主义传播与中国共产党诞生\"},\"children\":[]},{\"data\":{\"id\":\"bgfubieq2mo8\",\"created\":1507946212031,\"text\":\"三、中国革命新局面\"},\"children\":[]}]},{\"data\":{\"id\":\"bgez5ijfb2o8\",\"created\":1507858287723,\"text\":\"第五章 中国革命新道路\"},\"children\":[]},{\"data\":{\"id\":\"bgez5pzaef40\",\"created\":1507858303920,\"text\":\"第六章 抗日战争\"},\"children\":[]},{\"data\":{\"id\":\"bgez6ahxbaos\",\"created\":1507858348582,\"text\":\"第七章 新中国\"},\"children\":[]},{\"data\":{\"id\":\"bgez6kk2ui0o\",\"created\":1507858370480,\"text\":\"第八章 社会主义制度确定\"},\"children\":[]},{\"data\":{\"id\":\"bgez6skm8b48\",\"created\":1507858387927,\"text\":\"第九章 社会主义制度探索\"},\"children\":[]},{\"data\":{\"id\":\"bgez74l166wc\",\"created\":1507858414074,\"text\":\"第十章 改革开放\"},\"children\":[]}]},\"template\":\"fish-bone\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"19420e1aab170048c88ef1c4ae656aab","csrf_token":"0b9297559a63369f8e60e0c6d7755d03"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3485.400 QQBrowser/9.6.12190.400

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
