### ISSUE TITLE
问题反馈：经常性发生504错误

### ISSUE THREAD

**Issue by songnan1026** [fex-team/kityminder-editor#524]
错误
 {"data":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.9.2</center>\r\n</body>\r\n</html>\r\n","status":504,"config":{"method":"POST","transformResponse":[null],"url":"bos/get_root_dir","data":{"csrf_token":"d655bd452126d18d60ff27b5b0e5f1c6"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Gateway Timeout"}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by zhangbobell** [comment]
503 或 504 问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
