### ISSUE TITLE
经常提示有误，会自动刷新删除内容，不可还原

### ISSUE THREAD

**Issue by DeanLeung** [fex-team/kityminder-editor#527]
错误
 {"data":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>503 - Service Not Available</title>\n </head>\n <body>\n  <h1>503 - Service Not Available</h1>\n </body>\n</html>\n","status":503,"config":{"method":"POST","transformResponse":[null],"url":"bos/touch","data":{"fileName":"Java项目副本","parentGuid":"264c955fb4e1b0fd61b7887066980b52","template":"","version":"1.4.43","csrf_token":"ad4ed732462a064ba6e931e3a3dc4573"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Service Unavailable"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经修复，详见公告 https://tieba.baidu.com/p/5375015202
