### ISSUE TITLE
BUG: 复制链接按钮是 Flash，高版本 Chrome 默认禁止加载

### ISSUE THREAD

**Issue by XuyangJia** [fex-team/kityminder-editor#531]
脑图分享时，点击复制链接不管事儿  按钮是个摆设吗？
环境:  win7 + Chrome
![1](https://user-images.githubusercontent.com/25972889/31765908-95e10c18-b4f8-11e7-8b9b-47310b259507.png)

**Comment by zhangbobell** [comment]
为保证兼容性，复制按钮使用了 flash 文件，而你的 Chrome 浏览器如果版本高的话，会默认组织 flash 的加载，在地址栏的右侧点击允许即可。后续我们会对这一块进行优化。感谢反馈。

**Comment by Dafrok** [comment]
fixed
