### ISSUE TITLE
百度脑图 用户建议

### ISSUE THREAD

**Issue by mcluster** [fex-team/kityminder-editor#584]
百度脑图组你好。
  我今天初次尝试使用该产品，很是喜欢，稍微改善了我对百度的偏见。不过在使用过程中发现以下这个问题：
      
  在我欲拖拽整个脑图移动从而对周围区域进行阅览时，只能通过导航小窗点击拖动实现。

  我建议可以学习Maya、3DMAX等软件的交互方式，通过持续按住鼠标中键并拖拽鼠标以达到移动整个脑图的功能。
  谢谢！
一位痛并快乐着的百度用户
-------------------------------------------------------
发现鼠标右键可以实现该功能。但无法通过波动鼠标中键放大缩小。

**Comment by Dafrok** [comment]
review 了下源码，本来 `ctrl + 鼠标滚轮` 是可以缩放的，貌似前辈手滑拼错了一个字符串，如果你等不及发版可以照着 https://github.com/fex-team/kityminder-core/commit/6c9a32395a558417a5ca72182ffa3da336f34381 自己打个补丁

**Comment by Vmpy** [comment]
@Dafrok emmm，万一对面是个非计算机人士怎么办 *自己打个补丁*

**Comment by Dafrok** [comment]
@Vmpy 这里不是脑图的产品社区，是开源编辑器 kityminder 的 issue 区，职能上只用于解决编辑器本身的问题，不懂大概都去贴吧和 QQ 群问了吧（
