### ISSUE TITLE
脑图错误反馈

### ISSUE THREAD

**Issue by reconcil** [fex-team/kityminder-editor#585]
错误
 {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<meta charset=\"utf-8\" />\n<head>\n<title>Database Error</title>\n<style type=\"text/css\">\n\n::selection{ background-color: #E13300; color: white; }\n::moz-selection{ background-color: #E13300; color: white; }\n::webkit-selection{ background-color: #E13300; color: white; }\n\nbody {\n\tbackground-color: #fff;\n\tmargin: 40px;\n\tfont: 13px/20px normal Helvetica, Arial, sans-serif;\n\tcolor: #4F5155;\n}\n\na {\n\tcolor: #003399;\n\tbackground-color: transparent;\n\tfont-weight: normal;\n}\n\nh1 {\n\tcolor: #444;\n\tbackground-color: transparent;\n\tborder-bottom: 1px solid #D0D0D0;\n\tfont-size: 19px;\n\tfont-weight: normal;\n\tmargin: 0 0 14px 0;\n\tpadding: 14px 15px 10px 15px;\n}\n\ncode {\n\tfont-family: Consolas, Monaco, Courier New, Courier, monospace;\n\tfont-size: 12px;\n\tbackground-color: #f9f9f9;\n\tborder: 1px solid #D0D0D0;\n\tcolor: #002166;\n\tdisplay: block;\n\tmargin: 14px 0 14px 0;\n\tpadding: 12px 10px 12px 10px;\n}\n\n#container {\n\tmargin: 10px;\n\tborder: 1px solid #D0D0D0;\n\t-webkit-box-shadow: 0 0 8px #D0D0D0;\n}\n\np {\n\tmargin: 12px 15px 12px 15px;\n}\n</style>\n</head>\n<body>\n\t<div id=\"container\">\n\t\t<h1>发生了一个数据库错误</h1>\n\t\t<p>Error Number: 1205</p><p>Lock wait timeout exceeded; try restarting transaction</p><p>UPDATE `kityminder_file` SET `size` = size + 573, `last_modified_user` = '3828341913', `last_modified_time` = '2018-03-01 10:20:00', `last_modified_user_name` = 'reconcil1' WHERE `file_guid` =  'a91eb6d4874c8b884b4f98148a96ae5a' LIMIT 1</p><p>Filename: /var/www/kityminder/models/mbos.php</p><p>Line Number: 236</p>\t</div>\n</body>\n</html>","status":500,"config":{"method":"POST","transformResponse":[null],"url":"bos/save","data":{"strJson":"{\"root\":{\"data\":{\"id\":\"373505e0e4ca\",\"created\":1519627848,\"text\":\"spark 内存管理\",\"note\":\"我们知道在执行 Spark 的应用程序时，Spark 集群会启动 Driver 和 Executor 两种 JVM 进程，前者为主控进程，负责创建 Spark 上下文，提交 Spark 作业（Job），并将作业转化为计算任务（Task），在各个 Executor 进程间协调任务的调度，后者负责在工作节点上执行具体的计算任务，并将结果返回给 Driver，同时为需要持久化的 RDD 提供存储功能。由于 Driver 的内存管理相对来说较为简单，本文主要对 Executor\\n 的内存管理进行分析，下文中的 Spark 内存均特指 Executor 的内存。\"},\"children\":[{\"data\":{\"id\":\"bjp8jd72lxc0\",\"created\":1519868838067,\"text\":\"基于JVM的Spark内存管理\",\"note\":\"我们知道，JVM 的对象可以以序列化的方式存储，序列化的过程是将对象转换为二进制字节流，本质上可以理解为将非连续空间的链式存储转化为连续空间或块存储，在访问时则需要进行序列化的逆过程——反序列化，将字节流转化为对象，序列化的方式可以节省存储空间，但增加了存储和读取时候的计算开销。\\n\\n对于 Spark 中序列化的对象，由于是字节流的形式，其占用的内存大小可直接计算，而对于非序列化的对象，其占用的内存是通过周期性地采样近似估算而得，即并不是每次新增的数据项都会计算一次占用的内存大小，这种方法降低了时间开销但是有可能误差较大，导致某一时刻的实际内存有可能远远超出预期。此外，在被 Spark 标记为释放的对象实例，很有可能在实际上并没有被 JVM 回收，导致实际可用的内存小于 Spark 记录的可用内存。所以 Spark 并不能准确记录实际可用的堆内内存，从而也就无法完全避免内存溢出（OOM,\\n Out of Memory）的异常。\\n\\n虽然不能精准控制堆内内存的申请和释放，但 Spark 通过对存储内存和执行内存各自独立的规划管理，可以决定是否要在存储内存里缓存新的 RDD，以及是否为新的任务分配执行内存，在一定程度上可以提升内存的利用率，减少异常的出现。\"},\"children\":[]},{\"data\":{\"id\":\"bjp8lgmkunsw\",\"created\":1519869002263,\"text\":\"内存管理接口\",\"note\":\"Spark 为存储内存和执行内存的管理提供了统一的接口——MemoryManager，同一个 Executor 内的任务都调用这个接口的方法来申请或释放内存:\\n\\n内存管理接口的主要方法：\\n//申请存储内存\\ndef acquireStorageMemory(blockId: BlockId, numBytes: Long, memoryMode: MemoryMode): Boolean\\n//申请展开内存\\ndef acquireUnrollMemory(blockId: BlockId, numBytes: Long, memoryMode: MemoryMode): Boolean\\n//申请执行内存\\ndef acquireExecutionMemory(numBytes: Long, taskAttemptId: Long, memoryMode: MemoryMode): Long\\n//释放存储内存\\ndef releaseStorageMemory(numBytes: Long, memoryMode: MemoryMode): Unit\\n//释放执行内存\\ndef releaseExecutionMemory(numBytes: Long, taskAttemptId: Long, memoryMode: MemoryMode): Unit\\n//释放展开内存\\ndef releaseUnrollMemory(numBytes: Long, memoryMode: MemoryMode): Unit\\n\\n我们看到，在调用这些方法时都需要指定其内存模式（MemoryMode），这个参数决定了是在堆内还是堆外完成这次操作。\\n\\nMemoryManager 的具体实现上，Spark 1.6 之后默认为统一管理（Unified Memory Manager）方式，1.6 之前采用的静态管理（Static\\n Memory Manager）方式仍被保留，可通过配置 spark.memory.useLegacyMode 参数启用。\"},\"children\":[]},{\"data\":{\"id\":\"bjp83oz5wwwk\",\"created\":1519867609883,\"text\":\"Driver的JVM\",\"note\":\"主控进程，负责创建 Spark 上下文，提交 Spark 作业（Job），并将作业转化为计算任务（Task），在各个 Executor 进程间协调任务的调度\"},\"children\":[]},{\"data\":{\"id\":\"bjp83siq8lk4\",\"created\":1519867617596,\"text\":\"Executor的JVM\",\"note\":\"负责在工作节点上执行具体的计算任务，并将结果返回给 Driver，同时为需要持久化的 RDD 提供存储功能。\",\"image\":\"http://img.blog.csdn.net/20171205211028629?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvd2VpeGluXzM1NjAyNzQ4/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":144}},\"children\":[{\"data\":{\"id\":\"bjp89kdf6b4s\",\"created\":1519868070046,\"text\":\"堆内内存\",\"note\":\"堆内内存的大小，由 Spark 应用程序启动时的 –executor-memory 或 spark.executor.memory 参数配置\"},\"children\":[{\"data\":{\"id\":\"bjp8a3phgdcg\",\"created\":1519868112135,\"text\":\"1）存储（Storage）内存\",\"note\":\"Executor 内运行的并发任务共享 JVM 堆内内存，这些任务在\\n缓存 RDD 数据和广播（Broadcast）数据时占用的内存被规划为存储（Storage）内存\"},\"children\":[]},{\"data\":{\"id\":\"bjp8b4hriy0o\",\"created\":1519868192209,\"text\":\"2)执行（Execution）内存\",\"note\":\"这些任务在执行 Shuffle 时占用的内存被规划为执行（Execution）内存\"},\"children\":[]},{\"data\":{\"id\":\"bjp8c0t8ojcw\",\"created\":1519868262560,\"text\":\"3)剩余内存\",\"note\":\"剩余的部分不做特殊规划，那些 Spark 内部的对象实例，或者用户定义的 Spark 应用程序中的对象实例，均占用剩余的空间。不同的管理模式下，这三部分占用的空间大小各不相同\"},\"children\":[]},{\"data\":{\"id\":\"bjp8qhqgof4g\",\"created\":1519869396495,\"text\":\"静态内存管理\",\"image\":\"http://img.blog.csdn.net/20171205211034002?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvd2VpeGluXzM1NjAyNzQ4/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center\",\"imageTitle\":\"\",\"imageSize\":{\"width\":200,\"height\":114},\"note\":\"在 Spark 最初采用的静态内存管理机制下，存储内存、执行内存和其他内存的大小在 Spark 应用程序运行期间均为固定的，但用户可以应用程序启动前进行配置，堆内内存的分配\\n\\n60%（90%（---80%（存储的是RDD的缓存数据和广播变量）---20%（unroll内存：解压序列化的数据)）---10%（预留出来的））---20%（80%（用于Shuffle聚合）---20%（预留内存，防止OOM））---20%（线程执行所需要的内存：task的计算）\"},\"children\":[{\"data\":{\"id\":\"bjp8ytiuxhc0\",\"created\":1519870049070,\"text\":\"storage内存区域\",\"note\":\"由spark.storage.memoryFraction\\n控制 默认为0.6，占系统内存的60%\\n\"},\"children\":[{\"data\":{\"id\":\"bjp90yw2hrks\",\"created\":1519870217481,\"text\":\"预留\",\"note\":\"可防止OOM\\n由spark.storage.safetyFractoin控制\\n默认为10%\\n\"},\"children\":[]},{\"data\":{\"id\":\"bjp9202gay8s\",\"created\":1519870298408,\"text\":\"可用的storage内存\",\"note\":\"用于缓存RDD数据和广播数据\\n由（1-spark.storage.safetyFractoin）控制\"},\"children\":[{\"data\":{\"id\":\"bjp95a0nhc00\",\"created\":1519870555160,\"text\":\"用于unroll\",\"note\":\" 缓存iterator形式的block数据由\\n spark.storage.unrollFaction控制\\n 默认0.2，占用storage内存的20%\\n \\n \"},\"children\":[]}]}]},{\"data\":{\"id\":\"bjp8zv8fgmww\",\"created\":1519870131157,\"text\":\"Execution内存区域\",\"note\":\"由spark.shuffle.memoryFrction控制 默认为0.2，占系统内存的20%\"},\"children\":[{\"data\":{\"id\":\"bjp96udf38gg\",\"created\":1519870677831,\"text\":\" \",\"note\":\"防止OOM\\n由sparks\"},\"children\":[]}]},{\"data\":{\"id\":\"bjp90gkmn00s\",\"created\":1519870177607,\"text\":\"其他\",\"note\":\"取决于上面两部分的大小\\n默认为0.2，占系统内存的20%\\n\"},\"children\":[]}]}]},{\"data\":{\"id\":\"bjp8d9mlcv4k\",\"created\":1519868360113,\"text\":\"堆外内存\",\"note\":\"为了进一步优化内存的使用以及提高 Shuffle 时排序的效率，Spark 引入了堆外（Off-heap）内存，使之可以直接在工作节点的系统内存中开辟空间，存储经过序列化的二进制数据。利用 JDK Unsafe API（从 Spark 2.0 开始，在管理堆外的存储内存时不再基于 Tachyon，而是与堆外的执行内存一样，基于 JDK Unsafe API 实现），Spark 可以直接操作系统堆外内存，减少了不必要的内存开销，以及频繁的 GC 扫描和回收，提升了处理性能。堆外内存可以被精确地申请和释放，而且序列化的数据占用的空间可以被精确计算，所以相比堆内内存来说降低了管理的难度，也降低了误差。\\n\\n在默认情况下堆外内存并不启用，可通过配置 spark.memory.offHeap.enabled 参数启用，并由 spark.memory.offHeap.size 参数设定堆外空间的大小。除了没有 other 空间，堆外内存与堆内内存的划分方式相同，所有运行中的并发任务共享存储内存和执行内存。\"},\"children\":[]},{\"data\":{\"id\":\"bjp8g6q0vaww\",\"created\":1519868588883,\"text\":\"运行流程\",\"note\":\"申请内存：\\n\\nSpark 在代码中 new 一个对象实例\\n\\nJVM 从堆内内存分配空间，创建对象并返回对象引用\\n\\nSpark 保存该对象的引用，记录该对象占用的内存\\n\\n释放内存：\\n\\nSpark 记录该对象释放的内存，删除该对象的引用\\n\\n等待 JVM 的垃圾回收机制释放该对象占用的堆内内存\\n\"},\"children\":[]}]}]},\"template\":\"right\",\"theme\":\"fresh-blue\",\"version\":\"1.4.43\"}","fileGuid":"a91eb6d4874c8b884b4f98148a96ae5a","csrf_token":"54dab62d87e955c2bfde1063b196b76d"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by 378978764** [comment]
同样遇到了这个问题，至今没有修复！
