### ISSUE TITLE
这线条有些挡功能了啊

### ISSUE THREAD

**Issue by Joypigg** [fex-team/kityminder-editor#602]
![image](https://user-images.githubusercontent.com/33863704/38163453-f09f74f6-3526-11e8-9a38-8372424ef998.png)

**Comment by Joypigg** [comment]
![image](https://user-images.githubusercontent.com/33863704/38163637-0e5f1c28-352a-11e8-8171-c32b84bd6a6b.png)
好了，自己解决了

**Comment by Dafrok** [comment]
你的 zoom 不是 100% 吧

**Comment by Joypigg** [comment]
我浏览器版本是这、可是我回复浏览器默认设置了，还是不管用


在2018年3月31日 23:47，马金花儿<notifications@github.com> 写道：

你的 zoom 不是 100% 吧

**Comment by zhangbobell** [comment]
@Joypigg 使用 `Ctrl + 0` 恢复 100% 视图就行了

**Comment by Joypigg** [comment]
好的、可以了
在2018年4月1日 20:40，Bo Zhang<notifications@github.com> 写道：

@Joypigg 使用 Ctrl + 0 恢复 100% 视图就行了
