### ISSUE TITLE
编辑节点时光标行为异常

### ISSUE THREAD

**Issue by trustgit** [fex-team/kityminder-editor#611]
环境：Windows 10, Google Chrome 66.0.3359.139, 百度脑图
在编辑时通过方向键或鼠标点击来移动光标时，会异常地显示为选中一个字符
并且试图在选中位置编辑时，光标选中的以及其后的文字会依次被新输入的文字替换
![test2](https://user-images.githubusercontent.com/25559236/39403276-01b205d0-4baa-11e8-967d-b1dfd4adf665.gif)
![test](https://user-images.githubusercontent.com/25559236/39403277-02013812-4baa-11e8-8afc-3e3a0654c256.gif)

**Comment by trustgit** [comment]
Closing since this repo is not under good maintenance.
[rant: did you guys write this for KPI?]

**Comment by Dafrok** [comment]
目测你按了下键盘上的 insert。
