### ISSUE TITLE
【kityminder-hotbox】【sougou】在sougou浏览器下esc键无法正常使用

### ISSUE THREAD

**Issue by Naixor** [fex-team/kityminder-editor#63]
搜狗浏览器标准模式下esc键只有keyup时才触发，但目前的Hotbox源码中https://github.com/fex-team/hotbox/blob/master/src/hotbox.js#L428 只是针对keydown的情况下才处理esc键的逻辑，导致不可用。

**Comment by zhangbobell** [comment]
问题已经修复 cb6707e688fffa837c6c2114019b194b879ba536

**Comment by zhangbobell** [comment]
hotbox 上的 esc 的问题仍然存在，因为 sogou 浏览器只有 keyup 时才识别，跟是否开启输入法无关。而 hotbox 存在处理按键事件的三个阶段，因此仅仅修复了 input 框内的 esc 事件。
