### ISSUE TITLE
Chrome浏览器中布局问题

### ISSUE THREAD

**Issue by JsHuang** [fex-team/kityminder-editor#636]
在Chrome浏览器中，思路和布局页面，均有部分遮挡情况
Chrome 版本： 67.0.3396.62（正式版本） （64 位）
示例图

![image](https://user-images.githubusercontent.com/5506543/40895400-cd9a27ce-67e1-11e8-8879-afe511ee6cb4.png)

**Comment by Dafrok** [comment]
ctrl+鼠标滚轮缩放到 100%

**Comment by JsHuang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
依然会被覆盖，使用放大到 175%，显示才正确



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    
--Kind Regards!-Jin Huang

                


    在2018年6月4日 11:01，马金花儿<notifications@github.com> 写道： 


ctrl+鼠标滚轮缩放到 100%

**Comment by JsHuang** [comment]
这个方法没用，不知道是系统原因还是什么。我需要放大到150%才行。

**Comment by zhangbobell** [comment]
@JsHuang `Ctrl + 0` 恢复到 100% 视图就好了

**Comment by JsHuang** [comment]
谢谢回复，但是还是没解决，使用IE浏览器，视图放大或者缩小均无问题。我使用chrome 100%也不行

**Comment by JsHuang** [comment]
@Dafrok 如果在win10系统中启用了自定义缩放比例，就会出现这个问题，浏览器调节百分比到100是没有用的，但是IE没有影响。

**Comment by JsHuang** [comment]
手机和桌面上的生词本不能同步到一起，手机使用了微软账户登录，为什么生词本和桌面版本的无法同步，桌面版本也是使用微软账户
