### ISSUE TITLE
【kityminder-editor】【firefox 37.0.1】input编辑时左右键失效，无法控制光标位置

### ISSUE THREAD

**Issue by Naixor** [fex-team/kityminder-editor#65]

**Comment by Naixor** [comment]
这个问题，确定是左右键导致receiver blur触发，且不该是kityminder本身的逻辑问题，但还未找到是那个第三方插件导致左右键触发了blur事件（一直怀疑CodeMirror，但可惜把它干掉后此问题依旧复现）。先记下一个单独针对FF36&&37此BUG亡羊补牢的弥补措施，增加一个判定receiver是否编辑完成的tag，若为完成则receiver.onblur = funcition(){ setTimeout(function() { receiver.focus(); }, 0); }; 愿佛祖保佑日后可找到问题源头 - -

**Comment by zhangbobell** [comment]
佛祖还是保佑咱们的，找到了问题，由于 firefox 的 user-select 和 div 的 contenteditable 属性冲突造成的 blur 。solved by commit 58b45307e87c2ccb76c324e23a7a15e9bf75c571
