### ISSUE TITLE
无法创建脑图

### ISSUE THREAD

**Issue by hrp61** [fex-team/kityminder-editor#697]
今天无法创建新脑图
提示
创建脑图失败,请重试
换浏览器也不行

错误
 {"data":null,"status":-1,"config":{"method":"POST","transformResponse":[null],"url":"bos/ls","data":{"dirGuid":"3edd633149f2570e6d576008d3884409","csrf_token":"07a2df4b49f2b28e1d202e8566b2d278"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded"},"cached":false},"statusText":""}

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by Dafrok** [comment]
已修复
