### ISSUE TITLE
脑图 500 没法打开

### ISSUE THREAD

**Issue by toxic-johann** [fex-team/kityminder-editor#716]
脑图地址 http://naotu.baidu.com/file/4a0a33cf75ce1548a62ba151c19abf1d

该地址 500 没法打开

**Comment by Ronghengzhen** [comment]
> 脑图地址 http://naotu.baidu.com/file/4a0a33cf75ce1548a62ba151c19abf1d
> 
> 该地址 500 没法打开

我的是保存的时候出现错误500

**Comment by lvxuan263** [comment]
metoo 保存的时候提示500
