### ISSUE TITLE
分享脑图的 复制链接按钮 失效

### ISSUE THREAD

**Issue by OrdinaryFish** [fex-team/kityminder-editor#725]
Chrome 版本：

Google Chrome 已是最新版本
版本 71.0.3578.98（正式版本） （32 位）

**Comment by chenjiaren145** [comment]
我也存在同样的问题，电脑系统Mac Mojave 10.14.2 ，浏览器Chrome 71.0.3578.98（正式版本） ，都是最新版本

**Comment by Dafrok** [comment]
flash 被淘汰了，抽空换成别的

**Comment by Dafrok** [comment]
fixed
