### ISSUE TITLE
中文输入法ESC取消拼音输入时退出节点编辑框

### ISSUE THREAD

**Issue by ezgen** [fex-team/kityminder-editor#728]
当错误输入拼音用ESC键取消该段拼音时，会直接关闭节点编辑框，也就是相当于返回了2个ESC，导致前面输入的汉字未保存而丢失。
正常应该是只取消输入法拼音框，保持节点编辑框编辑状态（可参考Windows下修改文件名的操作）。
更多信息反馈可邮件至45456196@qq.com.

![image](https://user-images.githubusercontent.com/47061830/51790008-9c3f1100-21ca-11e9-915f-c6034840080f.png)

**Comment by new08** [comment]
应该是 [fixex sogou brower esc key cancel input bug](https://github.com/fex-team/kityminder-editor/commit/cb6707e688fffa837c6c2114019b194b879ba536#diff-e849aec92402ca7583d4d4d461b201dd) 这里引进的 bug

https://github.com/fex-team/kityminder-editor/blob/cb6707e688fffa837c6c2114019b194b879ba536/src/runtime/jumping.js#L84

**Comment by Dafrok** [comment]
fixed in 1.0.67

**Comment by ezgen** [comment]
> fixed in 1.0.65

百度脑图当前版本：1.4.43 **还有这个情况**。

使用环境：
Windows 10 Pro 中文版
Chrome 版本 70.0.3538.102（正式版本） （32 位）
搜狗拼音输入法 9.1 正式版（9.1.0.2657）

**Comment by Dafrok** [comment]
你说的版本不是 kityminder-editor 吧?

**Comment by ezgen** [comment]
> 你说的是脑图还是 kityminder-editor?

百度脑图。我不知道这个editor跟脑图是什么关系，从百度脑图的帮助页面上过来的。

**Comment by ezgen** [comment]
> 你说的是脑图还是 kityminder-editor?

百度脑图。我不知道这个editor跟脑图是什么关系，从百度脑图的帮助页面上过来的。

**Comment by Dafrok** [comment]
你的 1.4.43 版本号是从哪看到的

**Comment by ezgen** [comment]
> 你的 1.4.43 版本号是从哪看到的

![image](https://user-images.githubusercontent.com/47061830/52645966-c9a2f300-2f1c-11e9-820e-9df912223817.png)


![image](https://user-images.githubusercontent.com/47061830/52645937-bee85e00-2f1c-11e9-9d15-abb72ef81c77.png)

**Comment by Dafrok** [comment]
哦 懂了

kityminder-editor （也就是这个仓库）是一个开源软件，脑图是公司基于这个软件的线上产品，是分开维护的，我明天跟进一下吧

**Comment by ezgen** [comment]
[手心输入法ESC演示视频.zip](https://github.com/fex-team/kityminder-editor/files/2856465/ESC.zip)

**Comment by Dafrok** [comment]
fixed
http://naotu.baidu.com/user/changelog
