### ISSUE TITLE
第三方输入法ESC问题（含手心输入法的情况）

### ISSUE THREAD

**Issue by ezgen** [fex-team/kityminder-editor#730]
由于旧帖被关闭，重开帖。

手心输入法也是如此，因此不只是搜狗的问题，目前看来只有微软自带的输入法没有问题。

百度脑图当前版本：1.4.43 **还有这个情况**。

使用环境：
Windows 10 Pro 中文版
Chrome 版本 70.0.3538.102（正式版本） （32 位）
搜狗拼音输入法 9.1 正式版（9.1.0.2657）/ 手心输入法 2.7.0

--------------------------

fixed in 1.0.65

_Originally posted by @Dafrok in https://github.com/fex-team/kityminder-editor/issues/728#issuecomment-462740484_

**Comment by Dafrok** [comment]
#728
