### ISSUE TITLE
点击子节点或空白会跳到中心

### ISSUE THREAD

**Issue by mnilzb** [fex-team/kityminder-editor#737]
1. 点击子节点或空白会跳到中心，这样很不方便，如要编辑子节点，点击定位到子节点结果跳走了。。。
2. 子节点线条可能出现下方线条过短分叉到字体上，当然刷新可以自动变动正常

**Comment by Dafrok** [comment]
1、只有双击空白处才会跳回中心 https://github.com/fex-team/kityminder-core/blob/dev/src/module/view.js#L313-L317
2、没明白

**Comment by uiosun** [comment]
补充回答：
2. 脑图编辑界面中，"外观" 选项中有 “整理布局” 按钮，试试？

**Comment by ezgen** [comment]
确实有这种情况，Win10 1903，EDGE浏览器。
点击任何子节点会跳到主题居中
