### ISSUE TITLE
撤回功能API调用。

### ISSUE THREAD

**Issue by chengqinngling** [fex-team/kityminder-editor#739]
请问如何使用，API上没有卸载看到如何调用。请问有完整文档吗

**Comment by Dafrok** [comment]
https://github.com/fex-team/kityminder-editor/blob/master/src/runtime/history.js#L50-L58

**Comment by haihai0000003** [comment]
> https://github.com/fex-team/kityminder-editor/blob/master/src/runtime/history.js#L50-L58

您好,想向您请教一个问题,如何禁止拖拽脑图和禁止在脑图中滚轮滚动事件,
