### ISSUE TITLE
GFM语法使用列表后，缩进不正常

### ISSUE THREAD

**Issue by kmcbest** [fex-team/kityminder-editor#745]
测试代码

```
# 基本评价
11111
## 协同
* 2222
# 打法
1111
```
这时由于列表2222的缩进，造成“打法”的缩进不正常：打法应该和基本评价同缩进，但效果——见截图
![qq 20190307152302](https://user-images.githubusercontent.com/689023/53939015-ec27c680-40ec-11e9-8ecb-89b721902718.png)

浏览器：Firefox 56，Chrome 70.0.3650.1，均有此问题

**Comment by Dafrok** [comment]
请多打一个回车

**Comment by kmcbest** [comment]
> 
> 
> 请多打一个回车

收到，可以了，谢谢
