### ISSUE TITLE
【kityminder-editor】【all】目前input的逻辑未对粘贴复制文字做处理，而且粘贴复制文字未被加入到历史纪录队列中

### ISSUE THREAD

**Issue by Naixor** [fex-team/kityminder-editor#83]

**Comment by xulz** [comment]
选中节点，插入备注或链接，这个时候焦点已经在相应输入框，快捷键粘贴文字会直接创建以文字为内容的子节点。
这个bug很影响使用，基本意味这对这两个控件无法使用粘贴功能，绕过方式是拖拽。
请尽快修复。

**Comment by zhangbobell** [comment]
非常感谢你的反馈，这个 Bug 我们已经知晓并修复，将在下个更新上恢复正常。
