### ISSUE TITLE
9月14号新版BUG反馈

### ISSUE THREAD

**Issue by pksurecom** [fex-team/kityminder-editor#85]
1.不能对文件【不是文件夹】重新命名，却可以显示【重命名】功能；
2.【返回上一级】功能，一点击就返回到第二级大目录下（即root的一级子目录）；

一升级暂时就碰到这俩问题，用了其他的功能后再反馈哈；

大愚（QQ：1012921195，邮箱：pksurecom@163.com）

**Comment by zhangbobell** [comment]
这两个问题已经解决并上线，见 http://naotu.baidu.com/user/changelog
