### ISSUE TITLE
标签颜色怎么加了8个之后，后面的都是一样的白色了，以前不是这样的啊？

### ISSUE THREAD

**Issue by LACERBA** [fex-team/kityminder-editor#87]
![image](https://cloud.githubusercontent.com/assets/6136146/9929870/28189182-5d62-11e5-8288-6056f1ef541d.png)
而且能不能自定义颜色，和编辑删除呢？

**Comment by LACERBA** [comment]
@zhangbobell

**Comment by zhangbobell** [comment]
这个问题我们已经意识到了，下个版本将加入。
