### ISSUE TITLE
在 firefox 浏览器中，导入根节点是一张图片的 `xmind` 文件后，双击百度脑图的根节点会抛出异常

### ISSUE THREAD

**Issue by zswang** [fex-team/kityminder-editor#88]
## 大致步骤

1. 打开百度脑图，导入本地 `.xmind` 文件（中心是一张图）
图为 `xmind` 原稿
![image](https://cloud.githubusercontent.com/assets/536587/9936613/6892ff18-5d8f-11e5-8681-60acc7210dcc.png)

2. 导入成功后双击根节点，报错（参见『错误信息』）
图为导入百度脑图根节点为空
![image](https://cloud.githubusercontent.com/assets/536587/9936620/6f7fc34c-5d8f-11e5-9997-e92830ce7477.png)

## 环境

+ Windows、Firefox 40

## 错误信息

```
错误 http://naotu.baidu.com/public/dist/kityminder.online.min.js?_=a4cb90da2c437930
行号：34
错误信息：TypeError: a is null
列号：30340
错误对象：TypeError: a is null

浏览器信息：Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
```

## 来源

用户：恩铭（1群）反馈
时间：2015年09月17日22:54:59

## 其他

Mac Chrome 中没有复现

**Comment by Naixor** [comment]
多谢大叔反馈，这个问题是由于使用了
```JavaScript
HTMLElement.prototype.__defineSetter__("innerText", function(text) {
                this.innerHTML = text.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br>");
            })
```
FF下清空后导致text为null因此报错，已修复，还未更新到线上

**Comment by zhangbobell** [comment]
这个问题已经修复，@Naixor
