### ISSUE TITLE
读取文件失败

### ISSUE THREAD

**Issue by Lelandycrain** [fex-team/kityminder-editor#91]
错误
 503: 读取文件失败

浏览器信息：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by techird** [comment]
喜大普奔，这次上线解决了好多问题！

**Comment by zhangbobell** [comment]
:smile:
