### ISSUE TITLE
我的md脑图都没了怎么办！

### ISSUE THREAD

**Issue by hokerffb** [fex-team/kityminder-editor#92]
我比较喜欢markdown，所以过去用百度脑图的时候都是保存成md文件。
我昨天给别人演示东西找自己的一张脑图怎么也找不到，散会后观察，发现原始是百度脑图升级了，只支持km格式了，这样我过去所有的md脑图全部找不到了，界面上也没有导入md的入口，请问我该怎么办？都白写了吗？

**Comment by zhangbobell** [comment]
新版脑图有导入 md 格式的文件接口，在编辑界面有「打开本地文件」，你按照 FAQ 第二条自己导一下就行了。

**Comment by pengyuwei** [comment]
新的导入逻辑反人类啊。需要先创建空白文档才能导入。。。正常逻辑难道不是应该先导入再打开么。。。
而且过去支持md格式，现在不支持了变成必须导入，这个改变的原因是什么呢？
