### ISSUE TITLE
新版后chrome下快捷键失灵

### ISSUE THREAD

**Issue by lehman-china** [fex-team/kityminder-editor#95]
新版后chrome下快捷键失灵

**Comment by zhangbobell** [comment]
你好，请问是那几个快捷键失灵？还是所有的快捷键不能用了？

**Comment by lehman-china** [comment]
1.我这里是所有的快捷键失灵.
2.然后用IE11 尝试,无法从列表页跳转到,思维导图编辑页面.
3.复制url 到ie11 是能打开思维导图编辑页面的.
4.ie11所有快捷键有效.

**Comment by zhangbobell** [comment]
能否提供一下你的操作系统类型，浏览器类型，还有你说的快捷键（说明一个即可）？以便我们进一步跟进问题。

**Comment by zhangbobell** [comment]
IE 11.0 无法从子文件夹跳转到脑图编辑界面的问题已经解决。

**Comment by lehman-china** [comment]
1.windows 系统,
2.chrome 浏览器
3.insert 快捷键无效
4.过了这些天还是无效.~

**Comment by zhangbobell** [comment]
目前支持 F2 键插入，insert 快捷键我们会尽快加入。
