### ISSUE TITLE
请添加强制换行

### ISSUE THREAD

**Issue by liangsmood** [fex-team/kityminder-editor#99]
一个节点文字较多时排成一行很不方便阅读

**Comment by Naixor** [comment]
指的是类似excel那种表格内`自动换行`选项？
现在的话你可以先使用`shift + enter`，这个需求还真没考虑过。
但是自动换行的参考系又是什么呢？可否再说明下具体的样子，比如节点会随着你的文字内容增加而增加，但是超过最大边界就给你文字自动换行之类。没记错xmind也没有这个功能的

**Comment by zhangbobell** [comment]
使用 shift + enter 换行，见 FAQ。

**Comment by liangsmood** [comment]
好了，就是要这个。知识，为什么不和excel一致用alt+enter，我试了这个没有

**Comment by zhangbobell** [comment]
是不同的软件的问题，shift + 回车 也叫软回车，qq 的长文本换行就是这个。
